/*
 * PKL 51 - Subseksi Data Entry
 */

/*
 * PanelLogin.java
 *
 * Created on Jan 6, 2012, 9:08:51 PM
 */

package pkl51.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import pkl51.controller.LoginController;
import pkl51.model.MahasiswaModel;
import pkl51.model.event.MahasiswaListener;

/**
 *
 * @author ASUS
 */
public class PanelLogin extends javax.swing.JPanel implements MahasiswaListener{

    private LoginController controller;
    private MahasiswaModel model;
    /** Creates new form PanelLogin */
    public PanelLogin() {
        model = new MahasiswaModel();
        model.setListener(this);
        controller = new LoginController();
        controller.setModel(model);
        
        initComponents();
        textFieldNewPassword.setVisible(false);
        textFieldConfirmPassword.setVisible(false);
        labelNewPassword.setVisible(false);
        labelConfirmPassword.setVisible(false);
        buttonChange.setVisible(false);
        buttonCancel.setVisible(false);
    }

    public JPasswordField getTextFieldConfirmPassword() {
        return textFieldConfirmPassword;
    }

    public JPasswordField getTextFieldNewPassword() {
        return textFieldNewPassword;
    }

    public JPasswordField getTextFieldPassword() {
        return textFieldPassword;
    }

    public JTextField getTextFieldUsername() {
        return textFieldUsername;
    }

    public JButton getButtonChange() {
        return buttonChange;
    }

    public JButton getButtonCancel() {
        return buttonCancel;
    }

    public JButton getButtonLogin() {
        return buttonLogin;
    }

    public JLabel getLabelConfirmPassword() {
        return labelConfirmPassword;
    }

    public JLabel getLabelNewPassword() {
        return labelNewPassword;
    }

    public JButton getButtonExit() {
        return buttonExit;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonChange = new javax.swing.JButton();
        labelNewPassword = new javax.swing.JLabel();
        labelConfirmPassword = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        textFieldPassword = new pkl51.component.PasswordField();
        textFieldNewPassword = new pkl51.component.PasswordField();
        textFieldConfirmPassword = new pkl51.component.PasswordField();
        textFieldUsername = new pkl51.component.UserNameField();
        buttonExit = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(16, 224, 8));
        jLabel1.setText("Username");

        jLabel2.setForeground(new java.awt.Color(16, 224, 8));
        jLabel2.setText("Password");

        buttonChange.setText("Change");
        buttonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeActionPerformed(evt);
            }
        });

        labelNewPassword.setForeground(new java.awt.Color(16, 224, 8));
        labelNewPassword.setText("New Password");

        labelConfirmPassword.setForeground(new java.awt.Color(16, 224, 8));
        labelConfirmPassword.setText("Confirm Password");

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        textFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPasswordActionPerformed(evt);
            }
        });

        textFieldNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNewPasswordActionPerformed(evt);
            }
        });

        textFieldConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldConfirmPasswordActionPerformed(evt);
            }
        });

        textFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsernameActionPerformed(evt);
            }
        });

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(23, 23, 23))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(textFieldNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(textFieldConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(textFieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCancel)
                        .addGap(18, 18, 18)
                        .addComponent(buttonChange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExit)
                        .addGap(18, 18, 18)
                        .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNewPassword)
                    .addComponent(textFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConfirmPassword)
                    .addComponent(textFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin)
                    .addComponent(buttonCancel)
                    .addComponent(buttonChange)
                    .addComponent(buttonExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeActionPerformed
        // TODO add your handling code here:
        controller.changePassword(this);
    }//GEN-LAST:event_buttonChangeActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        controller.cancelChangePassword(this);
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        controller.login(this);
        textFieldNewPassword.requestFocusInWindow();
    }//GEN-LAST:event_buttonLoginActionPerformed

private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_buttonExitActionPerformed

private void textFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsernameActionPerformed
// TODO add your handling code here:
    textFieldPassword.requestFocusInWindow();
}//GEN-LAST:event_textFieldUsernameActionPerformed

private void textFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPasswordActionPerformed
// TODO add your handling code here:
    buttonLogin.requestFocusInWindow();
    controller.login(this);
}//GEN-LAST:event_textFieldPasswordActionPerformed

private void textFieldNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNewPasswordActionPerformed
// TODO add your handling code here:
    textFieldConfirmPassword.requestFocusInWindow();
}//GEN-LAST:event_textFieldNewPasswordActionPerformed

private void textFieldConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldConfirmPasswordActionPerformed
// TODO add your handling code here:
    buttonChange.requestFocusInWindow();
    controller.changePassword(this);
}//GEN-LAST:event_textFieldConfirmPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonChange;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelConfirmPassword;
    private javax.swing.JLabel labelNewPassword;
    private pkl51.component.PasswordField textFieldConfirmPassword;
    private pkl51.component.PasswordField textFieldNewPassword;
    private pkl51.component.PasswordField textFieldPassword;
    private pkl51.component.UserNameField textFieldUsername;
    // End of variables declaration//GEN-END:variables

    public void onChange(MahasiswaModel model) {
        textFieldUsername.setText(model.getNim());
        textFieldPassword.setText(model.getPassword());
    }

}
