/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Blok1.java
 *
 * Created on Feb 7, 2012, 8:54:35 PM
 */

package pkl51.view.kuesioner;

/**
 *
 * @author thiolutfi
 */
public class Blok1 extends javax.swing.JPanel {

    /** Creates new form Blok1 */
    public Blok1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new pkl51.component.Label();
        label3 = new pkl51.component.Label();
        label4 = new pkl51.component.Label();
        label5 = new pkl51.component.Label();
        label6 = new pkl51.component.Label();
        label7 = new pkl51.component.Label();
        label8 = new pkl51.component.Label();
        label9 = new pkl51.component.Label();
        label10 = new pkl51.component.Label();
        label11 = new pkl51.component.Label();
        label12 = new pkl51.component.Label();
        label13 = new pkl51.component.Label();
        label14 = new pkl51.component.Label();
        label15 = new pkl51.component.Label();
        label16 = new pkl51.component.Label();
        label17 = new pkl51.component.Label();
        label18 = new pkl51.component.Label();
        jPanel1 = new javax.swing.JPanel();
        textField5 = new pkl51.component.TextField();
        jPanel2 = new javax.swing.JPanel();
        textField8 = new pkl51.component.TextField();
        jPanel27 = new javax.swing.JPanel();
        textField24 = new pkl51.component.TextField();
        jPanel28 = new javax.swing.JPanel();
        textField25 = new pkl51.component.TextField();
        jPanel29 = new javax.swing.JPanel();
        textField26 = new pkl51.component.TextField();
        jPanel3 = new javax.swing.JPanel();
        label19 = new pkl51.component.Label();
        label20 = new pkl51.component.Label();
        label21 = new pkl51.component.Label();
        label22 = new pkl51.component.Label();
        label23 = new pkl51.component.Label();
        label24 = new pkl51.component.Label();
        label25 = new pkl51.component.Label();
        label26 = new pkl51.component.Label();
        label27 = new pkl51.component.Label();
        label28 = new pkl51.component.Label();
        label29 = new pkl51.component.Label();
        label30 = new pkl51.component.Label();
        label31 = new pkl51.component.Label();
        label32 = new pkl51.component.Label();
        label33 = new pkl51.component.Label();
        label34 = new pkl51.component.Label();
        label35 = new pkl51.component.Label();
        label36 = new pkl51.component.Label();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        textField1 = new pkl51.component.TextField();
        jPanel7 = new javax.swing.JPanel();
        textField2 = new pkl51.component.TextField();
        jPanel20 = new javax.swing.JPanel();
        textField17 = new pkl51.component.TextField();
        jPanel8 = new javax.swing.JPanel();
        textField4 = new pkl51.component.TextField();
        jPanel9 = new javax.swing.JPanel();
        textField3 = new pkl51.component.TextField();
        jPanel10 = new javax.swing.JPanel();
        textField6 = new pkl51.component.TextField();
        jPanel11 = new javax.swing.JPanel();
        textField7 = new pkl51.component.TextField();
        jPanel12 = new javax.swing.JPanel();
        textField9 = new pkl51.component.TextField();
        jPanel13 = new javax.swing.JPanel();
        textField10 = new pkl51.component.TextField();
        jPanel14 = new javax.swing.JPanel();
        textField11 = new pkl51.component.TextField();
        jPanel15 = new javax.swing.JPanel();
        textField12 = new pkl51.component.TextField();
        jPanel16 = new javax.swing.JPanel();
        textField13 = new pkl51.component.TextField();
        jPanel17 = new javax.swing.JPanel();
        textField14 = new pkl51.component.TextField();
        jPanel18 = new javax.swing.JPanel();
        textField16 = new pkl51.component.TextField();
        label1 = new pkl51.component.Label();
        jPanel19 = new javax.swing.JPanel();
        textField15 = new pkl51.component.TextField();
        jPanel21 = new javax.swing.JPanel();
        textField18 = new pkl51.component.TextField();
        jPanel22 = new javax.swing.JPanel();
        textField19 = new pkl51.component.TextField();
        jPanel23 = new javax.swing.JPanel();
        textField20 = new pkl51.component.TextField();
        jPanel24 = new javax.swing.JPanel();
        textField21 = new pkl51.component.TextField();
        jPanel25 = new javax.swing.JPanel();
        textField22 = new pkl51.component.TextField();
        jPanel26 = new javax.swing.JPanel();
        textField23 = new pkl51.component.TextField();
        jPanel30 = new javax.swing.JPanel();
        textField27 = new pkl51.component.TextField();
        jPanel31 = new javax.swing.JPanel();
        textField28 = new pkl51.component.TextField();
        jPanel32 = new javax.swing.JPanel();
        textField29 = new pkl51.component.TextField();
        jPanel33 = new javax.swing.JPanel();
        textField30 = new pkl51.component.TextField();
        jPanel34 = new javax.swing.JPanel();
        textField31 = new pkl51.component.TextField();
        jPanel35 = new javax.swing.JPanel();
        textField32 = new pkl51.component.TextField();
        jPanel36 = new javax.swing.JPanel();
        textField33 = new pkl51.component.TextField();
        jPanel37 = new javax.swing.JPanel();
        textField34 = new pkl51.component.TextField();
        jPanel38 = new javax.swing.JPanel();
        textField35 = new pkl51.component.TextField();
        jPanel39 = new javax.swing.JPanel();
        textField36 = new pkl51.component.TextField();
        jPanel40 = new javax.swing.JPanel();
        textField37 = new pkl51.component.TextField();
        jPanel41 = new javax.swing.JPanel();
        textField38 = new pkl51.component.TextField();
        jPanel42 = new javax.swing.JPanel();
        textField39 = new pkl51.component.TextField();
        jPanel43 = new javax.swing.JPanel();
        textField40 = new pkl51.component.TextField();
        jPanel44 = new javax.swing.JPanel();
        textField41 = new pkl51.component.TextField();
        jPanel45 = new javax.swing.JPanel();
        textField42 = new pkl51.component.TextField();
        jPanel46 = new javax.swing.JPanel();
        textField43 = new pkl51.component.TextField();
        jPanel47 = new javax.swing.JPanel();
        textField44 = new pkl51.component.TextField();
        jPanel48 = new javax.swing.JPanel();
        textField45 = new pkl51.component.TextField();
        jPanel49 = new javax.swing.JPanel();
        textField46 = new pkl51.component.TextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(721, 340));
        setLayout(null);

        label2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label2.setText("  *) kolom isian akan mengikuti kode yang diinput");
        add(label2);
        label2.setBounds(0, 310, 720, 30);

        label3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText(" Alamat (nama jalan/gang), RT/RW/Dusun");
        add(label3);
        label3.setBounds(30, 260, 210, 50);

        label4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("2");
        add(label4);
        label4.setBounds(0, 80, 30, 30);

        label5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("3");
        add(label5);
        label5.setBounds(0, 110, 30, 30);

        label6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label6.setText("4");
        add(label6);
        label6.setBounds(0, 140, 30, 30);

        label7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label7.setText("5");
        add(label7);
        label7.setBounds(0, 170, 30, 30);

        label8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setText("6");
        add(label8);
        label8.setBounds(0, 200, 30, 30);

        label9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label9.setText("7");
        add(label9);
        label9.setBounds(0, 230, 30, 30);

        label10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label10.setText("8");
        add(label10);
        label10.setBounds(0, 260, 30, 50);

        label11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label11.setText("1");
        add(label11);
        label11.setBounds(0, 50, 30, 30);

        label12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label12.setText(" Kabupaten");
        add(label12);
        label12.setBounds(30, 50, 210, 30);

        label13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label13.setText(" Kecamatan");
        add(label13);
        label13.setBounds(30, 80, 210, 30);

        label14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label14.setText(" Desa/Kelurahan");
        add(label14);
        label14.setBounds(30, 110, 210, 30);

        label15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label15.setText(" Nomor Blok Sensus");
        add(label15);
        label15.setBounds(30, 140, 210, 30);

        label16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label16.setText(" Nomor Urut Sampel Blok Sensus");
        add(label16);
        label16.setBounds(30, 170, 210, 30);

        label17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label17.setText(" Nomor Urut Sampel Rumah Tangga");
        add(label17);
        label17.setBounds(30, 200, 210, 30);

        label18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label18.setText(" Nama Kepala Rumah Tangga");
        add(label18);
        label18.setBounds(30, 230, 210, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        jPanel1.add(textField5);
        textField5.setBounds(20, 0, 440, 30);

        add(jPanel1);
        jPanel1.setBounds(240, 230, 480, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);
        jPanel2.add(textField8);
        textField8.setBounds(160, 0, 50, 30);

        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel27.setLayout(null);
        jPanel27.add(textField24);
        textField24.setBounds(20, 0, 210, 30);

        jPanel2.add(jPanel27);
        jPanel27.setBounds(490, 50, 230, 30);

        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel28.setLayout(null);
        jPanel28.add(textField25);
        textField25.setBounds(20, 0, 210, 30);

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel29.setLayout(null);
        jPanel29.add(textField26);
        textField26.setBounds(20, 0, 210, 30);

        jPanel28.add(jPanel29);
        jPanel29.setBounds(490, 50, 230, 30);

        jPanel2.add(jPanel28);
        jPanel28.setBounds(490, 50, 230, 30);

        add(jPanel2);
        jPanel2.setBounds(490, 200, 230, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        label19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label19.setText("I. PENGENALAN TEMPAT");
        jPanel3.add(label19);
        label19.setBounds(0, 0, 729, 30);

        label20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label20.setText("  *) kolom isian akan mengikuti kode yang diinput");
        jPanel3.add(label20);
        label20.setBounds(0, 290, 730, 30);

        label21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label21.setText(" Alamat (nama jalan/gang), RT/RW/Dusun");
        jPanel3.add(label21);
        label21.setBounds(30, 240, 210, 50);

        label22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label22.setText("1");
        jPanel3.add(label22);
        label22.setBounds(0, 60, 30, 30);

        label23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label23.setText("1");
        jPanel3.add(label23);
        label23.setBounds(0, 90, 30, 30);

        label24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label24.setText("1");
        jPanel3.add(label24);
        label24.setBounds(0, 120, 30, 30);

        label25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label25.setText("1");
        jPanel3.add(label25);
        label25.setBounds(0, 150, 30, 30);

        label26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label26.setText("1");
        jPanel3.add(label26);
        label26.setBounds(0, 180, 30, 30);

        label27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label27.setText("1");
        jPanel3.add(label27);
        label27.setBounds(0, 210, 30, 30);

        label28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label28.setText("1");
        jPanel3.add(label28);
        label28.setBounds(0, 240, 30, 50);

        label29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label29.setText("1");
        jPanel3.add(label29);
        label29.setBounds(0, 30, 30, 30);

        label30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label30.setText(" Kabupaten");
        jPanel3.add(label30);
        label30.setBounds(30, 30, 210, 30);

        label31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label31.setText(" Kecamatan");
        jPanel3.add(label31);
        label31.setBounds(30, 60, 210, 30);

        label32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label32.setText(" Desa/Kelurahan");
        jPanel3.add(label32);
        label32.setBounds(30, 90, 210, 30);

        label33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label33.setText(" Nomor Blok Sensus");
        jPanel3.add(label33);
        label33.setBounds(30, 120, 210, 30);

        label34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label34.setText(" Nomor Urut Sampel Blok Sensus");
        jPanel3.add(label34);
        label34.setBounds(30, 150, 210, 30);

        label35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label35.setText(" Nomor Urut Sampel Rumah Tangga");
        jPanel3.add(label35);
        label35.setBounds(30, 180, 210, 30);

        label36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label36.setText(" Nama Kepala Rumah Tangga");
        jPanel3.add(label36);
        label36.setBounds(30, 210, 210, 30);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(240, 30, 250, 30);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(490, 30, 230, 30);

        add(jPanel3);
        jPanel3.setBounds(-1, -1, 0, 0);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);
        jPanel6.add(textField1);
        textField1.setBounds(20, 0, 210, 30);

        add(jPanel6);
        jPanel6.setBounds(240, 80, 0, 30);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);
        jPanel7.add(textField2);
        textField2.setBounds(19, 0, 210, 30);

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setLayout(null);
        jPanel20.add(textField17);
        textField17.setBounds(19, 0, 210, 30);

        jPanel7.add(jPanel20);
        jPanel20.setBounds(240, 50, 250, 30);

        add(jPanel7);
        jPanel7.setBounds(240, 200, 250, 30);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(null);
        jPanel8.add(textField4);
        textField4.setBounds(20, 0, 210, 30);

        add(jPanel8);
        jPanel8.setBounds(240, 140, 0, 30);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(null);
        jPanel9.add(textField3);
        textField3.setBounds(20, 0, 210, 30);

        add(jPanel9);
        jPanel9.setBounds(240, 110, 250, 30);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(null);
        jPanel10.add(textField6);
        textField6.setBounds(20, 0, 210, 30);

        add(jPanel10);
        jPanel10.setBounds(240, 200, 0, 30);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(null);
        jPanel11.add(textField7);
        textField7.setBounds(20, 0, 210, 30);

        add(jPanel11);
        jPanel11.setBounds(240, 230, 0, 30);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(null);
        jPanel12.add(textField9);
        textField9.setBounds(20, 0, 210, 30);

        add(jPanel12);
        jPanel12.setBounds(490, 80, 0, 30);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(null);
        jPanel13.add(textField10);
        textField10.setBounds(20, 0, 210, 30);

        add(jPanel13);
        jPanel13.setBounds(490, 110, 0, 30);

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setLayout(null);
        jPanel14.add(textField11);
        textField11.setBounds(20, 0, 210, 30);

        add(jPanel14);
        jPanel14.setBounds(490, 140, 0, 30);

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.setLayout(null);
        jPanel15.add(textField12);
        textField12.setBounds(20, 0, 210, 30);

        add(jPanel15);
        jPanel15.setBounds(490, 170, 0, 30);

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.setLayout(null);
        jPanel16.add(textField13);
        textField13.setBounds(20, 0, 210, 30);

        add(jPanel16);
        jPanel16.setBounds(490, 200, 0, 30);

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.setLayout(null);
        jPanel17.add(textField14);
        textField14.setBounds(20, 0, 210, 30);

        add(jPanel17);
        jPanel17.setBounds(490, 230, 0, 0);

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setLayout(null);
        jPanel18.add(textField16);
        textField16.setBounds(20, 0, 440, 50);

        add(jPanel18);
        jPanel18.setBounds(240, 260, 480, 50);

        label1.setBackground(new java.awt.Color(0, 102, 204));
        label1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("I. PENGENALAN TEMPAT");
        label1.setOpaque(true);
        add(label1);
        label1.setBounds(0, 0, 720, 50);

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.setLayout(null);
        jPanel19.add(textField15);
        textField15.setBounds(20, 0, 210, 30);

        add(jPanel19);
        jPanel19.setBounds(240, 170, 250, 30);

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel21.setLayout(null);
        jPanel21.add(textField18);
        textField18.setBounds(19, 0, 210, 30);

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel22.setLayout(null);
        jPanel22.add(textField19);
        textField19.setBounds(19, 0, 210, 30);

        jPanel21.add(jPanel22);
        jPanel22.setBounds(240, 50, 250, 30);

        add(jPanel21);
        jPanel21.setBounds(240, 50, 250, 30);

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel23.setLayout(null);
        jPanel23.add(textField20);
        textField20.setBounds(19, 0, 210, 30);

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel24.setLayout(null);
        jPanel24.add(textField21);
        textField21.setBounds(19, 0, 210, 30);

        jPanel23.add(jPanel24);
        jPanel24.setBounds(240, 50, 250, 30);

        add(jPanel23);
        jPanel23.setBounds(240, 80, 250, 30);

        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel25.setLayout(null);
        jPanel25.add(textField22);
        textField22.setBounds(19, 0, 210, 30);

        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel26.setLayout(null);
        jPanel26.add(textField23);
        textField23.setBounds(19, 0, 210, 30);

        jPanel25.add(jPanel26);
        jPanel26.setBounds(240, 50, 250, 30);

        add(jPanel25);
        jPanel25.setBounds(240, 140, 250, 30);

        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.setLayout(null);
        jPanel30.add(textField27);
        textField27.setBounds(160, 0, 50, 30);

        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel31.setLayout(null);
        jPanel31.add(textField28);
        textField28.setBounds(20, 0, 210, 30);

        jPanel30.add(jPanel31);
        jPanel31.setBounds(490, 50, 230, 30);

        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel32.setLayout(null);
        jPanel32.add(textField29);
        textField29.setBounds(20, 0, 210, 30);

        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel33.setLayout(null);
        jPanel33.add(textField30);
        textField30.setBounds(20, 0, 210, 30);

        jPanel32.add(jPanel33);
        jPanel33.setBounds(490, 50, 230, 30);

        jPanel30.add(jPanel32);
        jPanel32.setBounds(490, 50, 230, 30);

        add(jPanel30);
        jPanel30.setBounds(490, 50, 230, 30);

        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel34.setLayout(null);
        jPanel34.add(textField31);
        textField31.setBounds(130, 0, 80, 30);

        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel35.setLayout(null);
        jPanel35.add(textField32);
        textField32.setBounds(20, 0, 210, 30);

        jPanel34.add(jPanel35);
        jPanel35.setBounds(490, 50, 230, 30);

        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel36.setLayout(null);
        jPanel36.add(textField33);
        textField33.setBounds(20, 0, 210, 30);

        jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel37.setLayout(null);
        jPanel37.add(textField34);
        textField34.setBounds(20, 0, 210, 30);

        jPanel36.add(jPanel37);
        jPanel37.setBounds(490, 50, 230, 30);

        jPanel34.add(jPanel36);
        jPanel36.setBounds(490, 50, 230, 30);

        add(jPanel34);
        jPanel34.setBounds(490, 80, 230, 30);

        jPanel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel38.setLayout(null);
        jPanel38.add(textField35);
        textField35.setBounds(130, 0, 80, 30);

        jPanel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel39.setLayout(null);
        jPanel39.add(textField36);
        textField36.setBounds(20, 0, 210, 30);

        jPanel38.add(jPanel39);
        jPanel39.setBounds(490, 50, 230, 30);

        jPanel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel40.setLayout(null);
        jPanel40.add(textField37);
        textField37.setBounds(20, 0, 210, 30);

        jPanel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel41.setLayout(null);
        jPanel41.add(textField38);
        textField38.setBounds(20, 0, 210, 30);

        jPanel40.add(jPanel41);
        jPanel41.setBounds(490, 50, 230, 30);

        jPanel38.add(jPanel40);
        jPanel40.setBounds(490, 50, 230, 30);

        add(jPanel38);
        jPanel38.setBounds(490, 110, 230, 30);

        jPanel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel42.setLayout(null);
        jPanel42.add(textField39);
        textField39.setBounds(60, 0, 150, 30);

        jPanel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel43.setLayout(null);
        jPanel43.add(textField40);
        textField40.setBounds(20, 0, 210, 30);

        jPanel42.add(jPanel43);
        jPanel43.setBounds(490, 50, 230, 30);

        jPanel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel44.setLayout(null);
        jPanel44.add(textField41);
        textField41.setBounds(20, 0, 210, 30);

        jPanel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel45.setLayout(null);
        jPanel45.add(textField42);
        textField42.setBounds(20, 0, 210, 30);

        jPanel44.add(jPanel45);
        jPanel45.setBounds(490, 50, 230, 30);

        jPanel42.add(jPanel44);
        jPanel44.setBounds(490, 50, 230, 30);

        add(jPanel42);
        jPanel42.setBounds(490, 140, 230, 30);

        jPanel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel46.setLayout(null);
        jPanel46.add(textField43);
        textField43.setBounds(110, 0, 100, 30);

        jPanel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel47.setLayout(null);
        jPanel47.add(textField44);
        textField44.setBounds(20, 0, 210, 30);

        jPanel46.add(jPanel47);
        jPanel47.setBounds(490, 50, 230, 30);

        jPanel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel48.setLayout(null);
        jPanel48.add(textField45);
        textField45.setBounds(20, 0, 210, 30);

        jPanel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel49.setLayout(null);
        jPanel49.add(textField46);
        textField46.setBounds(20, 0, 210, 30);

        jPanel48.add(jPanel49);
        jPanel49.setBounds(490, 50, 230, 30);

        jPanel46.add(jPanel48);
        jPanel48.setBounds(490, 50, 230, 30);

        add(jPanel46);
        jPanel46.setBounds(490, 170, 230, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private pkl51.component.Label label1;
    private pkl51.component.Label label10;
    private pkl51.component.Label label11;
    private pkl51.component.Label label12;
    private pkl51.component.Label label13;
    private pkl51.component.Label label14;
    private pkl51.component.Label label15;
    private pkl51.component.Label label16;
    private pkl51.component.Label label17;
    private pkl51.component.Label label18;
    private pkl51.component.Label label19;
    private pkl51.component.Label label2;
    private pkl51.component.Label label20;
    private pkl51.component.Label label21;
    private pkl51.component.Label label22;
    private pkl51.component.Label label23;
    private pkl51.component.Label label24;
    private pkl51.component.Label label25;
    private pkl51.component.Label label26;
    private pkl51.component.Label label27;
    private pkl51.component.Label label28;
    private pkl51.component.Label label29;
    private pkl51.component.Label label3;
    private pkl51.component.Label label30;
    private pkl51.component.Label label31;
    private pkl51.component.Label label32;
    private pkl51.component.Label label33;
    private pkl51.component.Label label34;
    private pkl51.component.Label label35;
    private pkl51.component.Label label36;
    private pkl51.component.Label label4;
    private pkl51.component.Label label5;
    private pkl51.component.Label label6;
    private pkl51.component.Label label7;
    private pkl51.component.Label label8;
    private pkl51.component.Label label9;
    private pkl51.component.TextField textField1;
    private pkl51.component.TextField textField10;
    private pkl51.component.TextField textField11;
    private pkl51.component.TextField textField12;
    private pkl51.component.TextField textField13;
    private pkl51.component.TextField textField14;
    private pkl51.component.TextField textField15;
    private pkl51.component.TextField textField16;
    private pkl51.component.TextField textField17;
    private pkl51.component.TextField textField18;
    private pkl51.component.TextField textField19;
    private pkl51.component.TextField textField2;
    private pkl51.component.TextField textField20;
    private pkl51.component.TextField textField21;
    private pkl51.component.TextField textField22;
    private pkl51.component.TextField textField23;
    private pkl51.component.TextField textField24;
    private pkl51.component.TextField textField25;
    private pkl51.component.TextField textField26;
    private pkl51.component.TextField textField27;
    private pkl51.component.TextField textField28;
    private pkl51.component.TextField textField29;
    private pkl51.component.TextField textField3;
    private pkl51.component.TextField textField30;
    private pkl51.component.TextField textField31;
    private pkl51.component.TextField textField32;
    private pkl51.component.TextField textField33;
    private pkl51.component.TextField textField34;
    private pkl51.component.TextField textField35;
    private pkl51.component.TextField textField36;
    private pkl51.component.TextField textField37;
    private pkl51.component.TextField textField38;
    private pkl51.component.TextField textField39;
    private pkl51.component.TextField textField4;
    private pkl51.component.TextField textField40;
    private pkl51.component.TextField textField41;
    private pkl51.component.TextField textField42;
    private pkl51.component.TextField textField43;
    private pkl51.component.TextField textField44;
    private pkl51.component.TextField textField45;
    private pkl51.component.TextField textField46;
    private pkl51.component.TextField textField5;
    private pkl51.component.TextField textField6;
    private pkl51.component.TextField textField7;
    private pkl51.component.TextField textField8;
    private pkl51.component.TextField textField9;
    // End of variables declaration//GEN-END:variables

}
