/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelBlok1_2_3.java
 *
 * Created on Feb 7, 2012, 8:54:35 PM
 */

package pkl51.view.kuesioner;

/**
 *
 * @author thiolutfi
 */
public class PanelBlok1_2_3 extends javax.swing.JPanel {

    /** Creates new form PanelBlok1_2_3 */
    public PanelBlok1_2_3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blok1 = new pkl51.view.kuesioner.Blok1();
        blok2_3 = new pkl51.view.kuesioner.Blok2_3();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(785, 809));
        add(blok1);
        add(blok2_3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl51.view.kuesioner.Blok1 blok1;
    private pkl51.view.kuesioner.Blok2_3 blok2_3;
    // End of variables declaration//GEN-END:variables

}
