/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkl53.view.loop;

import pkl53.converter.IntegerConverter;
import pkl53.converter.KetRTConverter;
import pkl53.converter.OpsiB4R3Usahaconverter;
import pkl53.converter.OpsiB4R8Converter;
import pkl53.converter.OpsiB4r7Converter;
import pkl53.converter.OpsiJenisKelaminConverter;
import pkl53.converter.OpsiListingB4R16Converter;
import pkl53.validasi.ListingB4Validasi;

/**
 *
 * @author HP G42 (RILLA)
 */
public class Loop4Listing extends javax.swing.JPanel {

    /**
     * Creates new form loop
     */
    public Loop4Listing() {
        initComponents();
        this.setOpaque(false);
        loopPanel.setOpaque(false);
        B4R19.setName("B4R19");
        ListingB4Validasi val = new ListingB4Validasi();
        val.setKetArt(ketRTTambahan);
        val.setPanelB4Listing(this);
        val.registerValidasi();
        val.setList();
        
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        ketRt = new pkl53.model.KetRt();
        ketRTTambahan = new pkl53.model.tambahan.KetRTTambahan();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        loopPanel = new javax.swing.JPanel();
        B4R2 = new pkl53.component.Textfield();
        B4R1 = new pkl53.component.Textfield();
        B4R4 = new pkl53.component.Textfield();
        B4R3 = new pkl53.component.Textfield();
        B4R7 = new pkl53.component.Textfield();
        B4R8 = new pkl53.component.Textfield();
        B4R6 = new pkl53.component.Textfield();
        B4R5 = new pkl53.component.Textfield();
        B4R13 = new pkl53.component.Textfield();
        B4R15 = new pkl53.component.Textfield();
        B4R14 = new pkl53.component.Textfield();
        B4R12 = new pkl53.component.Textfield();
        B4R11 = new pkl53.component.Textfield();
        B4R10 = new pkl53.component.Textfield();
        B4R9 = new pkl53.component.Textfield();
        B4R18 = new pkl53.component.Textfield();
        B4R17 = new pkl53.component.Textfield();
        B4R16 = new pkl53.component.Textfield();
        B4R24 = new pkl53.component.Textfield();
        B4R19 = new pkl53.component.Textfield();
        B4R25 = new pkl53.component.Textfield();
        B4R31 = new pkl53.component.Textfield();
        B4R30 = new pkl53.component.Textfield();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R1, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("b4r1"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R2, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("b4r2"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R24, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("b4r24"));
        binding.setConverter(new IntegerConverter());
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R25, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("b4r2526"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R3, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("b4r3"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R30, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("b4r30"));
        binding.setConverter(new IntegerConverter());
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R31, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("b4r31"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R4, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("b4r4"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R5, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("b4r5"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R6, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("b4r6"));
        binding.setConverter(new IntegerConverter());
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R9, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRt, org.jdesktop.beansbinding.BeanProperty.create("kksrt"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R1, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r1"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R10, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r10"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R11, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r11"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R12, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r12"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R13, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r13"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R14, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r14"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R15, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r15"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R16, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r16"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R17, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r17"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R18, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r18"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R19, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r19"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R2, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r2"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R24, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r24"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R25, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r25"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R3, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r3"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R30, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r30"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R31, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r31"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R4, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r4"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R5, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r5"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R6, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r6"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R7, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r7"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R8, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r8"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B4R9, org.jdesktop.beansbinding.ELProperty.create("${text}"), ketRTTambahan, org.jdesktop.beansbinding.BeanProperty.create("b4r9"));
        bindingGroup.addBinding(binding);

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loopPanel.setAlignmentX(1.0F);
        loopPanel.setAlignmentY(1.0F);
        loopPanel.setOpaque(false);

        B4R2.setBlok4Listing(true);
        B4R2.setCharType('2');
        B4R2.setLength(20);
        B4R2.setPanel(this);

        B4R1.setBlok4Listing(true);
        B4R1.setCharType('2');
        B4R1.setLength(4);
        B4R1.setPanel(this);
        B4R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4R1ActionPerformed(evt);
            }
        });

        B4R4.setBlok4Listing(true);
        B4R4.setLength(3);
        B4R4.setPanel(this);

        B4R3.setBlok4Listing(true);
        B4R3.setLength(3);
        B4R3.setPanel(this);

        B4R7.setBlok4Listing(true);
        B4R7.setPanel(this);

        B4R8.setBlok4Listing(true);
        B4R8.setCharType('2');
        B4R8.setLength(25);
        B4R8.setPanel(this);

        B4R6.setBlok4Listing(true);
        B4R6.setLength(2);
        B4R6.setPanel(this);
        B4R6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                B4R6FocusGained(evt);
            }
        });
        B4R6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4R6ActionPerformed(evt);
            }
        });

        B4R5.setBlok4Listing(true);
        B4R5.setLength(3);
        B4R5.setPanel(this);

        B4R13.setBlok4Listing(true);
        B4R13.setPanel(this);

        B4R15.setBlok4Listing(true);
        B4R15.setPanel(this);

        B4R14.setBlok4Listing(true);
        B4R14.setPanel(this);

        B4R12.setBlok4Listing(true);
        B4R12.setPanel(this);

        B4R11.setBlok4Listing(true);
        B4R11.setLength(2);
        B4R11.setPanel(this);

        B4R10.setBlok4Listing(true);
        B4R10.setPanel(this);

        B4R9.setBlok4Listing(true);
        B4R9.setPanel(this);

        B4R18.setBlok4Listing(true);
        B4R18.setPanel(this);

        B4R17.setBlok4Listing(true);
        B4R17.setPanel(this);

        B4R16.setBlok4Listing(true);
        B4R16.setPanel(this);

        B4R24.setBlok4Listing(true);
        B4R24.setLength(2);
        B4R24.setPanel(this);

        B4R19.setBlok4Listing(true);
        B4R19.setFieldValidasi(true);
        B4R19.setPanel(this);

        B4R25.setBlok4Listing(true);
        B4R25.setPanel(this);

        B4R31.setBlok4Listing(true);
        B4R31.setPanel(this);

        B4R30.setBlok4Listing(true);
        B4R30.setLength(2);
        B4R30.setPanel(this);

        javax.swing.GroupLayout loopPanelLayout = new javax.swing.GroupLayout(loopPanel);
        loopPanel.setLayout(loopPanelLayout);
        loopPanelLayout.setHorizontalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loopPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(B4R1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(B4R2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(B4R3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(B4R4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(B4R5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(B4R6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(B4R7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B4R8, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(B4R9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(B4R10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(B4R11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(B4R12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(B4R13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(B4R14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(B4R15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(B4R16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(B4R17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(B4R18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(B4R19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(B4R24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(B4R25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(B4R30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(B4R31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        loopPanelLayout.setVerticalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loopPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B4R1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4R30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jLayeredPane2.add(loopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2100, -1));

        add(jLayeredPane2, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void B4R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4R1ActionPerformed

    private void B4R6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4R6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4R6ActionPerformed

    private void B4R6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_B4R6FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_B4R6FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl53.component.Textfield B4R1;
    private pkl53.component.Textfield B4R10;
    private pkl53.component.Textfield B4R11;
    private pkl53.component.Textfield B4R12;
    private pkl53.component.Textfield B4R13;
    private pkl53.component.Textfield B4R14;
    private pkl53.component.Textfield B4R15;
    private pkl53.component.Textfield B4R16;
    private pkl53.component.Textfield B4R17;
    private pkl53.component.Textfield B4R18;
    private pkl53.component.Textfield B4R19;
    private pkl53.component.Textfield B4R2;
    private pkl53.component.Textfield B4R24;
    private pkl53.component.Textfield B4R25;
    private pkl53.component.Textfield B4R3;
    private pkl53.component.Textfield B4R30;
    private pkl53.component.Textfield B4R31;
    private pkl53.component.Textfield B4R4;
    private pkl53.component.Textfield B4R5;
    private pkl53.component.Textfield B4R6;
    private pkl53.component.Textfield B4R7;
    private pkl53.component.Textfield B4R8;
    private pkl53.component.Textfield B4R9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private pkl53.model.tambahan.KetRTTambahan ketRTTambahan;
    private pkl53.model.KetRt ketRt;
    private javax.swing.JPanel loopPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the loopPanel
     */
    public javax.swing.JPanel getLoopPanel() {
        return loopPanel;
    }

    /**
     * @param loopPanel the loopPanel to set
     */
    public void setLoopPanel(javax.swing.JPanel loopPanel) {
        this.loopPanel = loopPanel;
    }

    /**
     * @return the B4R1
     */
    public pkl53.component.Textfield getB4R1() {
        return B4R1;
    }

    /**
     * @param B4R1 the B4R1 to set
     */
    public void setB4R1(pkl53.component.Textfield B4R1) {
        this.B4R1 = B4R1;
    }

    /**
     * @return the B4R10
     */
    public pkl53.component.Textfield getB4R10() {
        return B4R10;
    }

    /**
     * @param B4R10 the B4R10 to set
     */
    public void setB4R10(pkl53.component.Textfield B4R10) {
        this.B4R10 = B4R10;
    }

    /**
     * @return the B4R11
     */
    public pkl53.component.Textfield getB4R11() {
        return B4R11;
    }

    /**
     * @param B4R11 the B4R11 to set
     */
    public void setB4R11(pkl53.component.Textfield B4R11) {
        this.B4R11 = B4R11;
    }

    /**
     * @return the B4R12
     */
    public pkl53.component.Textfield getB4R12() {
        return B4R12;
    }

    /**
     * @param B4R12 the B4R12 to set
     */
    public void setB4R12(pkl53.component.Textfield B4R12) {
        this.B4R12 = B4R12;
    }

    /**
     * @return the B4R13
     */
    public pkl53.component.Textfield getB4R13() {
        return B4R13;
    }

    /**
     * @param B4R13 the B4R13 to set
     */
    public void setB4R13(pkl53.component.Textfield B4R13) {
        this.B4R13 = B4R13;
    }

    /**
     * @return the B4R14
     */
    public pkl53.component.Textfield getB4R14() {
        return B4R14;
    }

    /**
     * @param B4R14 the B4R14 to set
     */
    public void setB4R14(pkl53.component.Textfield B4R14) {
        this.B4R14 = B4R14;
    }
     
    public pkl53.component.Textfield getB4R15() {
        return B4R15;
    }

    /**
     * @paB4R244R15 the B4R15 to set
     */
    public void setB4R15(pkl53.component.Textfield B4R15) {
        this.B4R15 = B4R15;
    }

   
    /**
     * @return the B4R17
     */
    public pkl53.component.Textfield getB4R17() {
        return B4R17;
    }

    /**
     * @param B4R17 the B4R17 to set
     */
    public void setB4R17(pkl53.component.Textfield B4R17) {
        this.setB4R16(B4R17);
    }

    /**
     * @return the B4R18
     */
    public pkl53.component.Textfield getB4R18() {
        return B4R18;
    }

    /**
     * @param B4R18 the B4R18 to set
     */
    public void setB4R18(pkl53.component.Textfield B4R18) {
        this.B4R17 = B4R18;
    }

    /**
     * @return the B4R19
     */
    public pkl53.component.Textfield getB4R19() {
        return B4R19;
    }

    /**
     * @param B4R19 the B4R19 to set
     */
    public void setB4R19(pkl53.component.Textfield B4R19) {
        this.B4R18 = B4R19;
    }

    /**
     * @return the B4R2
     */
    public pkl53.component.Textfield getB4R2() {
        return B4R2;
    }

    /**
     * @param B4R2 the B4R2 to set
     */
    public void setB4R2(pkl53.component.Textfield B4R2) {
        this.B4R2 = B4R2;
    }

   

    /**
     * @return the B4R3
     */
    public pkl53.component.Textfield getB4R3() {
        return B4R3;
    }

    /**
     * @param B4R3 the B4R3 to set
     */
    public void setB4R3(pkl53.component.Textfield B4R3) {
        this.B4R3 = B4R3;
    }

    /**
     * @return the B4R4
     */
    public pkl53.component.Textfield getB4R4() {
        return B4R4;
    }

    /**
     * @param B4R4 the B4R4 to set
     */
    public void setB4R4(pkl53.component.Textfield B4R4) {
        this.B4R4 = B4R4;
    }

    /**
     * @return the B4R5
     */
    public pkl53.component.Textfield getB4R5() {
        return B4R5;
    }

    /**
     * @param B4R5 the B4R5 to set
     */
    public void setB4R5(pkl53.component.Textfield B4R5) {
        this.B4R5 = B4R5;
    }

    /**
     * @return the B4R6
     */
    public pkl53.component.Textfield getB4R6() {
        return B4R6;
    }

    /**
     * @param B4R6 the B4R6 to set
     */
    public void setB4R6(pkl53.component.Textfield B4R6) {
        this.B4R6 = B4R6;
    }

    /**
     * @return the B4R7
     */
    public pkl53.component.Textfield getB4R7() {
        return B4R7;
    }

    /**
     * @param B4R7 the B4R7 to set
     */
    public void setB4R7(pkl53.component.Textfield B4R7) {
        this.B4R7 = B4R7;
    }
    public  void setB4R7(String B4R9) {
        B4R7.setText(B4R9);
    }

    /**
     * @return the B4R8
     */
    public pkl53.component.Textfield getB4R8() {
        return B4R8;
    }

    /**
     * @param B4R8 the B4R8 to set
     */
    public void setB4R8(pkl53.component.Textfield B4R8) {
        this.B4R8 = B4R8;
    }

    /**
     * @return the B4R9
     */
    public pkl53.component.Textfield getB4R9() {
        return B4R9;
    }

    /**
     * @param B4R9 the B4R9 to set
     */
    public void setB4R9(pkl53.component.Textfield B4R9) {
        this.B4R9 = B4R9;
    }

  
    

   

    /**
     * @return the B4R16
     */
    public pkl53.component.Textfield getB4R16() {
        return B4R16;
    }

    /**
     * @param B4R16 the B4R16 to set
     */
    public void setB4R16(pkl53.component.Textfield B4R16) {
        this.B4R16 = B4R16;
    }

    /**
     * @return the B4R25
     */
    public pkl53.component.Textfield getB4R25() {
        return B4R25;
    }

    /**
     * @param B4R25 the B4R25 to set
     */
    public void setB4R25(pkl53.component.Textfield B4R25) {
        this.B4R25 = B4R25;
    }

   

   

    /**
     * @return the B4R30
     */
    public pkl53.component.Textfield getB4R30() {
        return B4R30;
    }

    /**
     * @param B4R30 the B4R30 to set
     */
    public void setB4R30(pkl53.component.Textfield B4R30) {
        this.B4R30 = B4R30;
    }

    /**
     * @return the B4R31
     */
    public pkl53.component.Textfield getB4R31() {
        return B4R31;
    }

    /**
     * @param B4R31 the B4R31 to set
     */
    public void setB4R31(pkl53.component.Textfield B4R31) {
        this.B4R31 = B4R31;
    }
    public void setB4R31(String B4R31) {
        this.B4R31.setText(B4R31);
    }

    /**
     * @return the ketRt
     */
    public pkl53.model.KetRt getKetRt() {
        return ketRt;
    }

    /**
     * @param ketRt the ketRt to set
     */
    public void setKetRt(pkl53.model.KetRt ketRt) {
        this.ketRt = ketRt;
    }

    /**
     * @return the ketRTTambahan
     */
    public pkl53.model.tambahan.KetRTTambahan getKetRTTambahan() {
        return ketRTTambahan;
    }

    /**
     * @param ketRTTambahan the ketRTTambahan to set
     */
    public void setKetRTTambahan(pkl53.model.tambahan.KetRTTambahan ketRTTambahan) {
        this.ketRTTambahan = ketRTTambahan;
    }

    /**
     * @return the B4R24
     */
    public pkl53.component.Textfield getB4R24() {
        return B4R24;
    }

    /**
     * @param B4R24 the B4R24 to set
     */
    public void setB4R24(pkl53.component.Textfield B4R24) {
        this.B4R24 = B4R24;
    }


   


   
    
}
