/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl53.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import pkl53.controller.SubmitControllerPekerjaan;
import pkl53.converter.IntegerConverter;
import pkl53.model.B1Keterangantempat;
import pkl53.model.B4Art;
import pkl53.model.B4Keteranganumumtenagakerja;
import pkl53.model.Blok4PekerjaBinding;
import pkl53.model.KetKuesioner;
import pkl53.model.KetRtanggota;
import pkl53.view.loop.Loop4A;

/**
 *
 * @author Ema Yulandika SP
 */
public class Blok4 extends javax.swing.JPanel {

    Loop4A loop;
    private static String kks;
    private static List<Blok4PekerjaBinding> b4PekerjaanBindingList = new ArrayList<Blok4PekerjaBinding>();
    SubmitControllerPekerjaan submit = new SubmitControllerPekerjaan();
    IntegerConverter ic = new IntegerConverter();

    /**
     * Creates new form Blok4
     */
    public Blok4() {
//        scrollPane1.getViewport().setBackground( new Color(1.0f, 1.0f, 1.0f, 0.6f));

//        scrollPane1.getViewport().setBackground( new Color(1.0f, 1.0f, 1.0f, 0.6f));
        initComponents();

        GridLayout grid = new GridLayout(20, 1, 0, 0);
        loopPanel.setLayout(grid);

    }
    public static void getfocus(){
        Component[] comp = loopPanel.getComponents();
        Loop4A loop = (Loop4A) comp[0];
        loop.getB4R1().requestFocusInWindow();
                
    
    
    
    
    }

    public void setLOOP() {

        List<KetRtanggota> allketRtAnggotaList = new ArrayList<KetRtanggota>();
        allketRtAnggotaList = submit.getAllketRtAnggota(Blok123.getB1R6().getText(), new KetKuesioner(Blok123.getKKS()));
        if (allketRtAnggotaList.size() > 0) {
            int i = 1;
            for (KetRtanggota ag : allketRtAnggotaList) {
          
                for (int j = 0; j < ic.convertForward(ag.getB4r17()); j++) {
                    
                    loop = new Loop4A();
                    loopPanel.add(loop);
                    loop.getB4R1().setText(String.valueOf(i));
                    loop.getB4R2().setText(ag.getB4r8());
               
                    loop.getB4R3().setText((ag.getB4r9().getB4r3()));
                    loop.getB4R4().setText(String.valueOf(j + 1));
                    b4PekerjaanBindingList.add(loop.getBlok4ABinding());
                    loopPanel.updateUI();
                    

                }
                i++;
            }

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blokPekerja41 = new pkl53.imageClass.BlokPekerja4();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        tambahArtButton = new javax.swing.JButton();
        hapusArtButton = new javax.swing.JButton();
        loopPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(2100, 1275));

        blokPekerja41.setBackground(new java.awt.Color(255, 255, 255));
        blokPekerja41.setPreferredSize(new java.awt.Dimension(2100, 1275));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(2100, 1275));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tambahArtButton.setText("Tambah Baris");
        tambahArtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahArtButtonActionPerformed(evt);
            }
        });

        hapusArtButton.setText("Hapus Baris");
        hapusArtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusArtButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1729, Short.MAX_VALUE)
                .addComponent(tambahArtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusArtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahArtButton)
                    .addComponent(hapusArtButton))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 1993, 30));

        loopPanel.setOpaque(false);

        javax.swing.GroupLayout loopPanelLayout = new javax.swing.GroupLayout(loopPanel);
        loopPanel.setLayout(loopPanelLayout);
        loopPanelLayout.setHorizontalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1993, Short.MAX_VALUE)
        );
        loopPanelLayout.setVerticalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jLayeredPane1.add(loopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 420, 1993, 690));

        javax.swing.GroupLayout blokPekerja41Layout = new javax.swing.GroupLayout(blokPekerja41);
        blokPekerja41.setLayout(blokPekerja41Layout);
        blokPekerja41Layout.setHorizontalGroup(
            blokPekerja41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blokPekerja41Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        blokPekerja41Layout.setVerticalGroup(
            blokPekerja41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blokPekerja41Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blokPekerja41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blokPekerja41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tambahArtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahArtButtonActionPerformed
        // TODO add your handling code here:
        loop = new Loop4A();
        getLoopPanel().add(loop);
        b4PekerjaanBindingList.add(loop.getBlok4ABinding());
        getLoopPanel().updateUI();


    }//GEN-LAST:event_tambahArtButtonActionPerformed

    private void hapusArtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusArtButtonActionPerformed
        int i = getLoopPanel().getComponentCount();
        getLoopPanel().remove(i-1);
        b4PekerjaanBindingList.remove(i-1);
        getLoopPanel().updateUI();
        System.out.println("i-->"+i);
    }//GEN-LAST:event_hapusArtButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl53.imageClass.BlokPekerja4 blokPekerja41;
    private javax.swing.JButton hapusArtButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel loopPanel;
    private javax.swing.JButton tambahArtButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the kks
     */
    public String getKks() {
        return kks;
    }

    /**
     * @param kks the kks to set
     */
    public static void setKks(String kkss) {
        kks = kkss;
    }

    /**
     * @return the b4PekerjaanBindingList
     */
    public static List<Blok4PekerjaBinding> getB4PekerjaanBindingList() {
        return b4PekerjaanBindingList;
    }

    /**
     * @param b4PekerjaanBindingList the b4PekerjaanBindingList to set
     */
    public void setB4PekerjaanBindingList(List<Blok4PekerjaBinding> b4PekerjaanBindingLists) {
        b4PekerjaanBindingList = b4PekerjaanBindingLists;
    }

    /**
     * @return the loopPanel
     */
    public static javax.swing.JPanel getLoopPanel() {
        return loopPanel;
    }

    /**
     * @param loopPanel the loopPanel to set
     */
    public void setLoopPanel(javax.swing.JPanel loopPanel) {
        this.loopPanel = loopPanel;
    }

    public void clearBlok4() {
        getLoopPanel().removeAll();
        b4PekerjaanBindingList.clear();
        getLoopPanel().updateUI();
    }
}
