/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkl53.view;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import pkl53.controller.SubmitControllerPekerjaan;
import pkl53.converter.IntegerConverter;
import pkl53.model.B4Art;
import pkl53.model.B4Keteranganumumtenagakerja;
import pkl53.model.Blok4PekerjaBinding;
import pkl53.model.KetKuesioner;
import pkl53.model.KetRtanggota;
import static pkl53.view.Blok4.getLoopPanel;
import pkl53.view.loop.Loop4A;
import pkl53.view.loop.Loop4B;

/**
 *
 * @author User
 */
public class Blok4B extends javax.swing.JPanel {

    /**
     * @return the b4PekerjaBinding
     */
    public static List <Blok4PekerjaBinding> getB4PekerjaBinding() {
        return b4PekerjaBinding;
    }

    /**
     * @param aB4PekerjaBinding the b4PekerjaBinding to set
     */
    public static void setB4PekerjaBinding(List <Blok4PekerjaBinding> aB4PekerjaBinding) {
        b4PekerjaBinding = aB4PekerjaBinding;
    }

    /**
     * @return the loopPanel
     */
    public static javax.swing.JPanel getLoopPanel() {
        return loopPanel;
    }
    Loop4B loop;
    private  static List <Blok4PekerjaBinding> b4PekerjaBinding= new ArrayList<Blok4PekerjaBinding>();
    private List <B4Art> b4ArtList= new ArrayList<B4Art>();
    SubmitControllerPekerjaan submit = new  SubmitControllerPekerjaan();
    IntegerConverter ic = new IntegerConverter();
    /**
     * Creates new form blok4
     */
    public Blok4B() {
        
        initComponents();
        
        GridLayout grid = new GridLayout(12,1,0,0);
        loopPanel.setLayout(grid);
//        loop.getB4R1().requestFocusInWindow();
//        loop.getB4R1().setBounds(loop.getB4R1().getBounds().x-25,loop.getB4R1().getBounds().y,loop.getB4R1().getBounds().width,loop.getB4R1().getBounds().height);
//        loop.getB4R1().getPanel().scrollRectToVisible(loop.getB4R1().getBounds());
       
        
    }
public void setLOOP() {

        List<KetRtanggota> allketRtAnggotaList = new ArrayList<KetRtanggota>();
        allketRtAnggotaList = submit.getAllketRtAnggota(Blok123.getB1R6().getText(), new KetKuesioner(Blok123.getKKS()));
        if (allketRtAnggotaList.size() > 0) {
            int i = 1;
            for (KetRtanggota ag : allketRtAnggotaList) {
          
                for (int j = 0; j < ic.convertForward(ag.getB4r17()); j++) {
                    
                    loop = new Loop4B();
                    getLoopPanel().add(loop);
                    loop.getB4R1().setText(String.valueOf(i));
                    loop.getB4R2().setText(ag.getB4r8());
               
                    loop.getB4R4().setText(String.valueOf(j + 1));
                    b4PekerjaBinding.add(loop.getBlok4BBinding());
                    getLoopPanel().updateUI();

                }
                i++;
            }

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blok4B1 = new pkl53.imageClass.BlokPekerja4B();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        tambahArtButton = new javax.swing.JButton();
        hapusArtButton = new javax.swing.JButton();
        loopPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        blok4B1.setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tambahArtButton.setText("Tambah Baris");
        tambahArtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahArtButtonActionPerformed(evt);
            }
        });

        hapusArtButton.setText("Hapus Baris");
        hapusArtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusArtButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1478, Short.MAX_VALUE)
                .addComponent(tambahArtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(hapusArtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahArtButton)
                    .addComponent(hapusArtButton))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 402, 1762, 30));

        loopPanel.setOpaque(false);

        javax.swing.GroupLayout loopPanelLayout = new javax.swing.GroupLayout(loopPanel);
        loopPanel.setLayout(loopPanelLayout);
        loopPanelLayout.setHorizontalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1762, Short.MAX_VALUE)
        );
        loopPanelLayout.setVerticalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jLayeredPane1.add(loopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 432, 1762, 660));

        javax.swing.GroupLayout blok4B1Layout = new javax.swing.GroupLayout(blok4B1);
        blok4B1.setLayout(blok4B1Layout);
        blok4B1Layout.setHorizontalGroup(
            blok4B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blok4B1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        blok4B1Layout.setVerticalGroup(
            blok4B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blok4B1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        add(blok4B1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tambahArtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahArtButtonActionPerformed
        // TODO add your handling code here:
        loop = new Loop4B();
        getLoopPanel().add(loop);
        getB4PekerjaBinding().add(loop.getBlok4BBinding());
         
       
//        loop.getB4R1().requestFocusInWindow();
//        loop.getB4R1().setBounds(loop.getB4R1().getBounds().x-25,loop.getB4R1().getBounds().y,loop.getB4R1().getBounds().width,loop.getB4R1().getBounds().height);
//        loop.getB4R1().getPanel().scrollRectToVisible(loop.getB4R1().getBounds());

//        

    }//GEN-LAST:event_tambahArtButtonActionPerformed

    private void hapusArtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusArtButtonActionPerformed
        int i = getLoopPanel().getComponentCount();
        getLoopPanel().remove(i-1);
        getB4PekerjaBinding().remove(i-1);
        getLoopPanel().updateUI();
        System.out.println("i-->"+i);
    }//GEN-LAST:event_hapusArtButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl53.imageClass.BlokPekerja4B blok4B1;
    private javax.swing.JButton hapusArtButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel loopPanel;
    private javax.swing.JButton tambahArtButton;
    // End of variables declaration//GEN-END:variables

  
    /**
     * @return the b4ArtList
     */
    public List <B4Art> getB4ArtList() {
        return b4ArtList;
    }

    /**
     * @param b4ArtList the b4ArtList to set
     */
    public void setB4ArtList(List <B4Art> b4ArtList) {
        this.b4ArtList = b4ArtList;
    }

    public void clearBlok4B() {
        loopPanel.removeAll();
        b4PekerjaBinding.clear();
        loopPanel.updateUI();
    }
}
