/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl53.view;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import pkl53.component.Textfield;
import pkl53.controller.SubmitControllerPekerjaan;
import pkl53.converter.IntegerConverter;
import pkl53.model.KetKuesioner;
import pkl53.model.KetRtanggota;
import pkl53.model.tambahan.B2Tambahan;
import pkl53.view.loop.Loop4Usaha;

/**
 *
 * @author Ema Yuland SP
 */
public class BlokUsaha4 extends javax.swing.JPanel {
    private String kks;
    private static ArrayList<B2Tambahan> b2TambahanList = new ArrayList<B2Tambahan>();
    private Loop4Usaha loop;
    private SubmitControllerPekerjaan submit = new SubmitControllerPekerjaan();
    private IntegerConverter ic = new IntegerConverter();
    private BlokUsaha123 blokUsaha123;

    /**
     * Creates new form blok123
     */
    public BlokUsaha4() {
        initComponents();
        GridLayout grid = new GridLayout(15, 1, 0, 0);
        loopPanel.setLayout(grid);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blok4Usaha = new pkl53.imageClass.BlokUsaha4();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        loopPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tambahArtButton = new javax.swing.JButton();
        hapusArtButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        blok4Usaha.setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loopPanel.setOpaque(false);

        javax.swing.GroupLayout loopPanelLayout = new javax.swing.GroupLayout(loopPanel);
        loopPanel.setLayout(loopPanelLayout);
        loopPanelLayout.setHorizontalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1291, Short.MAX_VALUE)
        );
        loopPanelLayout.setVerticalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        jLayeredPane1.add(loopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 340, 1291, 523));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tambahArtButton.setText("Tambah Baris");
        tambahArtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahArtButtonActionPerformed(evt);
            }
        });

        hapusArtButton.setText("Hapus Baris");
        hapusArtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusArtButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1012, Short.MAX_VALUE)
                .addComponent(tambahArtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapusArtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahArtButton)
                    .addComponent(hapusArtButton))
                .addContainerGap())
        );

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 310, 1290, 30));

        javax.swing.GroupLayout blok4UsahaLayout = new javax.swing.GroupLayout(blok4Usaha);
        blok4Usaha.setLayout(blok4UsahaLayout);
        blok4UsahaLayout.setHorizontalGroup(
            blok4UsahaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blok4UsahaLayout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        blok4UsahaLayout.setVerticalGroup(
            blok4UsahaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1385, Short.MAX_VALUE)
        );

        add(blok4Usaha, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tambahArtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahArtButtonActionPerformed
        // TODO add your handling code here:
        loop = new Loop4Usaha();
        loopPanel.add(loop);
        b2TambahanList.add(loop.getB2Tambahan1());
        System.out.println("B2List "+ b2TambahanList.size());
    }//GEN-LAST:event_tambahArtButtonActionPerformed

    private void hapusArtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusArtButtonActionPerformed
        int i = loopPanel.getComponentCount();
        loopPanel.remove(i-1);
        b2TambahanList.remove(i-1);
        loopPanel.updateUI();
        System.out.println("i-->"+i);
        System.out.println("B2List "+ b2TambahanList.size());
    }//GEN-LAST:event_hapusArtButtonActionPerformed

    public void clearBlok4(){
        getLoopPanel().removeAll();
        getB2TambahanList().clear();
        getLoopPanel().updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl53.imageClass.BlokUsaha4 blok4Usaha;
    private javax.swing.JButton hapusArtButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel loopPanel;
    private javax.swing.JButton tambahArtButton;
    // End of variables declaration//GEN-END:variables


    /**
     * @return the loopPanel
     */
    public static javax.swing.JPanel getLoopPanel() {
        return loopPanel;
    }

    /**
     * @param aLoopPanel the loopPanel to set
     */
    public static void setLoopPanel(javax.swing.JPanel aLoopPanel) {
        loopPanel = aLoopPanel;
    }

    /**
     * @return the kks
     */
    public String getKks() {
        return kks;
    }

    /**
     * @param kks the kks to set
     */
    public void setKks(String kks) {
        this.kks = kks;
    }

    /**
     * @return the loop
     */
    public Loop4Usaha getLoop() {
        return loop;
    }

    /**
     * @param loop the loop to set
     */
    public void setLoop(Loop4Usaha loop) {
        this.loop = loop;
    }

    /**
     * @return the blokUsaha123
     */
    public BlokUsaha123 getBlokUsaha123() {
        return blokUsaha123;
    }

    /**
     * @param blokUsaha123 the blokUsaha123 to set
     */
    public void setBlokUsaha123(BlokUsaha123 blokUsaha123) {
        this.blokUsaha123 = blokUsaha123;
    }

    /**
     * @return the blok4Usaha
     */
    public pkl53.imageClass.BlokUsaha4 getBlok4Usaha() {
        return blok4Usaha;
    }

    /**
     * @param blok4Usaha the blok4Usaha to set
     */
    public void setBlok4Usaha(pkl53.imageClass.BlokUsaha4 blok4Usaha) {
        this.blok4Usaha = blok4Usaha;
    }

    /**
     * @return the b2TambahanList
     */
    public static ArrayList<B2Tambahan> getB2TambahanList() {
        return b2TambahanList;
    }

    /**
     * @param aB2TambahanList the b2TambahanList to set
     */
    public static void setB2TambahanList(ArrayList<B2Tambahan> aB2TambahanList) {
        b2TambahanList = aB2TambahanList;
    }
    
    public void setLoop(){
        List<KetRtanggota> allketRtAnggotaList = new ArrayList<KetRtanggota>();
        allketRtAnggotaList = submit.getAllketRtAnggota(BlokUsaha123.getB1R6().getText(), new KetKuesioner(BlokUsaha123.getKKS()));
        if (allketRtAnggotaList.size() > 0) {
            int i = 1;
            for (KetRtanggota ag : allketRtAnggotaList) {
                for (int j = 0; j < ic.convertForward(ag.getB4r17()); j++) {
                    
                    loop = new Loop4Usaha();
                    loopPanel.add(loop);
                    loop.getB4R1().setText(String.valueOf(i));
                    loop.getB4R2().setText(ag.getB4r8());
               
                    loop.getB4R3().setText((ag.getB4r9().getB4r3()));
                    loop.getB4R4().setText(String.valueOf(j + 1));
                    b2TambahanList.add(loop.getB2Tambahan1());

                }
                i++;
            }

        }
    }
}
