/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkl53.view;

import java.util.ArrayList;
import java.util.List;
import pkl53.component.Textfield;
import pkl53.validasi.Blok56BValidasi;


/**
 *
 * @author User
 */
public class Blok56B extends javax.swing.JPanel {
    

    
    
    private Blok56 blok56;
    private ArrayList<Textfield> listTextFieldBlok56B = new ArrayList<Textfield>();
    private List<Textfield> String = new ArrayList<Textfield>();
    /**
     * Creates new form blok123
     */
    public Blok56B() {
        initComponents();
        addListTextfield();
        Blok56BValidasi val = new Blok56BValidasi();
        
        val.setPanelBlok56B(this);
        val.setPanelBlok56(blok56);
        val.registerValidasi();
        val.setList();
        
    }
    public Blok56B(DataEntriPekerjaanPanel dp) {
        initComponents();
        addListTextfield();
        Blok56BValidasi val = new Blok56BValidasi();
        
        val.setDataEntriPekerjaanPanel(dp);
        val.setPanelBlok56B(this);
        val.setPanelBlok56(blok56);
        val.registerValidasi();
        val.setList();
        
    }
    
    public List<Textfield> getListTextFieldBlok56B() {
        return listTextFieldBlok56B;
    }
   
    
     public void addListTextfield() {
         listTextFieldBlok56B.add(0,  getB6R11());
        listTextFieldBlok56B.add(1,  getB6R12a());
        listTextFieldBlok56B.add(2,  getB6R12b());
        listTextFieldBlok56B.add(3,  getB6R13());
        listTextFieldBlok56B.add(4,  getB6R14());
        listTextFieldBlok56B.add(5,  getB6R15barang());
        listTextFieldBlok56B.add(6,  getB6R15uang());
        listTextFieldBlok56B.add(7,  getB6R16());
        listTextFieldBlok56B.add(8,  getB6R17());
        listTextFieldBlok56B.add(9,  getB6R17lainnya());
        listTextFieldBlok56B.add(10,  getB6R18());
        listTextFieldBlok56B.add(11,  getB6R19());
        listTextFieldBlok56B.add(12,  getB6R20barang());
        listTextFieldBlok56B.add(13,  getB6R20uang());
        listTextFieldBlok56B.add(14,  getB6R21a());
        listTextFieldBlok56B.add(15,  getB6R21b());
        listTextFieldBlok56B.add(16,  getB6R21c());
        listTextFieldBlok56B.add(17,  getB6R22a());
        listTextFieldBlok56B.add(18,  getB6R22b());
        listTextFieldBlok56B.add(19,  getB6R22bLainnya());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        blok56BTamabahan = new pkl53.model.tambahan.Blok56BTamabahan();
        blok671 = new pkl53.imageClass.BlokPekerja56B();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        B6R21b = new pkl53.component.Textfield();
        B6R22a = new pkl53.component.Textfield();
        B6R12b = new pkl53.component.Textfield();
        B6R11 = new pkl53.component.Textfield();
        B6R12a = new pkl53.component.Textfield();
        B6R15uang = new pkl53.component.Textfield();
        B6R22b = new pkl53.component.Textfield();
        B6R13 = new pkl53.component.Textfield();
        B6R14 = new pkl53.component.Textfield();
        B6R16 = new pkl53.component.Textfield();
        B6R17lainnya = new pkl53.component.Textfield();
        B6R19 = new pkl53.component.Textfield();
        B6R20uang = new pkl53.component.Textfield();
        B6R18 = new pkl53.component.Textfield();
        B6R20barang = new pkl53.component.Textfield();
        B6R15barang = new pkl53.component.Textfield();
        B6R17 = new pkl53.component.Textfield();
        B6R21c = new pkl53.component.Textfield();
        B6R21a = new pkl53.component.Textfield();
        B6R22bLainnya = new pkl53.component.Textfield();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R11, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r11"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R12a, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r12a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R12b, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r12b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R13, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r13"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R14, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r14"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R15uang, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r15a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R15barang, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r15b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R16, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r16"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R17, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r17"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R17lainnya, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r17lain"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R18, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r18"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R19, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r19"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R15uang, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r20a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R15barang, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r20b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R21a, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r21a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R21b, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r21b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R21c, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r21c"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R22a, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r22a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R22b, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r22b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R22bLainnya, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r22blain"));
        bindingGroup.addBinding(binding);

        setBackground(new java.awt.Color(255, 255, 255));

        blok671.setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B6R21b.setPanel(blok671);
        B6R21b.setTextfield(B6R21c);
        jLayeredPane1.add(B6R21b, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 440, 35, 27));

        B6R22a.setPanel(blok671);
        B6R22a.setTextfield(B6R22b);
        jLayeredPane1.add(B6R22a, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 540, 35, 27));

        B6R12b.setNextType(true);
        B6R12b.setPanel(blok671);
        B6R12b.setTextfield(B6R13);
        jLayeredPane1.add(B6R12b, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 35, 30));

        B6R11.setNextType(true);
        B6R11.setPanel(blok671);
        B6R11.setTextfield(B6R12a);
        B6R11.setTextfieldKhusus(true);
        jLayeredPane1.add(B6R11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 35, 30));

        B6R12a.setNextType(true);
        B6R12a.setPanel(blok671);
        B6R12a.setTextfield(B6R12b);
        jLayeredPane1.add(B6R12a, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 35, 30));

        B6R15uang.setLength(9);
        B6R15uang.setNextType(true);
        B6R15uang.setPanel(blok671);
        B6R15uang.setTextfield(B6R15barang);
        jLayeredPane1.add(B6R15uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 710, 260, 27));

        B6R22b.setNextType(true);
        B6R22b.setPanel(blok671);
        B6R22b.setTextfield(B6R22bLainnya);
        jLayeredPane1.add(B6R22b, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 35, 27));

        B6R13.setNextType(true);
        B6R13.setPanel(blok671);
        B6R13.setTextfield(B6R14);
        jLayeredPane1.add(B6R13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 35, 30));

        B6R14.setNextType(true);
        B6R14.setPanel(blok671);
        B6R14.setTextfield(B6R15uang);
        jLayeredPane1.add(B6R14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 35, 30));

        B6R16.setNextType(true);
        B6R16.setPanel(blok671);
        B6R16.setTextfield(B6R17);
        jLayeredPane1.add(B6R16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 870, 35, 30));

        B6R17lainnya.setCharType('2');
        B6R17lainnya.setLength(30);
        B6R17lainnya.setNextType(true);
        B6R17lainnya.setPanel(blok671);
        B6R17lainnya.setTextfield(B6R18);
        jLayeredPane1.add(B6R17lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1020, 210, 25));

        B6R19.setNextType(true);
        B6R19.setPanel(blok671);
        B6R19.setTextfield(B6R20uang);
        jLayeredPane1.add(B6R19, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 177, 35, 30));

        B6R20uang.setLength(9);
        B6R20uang.setNextType(true);
        B6R20uang.setPanel(blok671);
        B6R20uang.setTextfield(B6R20barang);
        jLayeredPane1.add(B6R20uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 270, 27));

        B6R18.setNextType(true);
        B6R18.setPanel(blok671);
        B6R18.setTextfield(B6R19);
        B6R18.setTextfieldKhusus(true);
        jLayeredPane1.add(B6R18, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 77, 35, 30));

        B6R20barang.setLength(9);
        B6R20barang.setNextType(true);
        B6R20barang.setPanel(blok671);
        B6R20barang.setTextfield(B6R21a);
        jLayeredPane1.add(B6R20barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 270, 27));

        B6R15barang.setLength(9);
        B6R15barang.setNextType(true);
        B6R15barang.setPanel(blok671);
        B6R15barang.setTextfield(B6R16);
        jLayeredPane1.add(B6R15barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 760, 260, 27));

        B6R17.setNextType(true);
        B6R17.setPanel(blok671);
        B6R17.setTextfield(B6R17lainnya);
        jLayeredPane1.add(B6R17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 950, 35, 30));

        B6R21c.setNextType(true);
        B6R21c.setPanel(blok671);
        B6R21c.setTextfield(B6R22a);
        jLayeredPane1.add(B6R21c, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 35, 27));

        B6R21a.setNextType(true);
        B6R21a.setPanel(blok671);
        B6R21a.setTextfield(B6R21b);
        jLayeredPane1.add(B6R21a, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, 35, 27));

        B6R22bLainnya.setCharType('2');
        B6R22bLainnya.setLength(30);
        B6R22bLainnya.setPanel(blok671);
        jLayeredPane1.add(B6R22bLainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 670, 250, 27));

        javax.swing.GroupLayout blok671Layout = new javax.swing.GroupLayout(blok671);
        blok671.setLayout(blok671Layout);
        blok671Layout.setHorizontalGroup(
            blok671Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(blok671Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE))
        );
        blok671Layout.setVerticalGroup(
            blok671Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1761, Short.MAX_VALUE)
            .addGroup(blok671Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(blok671Layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1742, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blok671, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blok671, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static pkl53.component.Textfield B6R11;
    private pkl53.component.Textfield B6R12a;
    private pkl53.component.Textfield B6R12b;
    private pkl53.component.Textfield B6R13;
    private pkl53.component.Textfield B6R14;
    private pkl53.component.Textfield B6R15barang;
    private pkl53.component.Textfield B6R15uang;
    private pkl53.component.Textfield B6R16;
    private pkl53.component.Textfield B6R17;
    private pkl53.component.Textfield B6R17lainnya;
    private pkl53.component.Textfield B6R18;
    private pkl53.component.Textfield B6R19;
    private pkl53.component.Textfield B6R20barang;
    private pkl53.component.Textfield B6R20uang;
    private pkl53.component.Textfield B6R21a;
    private pkl53.component.Textfield B6R21b;
    private pkl53.component.Textfield B6R21c;
    private pkl53.component.Textfield B6R22a;
    private pkl53.component.Textfield B6R22b;
    private pkl53.component.Textfield B6R22bLainnya;
    private pkl53.model.tambahan.Blok56BTamabahan blok56BTamabahan;
    private pkl53.imageClass.BlokPekerja56B blok671;
    private javax.swing.JLayeredPane jLayeredPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the B6R11
     */
    public static pkl53.component.Textfield getB6R11() {
        return B6R11;
    }

    /**
     * @param B6R11 the B6R11 to set
     */
    public void setB6R11(pkl53.component.Textfield B6R11) {
        this.B6R11 = B6R11;
    }

    /**
     * @return the B6R12a
     */
    public pkl53.component.Textfield getB6R12a() {
        return B6R12a;
    }

    /**
     * @param B6R12a the B6R12a to set
     */
    public void setB6R12a(pkl53.component.Textfield B6R12a) {
        this.B6R12a = B6R12a;
    }

    /**
     * @return the B6R12b
     */
    public pkl53.component.Textfield getB6R12b() {
        return B6R12b;
    }

    /**
     * @param B6R12b the B6R12b to set
     */
    public void setB6R12b(pkl53.component.Textfield B6R12b) {
        this.B6R12b = B6R12b;
    }

    /**
     * @return the B6R13
     */
    public pkl53.component.Textfield getB6R13() {
        return B6R13;
    }

    /**
     * @param B6R13 the B6R13 to set
     */
    public void setB6R13(pkl53.component.Textfield B6R13) {
        this.B6R13 = B6R13;
    }

    /**
     * @return the B6R14
     */
    public pkl53.component.Textfield getB6R14() {
        return B6R14;
    }

    /**
     * @param B6R14 the B6R14 to set
     */
    public void setB6R14(pkl53.component.Textfield B6R14) {
        this.B6R14 = B6R14;
    }

    /**
     * @return the B6R15barang
     */
    public pkl53.component.Textfield getB6R15barang() {
        return B6R15barang;
    }

    /**
     * @param B6R15barang the B6R15barang to set
     */
    public void setB6R15barang(pkl53.component.Textfield B6R15barang) {
        this.B6R15barang = B6R15barang;
    }

    /**
     * @return the B6R15uang
     */
    public pkl53.component.Textfield getB6R15uang() {
        return B6R15uang;
    }

    /**
     * @param B6R15uang the B6R15uang to set
     */
    public void setB6R15uang(pkl53.component.Textfield B6R15uang) {
        this.B6R15uang = B6R15uang;
    }

    /**
     * @return the B6R16
     */
    public pkl53.component.Textfield getB6R16() {
        return B6R16;
    }

    /**
     * @param B6R16 the B6R16 to set
     */
    public void setB6R16(pkl53.component.Textfield B6R16) {
        this.B6R16 = B6R16;
    }

    /**
     * @return the B6R17
     */
    public pkl53.component.Textfield getB6R17() {
        return B6R17;
    }

    /**
     * @param B6R17 the B6R17 to set
     */
    public void setB6R17(pkl53.component.Textfield B6R17) {
        this.B6R17 = B6R17;
    }

    /**
     * @return the B6R17lainnya
     */
    public pkl53.component.Textfield getB6R17lainnya() {
        return B6R17lainnya;
    }

    /**
     * @param B6R17lainnya the B6R17lainnya to set
     */
    public void setB6R17lainnya(pkl53.component.Textfield B6R17lainnya) {
        this.B6R17lainnya = B6R17lainnya;
    }

    /**
     * @return the B6R18
     */
    public pkl53.component.Textfield getB6R18() {
        return B6R18;
    }

    /**
     * @param B6R18 the B6R18 to set
     */
    public void setB6R18(pkl53.component.Textfield B6R18) {
        this.B6R18 = B6R18;
    }

    /**
     * @return the B6R19
     */
    public pkl53.component.Textfield getB6R19() {
        return B6R19;
    }

    /**
     * @param B6R19 the B6R19 to set
     */
    public void setB6R19(pkl53.component.Textfield B6R19) {
        this.B6R19 = B6R19;
    }

    /**
     * @return the B6R20barang
     */
    public pkl53.component.Textfield getB6R20barang() {
        return B6R20barang;
    }

    /**
     * @param B6R20barang the B6R20barang to set
     */
    public void setB6R20barang(pkl53.component.Textfield B6R20barang) {
        this.B6R20barang = B6R20barang;
    }

    /**
     * @return the B6R20uang
     */
    public pkl53.component.Textfield getB6R20uang() {
        return B6R20uang;
    }

    /**
     * @param B6R20uang the B6R20uang to set
     */
    public void setB6R20uang(pkl53.component.Textfield B6R20uang) {
        this.B6R20uang = B6R20uang;
    }


    /**
     * @return the B6R22a
     */
    public pkl53.component.Textfield getB6R22a() {
        return B6R22a;
    }

    /**
     * @param B6R22a the B6R22a to set
     */
    public void setB6R22a(pkl53.component.Textfield B6R22a) {
        this.B6R22a = B6R22a;
    }

    /**
     * @return the B6R22b
     */
    public pkl53.component.Textfield getB6R22b() {
        return B6R22b;
    }

    /**
     * @param B6R22b the B6R22b to set
     */
    public void setB6R22b(pkl53.component.Textfield B6R22b) {
        this.B6R22b = B6R22b;
    }

    /**
     * @return the blok671
     */
    public pkl53.imageClass.BlokPekerja56B getBlok671() {
        return blok671;
    }

    /**
     * @param blok671 the blok671 to set
     */
    public void setBlok671(pkl53.imageClass.BlokPekerja56B blok671) {
        this.blok671 = blok671;
    }

    /**
     * @return the jLayeredPane1
     */
    public javax.swing.JLayeredPane getjLayeredPane1() {
        return jLayeredPane1;
    }

    /**
     * @param jLayeredPane1 the jLayeredPane1 to set
     */
    public void setjLayeredPane1(javax.swing.JLayeredPane jLayeredPane1) {
        this.jLayeredPane1 = jLayeredPane1;
    }

    /**
     * @return the B6R21a
     */
    public pkl53.component.Textfield getB6R21a() {
        return B6R21a;
    }

    /**
     * @param B6R21a the B6R21a to set
     */
    public void setB6R21a(pkl53.component.Textfield B6R21a) {
        this.B6R21a = B6R21a;
    }

    /**
     * @return the B6R21b
     */
    public pkl53.component.Textfield getB6R21b() {
        return B6R21b;
    }

    /**
     * @param B6R21b the B6R21b to set
     */
    public void setB6R21b(pkl53.component.Textfield B6R21b) {
        this.B6R21b = B6R21b;
    }

    /**
     * @return the B6R21c
     */
    public pkl53.component.Textfield getB6R21c() {
        return B6R21c;
    }

    /**
     * @param B6R21c the B6R21c to set
     */
    public void setB6R21c(pkl53.component.Textfield B6R21c) {
        this.B6R21c = B6R21c;
    }

    /**
     * @return the B6R22bLainnya
     */
    public pkl53.component.Textfield getB6R22bLainnya() {
        return B6R22bLainnya;
    }

    /**
     * @param B6R22bLainnya the B6R22bLainnya to set
     */
    public void setB6R22bLainnya(pkl53.component.Textfield B6R22bLainnya) {
        this.B6R22bLainnya = B6R22bLainnya;
    }

    /**
     * @return the blok56BTamabahan
     */
    public pkl53.model.tambahan.Blok56BTamabahan getBlok56BTamabahan() {
        return blok56BTamabahan;
    }

    /**
     * @param blok56BTamabahan the blok56BTamabahan to set
     */
    public void setBlok56BTamabahan(pkl53.model.tambahan.Blok56BTamabahan blok56BTamabahan) {
        this.blok56BTamabahan = blok56BTamabahan;
    }

    void setBlok56(Blok56 blok56) {
        this.blok56 = blok56;
    }

   
    
  
}
