/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl53.view;

import java.awt.Component;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import pkl53.component.Textfield;
import pkl53.converter.IntegerConverter;
import pkl53.model.tambahan.B3r15PekerjaTambahan;
import pkl53.validasi.UsahaBlok5BValidasi;
import pkl53.view.loop.LoopUsaha;

/**
 *
 * @author lele
 */
public class BlokUsaha5B extends javax.swing.JPanel {

    private ArrayList<Textfield> listTextFieldBlokUsaha5b = new ArrayList<Textfield>();
    private ArrayList<B3r15PekerjaTambahan> listModelB3R15 = new ArrayList<B3r15PekerjaTambahan>();
    private LoopUsaha lu;
    private String KKSArtNup;

    /**
     * Creates new form blok123
     */
    public BlokUsaha5B() {
        initComponents();
        addListTextfield();
        UsahaBlok5BValidasi val = new  UsahaBlok5BValidasi();
        val.setPanelUsahaBlok5B(this);
        val.registerValidasi();
        val.setList5BUsaha();
        
        

        GridLayout grid = new GridLayout(20, 1, 0, 0);
        loopPanel.setLayout(grid);
        jScrollPane1.getViewport().setOpaque(false);

    }

    public List<Textfield> getListTextFieldBlokUsaha5b() {
        return listTextFieldBlokUsaha5b;
    }

    public void addListTextfield() {
        //35
        listTextFieldBlokUsaha5b.add(B5R16);
        listTextFieldBlokUsaha5b.add(B5R17A_NON);
        listTextFieldBlokUsaha5b.add(B5R17A_PERT);
        listTextFieldBlokUsaha5b.add(B5R17B_NON);
        listTextFieldBlokUsaha5b.add(B5R17B_PERT);
        listTextFieldBlokUsaha5b.add(B5R17CI_NON);
        listTextFieldBlokUsaha5b.add(B5R17CI_PERT);
        listTextFieldBlokUsaha5b.add(B5R17CII_NON);
        listTextFieldBlokUsaha5b.add(B5R17CII_PERT);
        listTextFieldBlokUsaha5b.add(B5R17CIII_NON);
        listTextFieldBlokUsaha5b.add(B5R17CIII_PERT);
        listTextFieldBlokUsaha5b.add(B5R17DI_NON);
        listTextFieldBlokUsaha5b.add(B5R17DI_PERT);
        listTextFieldBlokUsaha5b.add(B5R17DII_NON);
        listTextFieldBlokUsaha5b.add(B5R17DII_PERT);
        listTextFieldBlokUsaha5b.add(B5R17E_NON);
        listTextFieldBlokUsaha5b.add(B5R17E_PERT);
        listTextFieldBlokUsaha5b.add(B5R17F_NON);
        listTextFieldBlokUsaha5b.add(B5R17F_PERT);
        listTextFieldBlokUsaha5b.add(B5R17G_NON);
        listTextFieldBlokUsaha5b.add(B5R17G_PERT);
        listTextFieldBlokUsaha5b.add(B5R17H_NON);
        listTextFieldBlokUsaha5b.add(B5R17H_PERT);
        listTextFieldBlokUsaha5b.add(B5R17I_NON);
        listTextFieldBlokUsaha5b.add(B5R17I_PERT);
        listTextFieldBlokUsaha5b.add(B5R17J_NON);
        listTextFieldBlokUsaha5b.add(B5R17J_PERT);
        listTextFieldBlokUsaha5b.add(B5R17K_NON);
        listTextFieldBlokUsaha5b.add(B5R17K_PERT);
        listTextFieldBlokUsaha5b.add(B5R17L_NON);
        listTextFieldBlokUsaha5b.add(B5R17L_PERT);
        listTextFieldBlokUsaha5b.add(B5R17LABA_NON);
        listTextFieldBlokUsaha5b.add(B5R17LABA_PERT);
        listTextFieldBlokUsaha5b.add(B5R17TOT_NON);
        listTextFieldBlokUsaha5b.add(B5R17TOT_PERT);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        b3RinciusahaTambahan1 = new pkl53.model.tambahan.B3RinciusahaTambahan();
        blok5abcUsaha1 = new pkl53.imageClass.BlokUsaha5B();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        B5R16 = new pkl53.component.Textfield();
        B5R17A_PERT = new pkl53.component.Textfield();
        B5R17B_PERT = new pkl53.component.Textfield();
        B5R17CI_PERT = new pkl53.component.Textfield();
        B5R17CII_PERT = new pkl53.component.Textfield();
        B5R17CIII_PERT = new pkl53.component.Textfield();
        B5R17DI_PERT = new pkl53.component.Textfield();
        B5R17DII_PERT = new pkl53.component.Textfield();
        B5R17E_PERT = new pkl53.component.Textfield();
        B5R17F_PERT = new pkl53.component.Textfield();
        B5R17G_PERT = new pkl53.component.Textfield();
        B5R17H_PERT = new pkl53.component.Textfield();
        B5R17I_PERT = new pkl53.component.Textfield();
        B5R17J_PERT = new pkl53.component.Textfield();
        B5R17K_PERT = new pkl53.component.Textfield();
        B5R17L_PERT = new pkl53.component.Textfield();
        B5R17TOT_PERT = new pkl53.component.Textfield();
        B5R17LABA_PERT = new pkl53.component.Textfield();
        B5R17A_NON = new pkl53.component.Textfield();
        B5R17B_NON = new pkl53.component.Textfield();
        B5R17CI_NON = new pkl53.component.Textfield();
        B5R17CII_NON = new pkl53.component.Textfield();
        B5R17CIII_NON = new pkl53.component.Textfield();
        B5R17DI_NON = new pkl53.component.Textfield();
        B5R17DII_NON = new pkl53.component.Textfield();
        B5R17E_NON = new pkl53.component.Textfield();
        B5R17F_NON = new pkl53.component.Textfield();
        B5R17G_NON = new pkl53.component.Textfield();
        B5R17H_NON = new pkl53.component.Textfield();
        B5R17I_NON = new pkl53.component.Textfield();
        B5R17J_NON = new pkl53.component.Textfield();
        B5R17K_NON = new pkl53.component.Textfield();
        B5R17L_NON = new pkl53.component.Textfield();
        B5R17TOT_NON = new pkl53.component.Textfield();
        B5R17LABA_NON = new pkl53.component.Textfield();
        jScrollPane1 = new javax.swing.JScrollPane();
        loopPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R16, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R16"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17A_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17A_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17A_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17A_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17B_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17B_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17B_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17B_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17CI_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17CI_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17CI_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17CI_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17CII_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17CII_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17CII_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17CII_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17CIII_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17CIII_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17CIII_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17CIII_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17DI_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17DI_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17DI_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17DI_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17DII_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17DII_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17DII_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17DII_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17E_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17E_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17E_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17E_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17F_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17F_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17F_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17F_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17G_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17G_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17G_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17G_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17H_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17H_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17H_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17H_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17I_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17I_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17I_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17I_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17J_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17J_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17J_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17J_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17K_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17K_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17K_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17K_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17L_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17L_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17L_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17L_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17LABA_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17LABA_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17LABA_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17LABA_PERT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17TOT_NON, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17TOT_NON"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17TOT_PERT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R17TOT_PERT"));
        bindingGroup.addBinding(binding);

        setPreferredSize(new java.awt.Dimension(1070, 1381));
        setLayout(new java.awt.BorderLayout());

        blok5abcUsaha1.setPreferredSize(new java.awt.Dimension(1070, 1983));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1070, 1389));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B5R16.setLength(11);
        B5R16.setNextType(true);
        B5R16.setPanel(blok5abcUsaha1);
        B5R16.setTextfield(B5R17A_PERT);
        B5R16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R16ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 705, 350, 30));

        B5R17A_PERT.setLength(9);
        B5R17A_PERT.setNextType(true);
        B5R17A_PERT.setPanel(blok5abcUsaha1);
        B5R17A_PERT.setTextfield(B5R17B_PERT);
        B5R17A_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17A_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17A_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 835, 270, 25));

        B5R17B_PERT.setLength(9);
        B5R17B_PERT.setNextType(true);
        B5R17B_PERT.setPanel(blok5abcUsaha1);
        B5R17B_PERT.setTextfield(B5R17CI_PERT);
        B5R17B_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17B_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17B_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 868, 270, 25));

        B5R17CI_PERT.setLength(9);
        B5R17CI_PERT.setNextType(true);
        B5R17CI_PERT.setPanel(blok5abcUsaha1);
        B5R17CI_PERT.setTextfield(B5R17CII_PERT);
        B5R17CI_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17CI_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17CI_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 933, 270, 25));

        B5R17CII_PERT.setLength(9);
        B5R17CII_PERT.setNextType(true);
        B5R17CII_PERT.setPanel(blok5abcUsaha1);
        B5R17CII_PERT.setTextfield(B5R17CIII_PERT);
        B5R17CII_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17CII_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17CII_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 965, 270, 25));

        B5R17CIII_PERT.setLength(9);
        B5R17CIII_PERT.setNextType(true);
        B5R17CIII_PERT.setPanel(blok5abcUsaha1);
        B5R17CIII_PERT.setTextfield(B5R17DI_PERT);
        B5R17CIII_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17CIII_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17CIII_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 997, 270, 25));

        B5R17DI_PERT.setLength(9);
        B5R17DI_PERT.setNextType(true);
        B5R17DI_PERT.setPanel(blok5abcUsaha1);
        B5R17DI_PERT.setTextfield(B5R17DII_PERT);
        B5R17DI_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17DI_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17DI_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1062, 270, 25));

        B5R17DII_PERT.setLength(9);
        B5R17DII_PERT.setNextType(true);
        B5R17DII_PERT.setPanel(blok5abcUsaha1);
        B5R17DII_PERT.setTextfield(B5R17E_PERT);
        B5R17DII_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17DII_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17DII_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1094, 270, 25));

        B5R17E_PERT.setLength(9);
        B5R17E_PERT.setNextType(true);
        B5R17E_PERT.setPanel(blok5abcUsaha1);
        B5R17E_PERT.setTextfield(B5R17F_PERT);
        B5R17E_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17E_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17E_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1126, 270, 25));

        B5R17F_PERT.setLength(9);
        B5R17F_PERT.setNextType(true);
        B5R17F_PERT.setPanel(blok5abcUsaha1);
        B5R17F_PERT.setTextfield(B5R17G_PERT);
        B5R17F_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17F_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17F_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1158, 270, 25));

        B5R17G_PERT.setLength(9);
        B5R17G_PERT.setNextType(true);
        B5R17G_PERT.setPanel(blok5abcUsaha1);
        B5R17G_PERT.setTextfield(B5R17H_PERT);
        B5R17G_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17G_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17G_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1191, 270, 25));

        B5R17H_PERT.setLength(9);
        B5R17H_PERT.setNextType(true);
        B5R17H_PERT.setPanel(blok5abcUsaha1);
        B5R17H_PERT.setTextfield(B5R17I_PERT);
        B5R17H_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17H_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17H_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1223, 270, 25));

        B5R17I_PERT.setLength(9);
        B5R17I_PERT.setNextType(true);
        B5R17I_PERT.setPanel(blok5abcUsaha1);
        B5R17I_PERT.setTextfield(B5R17J_PERT);
        B5R17I_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17I_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17I_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1255, 270, 25));

        B5R17J_PERT.setLength(9);
        B5R17J_PERT.setNextType(true);
        B5R17J_PERT.setPanel(blok5abcUsaha1);
        B5R17J_PERT.setTextfield(B5R17K_PERT);
        B5R17J_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17J_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17J_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1287, 270, 25));

        B5R17K_PERT.setLength(9);
        B5R17K_PERT.setNextType(true);
        B5R17K_PERT.setPanel(blok5abcUsaha1);
        B5R17K_PERT.setTextfield(B5R17L_PERT);
        B5R17K_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17K_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17K_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1320, 270, 25));

        B5R17L_PERT.setLength(9);
        B5R17L_PERT.setNextType(true);
        B5R17L_PERT.setPanel(blok5abcUsaha1);
        B5R17L_PERT.setTextfield(B5R17TOT_PERT);
        B5R17L_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17L_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17L_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1353, 270, 25));

        B5R17TOT_PERT.setLength(9);
        B5R17TOT_PERT.setNextType(true);
        B5R17TOT_PERT.setPanel(blok5abcUsaha1);
        B5R17TOT_PERT.setTextfield(B5R17LABA_PERT);
        B5R17TOT_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17TOT_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17TOT_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1385, 270, 25));

        B5R17LABA_PERT.setCharType('2');
        B5R17LABA_PERT.setLength(9);
        B5R17LABA_PERT.setNextType(true);
        B5R17LABA_PERT.setPanel(blok5abcUsaha1);
        B5R17LABA_PERT.setTextfield(B5R17A_NON);
        B5R17LABA_PERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17LABA_PERTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17LABA_PERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1421, 270, 25));

        B5R17A_NON.setLength(9);
        B5R17A_NON.setNextType(true);
        B5R17A_NON.setPanel(blok5abcUsaha1);
        B5R17A_NON.setTextfield(B5R17B_NON);
        B5R17A_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17A_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17A_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 835, 270, 25));

        B5R17B_NON.setLength(9);
        B5R17B_NON.setNextType(true);
        B5R17B_NON.setPanel(blok5abcUsaha1);
        B5R17B_NON.setTextfield(B5R17CI_NON);
        B5R17B_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17B_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17B_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 868, 270, 25));

        B5R17CI_NON.setLength(9);
        B5R17CI_NON.setNextType(true);
        B5R17CI_NON.setPanel(blok5abcUsaha1);
        B5R17CI_NON.setTextfield(B5R17CII_NON);
        B5R17CI_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17CI_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17CI_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 933, 270, 25));

        B5R17CII_NON.setLength(9);
        B5R17CII_NON.setNextType(true);
        B5R17CII_NON.setPanel(blok5abcUsaha1);
        B5R17CII_NON.setTextfield(B5R17CIII_NON);
        B5R17CII_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17CII_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17CII_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 965, 270, 25));

        B5R17CIII_NON.setLength(9);
        B5R17CIII_NON.setNextType(true);
        B5R17CIII_NON.setPanel(blok5abcUsaha1);
        B5R17CIII_NON.setTextfield(B5R17DI_NON);
        B5R17CIII_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17CIII_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17CIII_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 997, 270, 25));

        B5R17DI_NON.setLength(9);
        B5R17DI_NON.setNextType(true);
        B5R17DI_NON.setPanel(blok5abcUsaha1);
        B5R17DI_NON.setTextfield(B5R17DII_NON);
        B5R17DI_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17DI_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17DI_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1062, 270, 25));

        B5R17DII_NON.setLength(9);
        B5R17DII_NON.setNextType(true);
        B5R17DII_NON.setPanel(blok5abcUsaha1);
        B5R17DII_NON.setTextfield(B5R17E_NON);
        B5R17DII_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17DII_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17DII_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1094, 270, 25));

        B5R17E_NON.setLength(9);
        B5R17E_NON.setNextType(true);
        B5R17E_NON.setPanel(blok5abcUsaha1);
        B5R17E_NON.setTextfield(B5R17F_NON);
        B5R17E_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17E_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17E_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1126, 270, 25));

        B5R17F_NON.setLength(9);
        B5R17F_NON.setNextType(true);
        B5R17F_NON.setPanel(blok5abcUsaha1);
        B5R17F_NON.setTextfield(B5R17G_NON);
        B5R17F_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17F_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17F_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1158, 270, 25));

        B5R17G_NON.setLength(9);
        B5R17G_NON.setNextType(true);
        B5R17G_NON.setPanel(blok5abcUsaha1);
        B5R17G_NON.setTextfield(B5R17H_NON);
        B5R17G_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17G_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17G_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1191, 270, 25));

        B5R17H_NON.setLength(9);
        B5R17H_NON.setNextType(true);
        B5R17H_NON.setPanel(blok5abcUsaha1);
        B5R17H_NON.setTextfield(B5R17I_NON);
        B5R17H_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17H_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17H_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1223, 270, 25));

        B5R17I_NON.setLength(9);
        B5R17I_NON.setNextType(true);
        B5R17I_NON.setPanel(blok5abcUsaha1);
        B5R17I_NON.setTextfield(B5R17J_NON);
        B5R17I_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17I_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17I_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1255, 270, 25));

        B5R17J_NON.setLength(9);
        B5R17J_NON.setNextType(true);
        B5R17J_NON.setPanel(blok5abcUsaha1);
        B5R17J_NON.setTextfield(B5R17K_NON);
        B5R17J_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17J_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17J_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1287, 270, 25));

        B5R17K_NON.setLength(9);
        B5R17K_NON.setNextType(true);
        B5R17K_NON.setPanel(blok5abcUsaha1);
        B5R17K_NON.setTextfield(B5R17L_NON);
        B5R17K_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17K_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17K_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1320, 270, 25));

        B5R17L_NON.setLength(9);
        B5R17L_NON.setNextType(true);
        B5R17L_NON.setPanel(blok5abcUsaha1);
        B5R17L_NON.setTextfield(B5R17TOT_NON);
        B5R17L_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17L_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17L_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1353, 270, 25));

        B5R17TOT_NON.setLength(9);
        B5R17TOT_NON.setNextType(true);
        B5R17TOT_NON.setPanel(blok5abcUsaha1);
        B5R17TOT_NON.setTextfield(B5R17LABA_NON);
        B5R17TOT_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17TOT_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17TOT_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1385, 270, 25));

        B5R17LABA_NON.setCharType('2');
        B5R17LABA_NON.setLength(9);
        B5R17LABA_NON.setPanel(blok5abcUsaha1);
        B5R17LABA_NON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R17LABA_NONActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R17LABA_NON, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1421, 270, 25));

        loopPanel.setOpaque(false);

        javax.swing.GroupLayout loopPanelLayout = new javax.swing.GroupLayout(loopPanel);
        loopPanel.setLayout(loopPanelLayout);
        loopPanelLayout.setHorizontalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1011, Short.MAX_VALUE)
        );
        loopPanelLayout.setVerticalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(loopPanel);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 210, 1020, 290));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, -1, -1));

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, -1, -1));

        javax.swing.GroupLayout blok5abcUsaha1Layout = new javax.swing.GroupLayout(blok5abcUsaha1);
        blok5abcUsaha1.setLayout(blok5abcUsaha1Layout);
        blok5abcUsaha1Layout.setHorizontalGroup(
            blok5abcUsaha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        blok5abcUsaha1Layout.setVerticalGroup(
            blok5abcUsaha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1527, Short.MAX_VALUE)
        );

        add(blok5abcUsaha1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void B5R16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R16ActionPerformed

    private void B5R17CI_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17CI_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17CI_PERTActionPerformed

    private void B5R17A_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17A_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17A_NONActionPerformed

    private void B5R17B_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17B_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17B_NONActionPerformed

    private void B5R17CI_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17CI_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17CI_NONActionPerformed

    private void B5R17DI_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17DI_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17DI_NONActionPerformed

    private void B5R17DII_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17DII_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17DII_NONActionPerformed

    private void B5R17E_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17E_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17E_NONActionPerformed

    private void B5R17F_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17F_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17F_NONActionPerformed

    private void B5R17G_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17G_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17G_NONActionPerformed

    private void B5R17H_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17H_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17H_NONActionPerformed

    private void B5R17I_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17I_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17I_NONActionPerformed

    private void B5R17J_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17J_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17J_NONActionPerformed

    private void B5R17K_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17K_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17K_NONActionPerformed

    private void B5R17L_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17L_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17L_NONActionPerformed

    private void B5R17TOT_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17TOT_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17TOT_NONActionPerformed

    private void B5R17LABA_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17LABA_NONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17LABA_NONActionPerformed

    private void B5R17A_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17A_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17A_PERTActionPerformed

    private void B5R17B_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17B_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17B_PERTActionPerformed

    private void B5R17CII_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17CII_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17CII_PERTActionPerformed

    private void B5R17CIII_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17CIII_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17CIII_PERTActionPerformed

    private void B5R17DI_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17DI_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17DI_PERTActionPerformed

    private void B5R17DII_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17DII_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17DII_PERTActionPerformed

    private void B5R17E_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17E_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17E_PERTActionPerformed

    private void B5R17F_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17F_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17F_PERTActionPerformed

    private void B5R17G_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17G_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17G_PERTActionPerformed

    private void B5R17H_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17H_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17H_PERTActionPerformed

    private void B5R17I_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17I_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17I_PERTActionPerformed

    private void B5R17J_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17J_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17J_PERTActionPerformed

    private void B5R17K_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17K_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17K_PERTActionPerformed

    private void B5R17L_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17L_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17L_PERTActionPerformed

    private void B5R17TOT_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17TOT_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17TOT_PERTActionPerformed

    private void B5R17LABA_PERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17LABA_PERTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R17LABA_PERTActionPerformed

    private void B5R17CII_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17CII_NONActionPerformed


    }//GEN-LAST:event_B5R17CII_NONActionPerformed

    private void B5R17CIII_NONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R17CIII_NONActionPerformed

    }//GEN-LAST:event_B5R17CIII_NONActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String x = JOptionPane.showInputDialog(null, "Masukkan jumlah pekerja yang ingin ditambahkan!",
                "Tambah Pekerja",
                JOptionPane.WARNING_MESSAGE
        );
        IntegerConverter intconvert = new IntegerConverter();
        if (!x.equals("")) {
            addLoop(intconvert.convertForward(x));
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String x = JOptionPane.showInputDialog(null, "Masukkan jumlah pekerja yang ingin dihapus !!!",
                "Delete Pekerja Terakhir",
                JOptionPane.WARNING_MESSAGE
        );
        IntegerConverter intconvert = new IntegerConverter();
        if (!x.equals("")) {
            deleteLoop(intconvert.convertForward(x));
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl53.component.Textfield B5R16;
    private pkl53.component.Textfield B5R17A_NON;
    private pkl53.component.Textfield B5R17A_PERT;
    private pkl53.component.Textfield B5R17B_NON;
    private pkl53.component.Textfield B5R17B_PERT;
    private pkl53.component.Textfield B5R17CIII_NON;
    private pkl53.component.Textfield B5R17CIII_PERT;
    private pkl53.component.Textfield B5R17CII_NON;
    private pkl53.component.Textfield B5R17CII_PERT;
    private pkl53.component.Textfield B5R17CI_NON;
    private pkl53.component.Textfield B5R17CI_PERT;
    private pkl53.component.Textfield B5R17DII_NON;
    private pkl53.component.Textfield B5R17DII_PERT;
    private pkl53.component.Textfield B5R17DI_NON;
    private pkl53.component.Textfield B5R17DI_PERT;
    private pkl53.component.Textfield B5R17E_NON;
    private pkl53.component.Textfield B5R17E_PERT;
    private pkl53.component.Textfield B5R17F_NON;
    private pkl53.component.Textfield B5R17F_PERT;
    private pkl53.component.Textfield B5R17G_NON;
    private pkl53.component.Textfield B5R17G_PERT;
    private pkl53.component.Textfield B5R17H_NON;
    private pkl53.component.Textfield B5R17H_PERT;
    private pkl53.component.Textfield B5R17I_NON;
    private pkl53.component.Textfield B5R17I_PERT;
    private pkl53.component.Textfield B5R17J_NON;
    private pkl53.component.Textfield B5R17J_PERT;
    private pkl53.component.Textfield B5R17K_NON;
    private pkl53.component.Textfield B5R17K_PERT;
    private pkl53.component.Textfield B5R17LABA_NON;
    private pkl53.component.Textfield B5R17LABA_PERT;
    private pkl53.component.Textfield B5R17L_NON;
    private pkl53.component.Textfield B5R17L_PERT;
    private pkl53.component.Textfield B5R17TOT_NON;
    private pkl53.component.Textfield B5R17TOT_PERT;
    private javax.swing.JButton addButton;
    private pkl53.model.tambahan.B3RinciusahaTambahan b3RinciusahaTambahan1;
    private pkl53.imageClass.BlokUsaha5B blok5abcUsaha1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel loopPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the B5R16
     */
    public pkl53.component.Textfield getB5R16() {
        return B5R16;
    }

    /**
     * @param B5R16 the B5R16 to set
     */
    public void setB5R16(pkl53.component.Textfield B5R16) {
        this.B5R16 = B5R16;
    }

    /**
     * @return the B5R17A_NON
     */
    public pkl53.component.Textfield getB5R17A_NON() {
        return B5R17A_NON;
    }

    /**
     * @param B5R17A_NON the B5R17A_NON to set
     */
    public void setB5R17A_NON(pkl53.component.Textfield B5R17A_NON) {
        this.B5R17A_NON = B5R17A_NON;
    }

    /**
     * @return the B5R17A_PERT
     */
    public pkl53.component.Textfield getB5R17A_PERT() {
        return B5R17A_PERT;
    }

    /**
     * @param B5R17A_PERT the B5R17A_PERT to set
     */
    public void setB5R17A_PERT(pkl53.component.Textfield B5R17A_PERT) {
        this.B5R17A_PERT = B5R17A_PERT;
    }

    /**
     * @return the B5R17B_NON
     */
    public pkl53.component.Textfield getB5R17B_NON() {
        return B5R17B_NON;
    }

    /**
     * @param B5R17B_NON the B5R17B_NON to set
     */
    public void setB5R17B_NON(pkl53.component.Textfield B5R17B_NON) {
        this.B5R17B_NON = B5R17B_NON;
    }

    /**
     * @return the B5R17B_PERT
     */
    public pkl53.component.Textfield getB5R17B_PERT() {
        return B5R17B_PERT;
    }

    /**
     * @param B5R17B_PERT the B5R17B_PERT to set
     */
    public void setB5R17B_PERT(pkl53.component.Textfield B5R17B_PERT) {
        this.B5R17B_PERT = B5R17B_PERT;
    }

    /**
     * @return the B5R17CIII_NON
     */
    public pkl53.component.Textfield getB5R17CIII_NON() {
        return B5R17CIII_NON;
    }

    /**
     * @param B5R17CIII_NON the B5R17CIII_NON to set
     */
    public void setB5R17CIII_NON(pkl53.component.Textfield B5R17CIII_NON) {
        this.B5R17CIII_NON = B5R17CIII_NON;
    }

    /**
     * @return the B5R17CIII_PERT
     */
    public pkl53.component.Textfield getB5R17CIII_PERT() {
        return B5R17CIII_PERT;
    }

    /**
     * @param B5R17CIII_PERT the B5R17CIII_PERT to set
     */
    public void setB5R17CIII_PERT(pkl53.component.Textfield B5R17CIII_PERT) {
        this.B5R17CIII_PERT = B5R17CIII_PERT;
    }

    /**
     * @return the B5R17CII_NON
     */
    public pkl53.component.Textfield getB5R17CII_NON() {
        return B5R17CII_NON;
    }

    /**
     * @param B5R17CII_NON the B5R17CII_NON to set
     */
    public void setB5R17CII_NON(pkl53.component.Textfield B5R17CII_NON) {
        this.B5R17CII_NON = B5R17CII_NON;
    }

    /**
     * @return the B5R17CII_PERT
     */
    public pkl53.component.Textfield getB5R17CII_PERT() {
        return B5R17CII_PERT;
    }

    /**
     * @param B5R17CII_PERT the B5R17CII_PERT to set
     */
    public void setB5R17CII_PERT(pkl53.component.Textfield B5R17CII_PERT) {
        this.B5R17CII_PERT = B5R17CII_PERT;
    }

    /**
     * @return the B5R17CI_NON
     */
    public pkl53.component.Textfield getB5R17CI_NON() {
        return B5R17CI_NON;
    }

    /**
     * @param B5R17CI_NON the B5R17CI_NON to set
     */
    public void setB5R17CI_NON(pkl53.component.Textfield B5R17CI_NON) {
        this.B5R17CI_NON = B5R17CI_NON;
    }

    /**
     * @return the B5R17CI_PERT
     */
    public pkl53.component.Textfield getB5R17CI_PERT() {
        return B5R17CI_PERT;
    }

    /**
     * @param B5R17CI_PERT the B5R17CI_PERT to set
     */
    public void setB5R17CI_PERT(pkl53.component.Textfield B5R17CI_PERT) {
        this.B5R17CI_PERT = B5R17CI_PERT;
    }

    /**
     * @return the B5R17DII_NON
     */
    public pkl53.component.Textfield getB5R17DII_NON() {
        return B5R17DII_NON;
    }

    /**
     * @param B5R17DII_NON the B5R17DII_NON to set
     */
    public void setB5R17DII_NON(pkl53.component.Textfield B5R17DII_NON) {
        this.B5R17DII_NON = B5R17DII_NON;
    }

    /**
     * @return the B5R17DII_PERT
     */
    public pkl53.component.Textfield getB5R17DII_PERT() {
        return B5R17DII_PERT;
    }

    /**
     * @param B5R17DII_PERT the B5R17DII_PERT to set
     */
    public void setB5R17DII_PERT(pkl53.component.Textfield B5R17DII_PERT) {
        this.B5R17DII_PERT = B5R17DII_PERT;
    }

    /**
     * @return the B5R17DI_NON
     */
    public pkl53.component.Textfield getB5R17DI_NON() {
        return B5R17DI_NON;
    }

    /**
     * @param B5R17DI_NON the B5R17DI_NON to set
     */
    public void setB5R17DI_NON(pkl53.component.Textfield B5R17DI_NON) {
        this.B5R17DI_NON = B5R17DI_NON;
    }

    /**
     * @return the B5R17DI_PERT
     */
    public pkl53.component.Textfield getB5R17DI_PERT() {
        return B5R17DI_PERT;
    }

    /**
     * @param B5R17DI_PERT the B5R17DI_PERT to set
     */
    public void setB5R17DI_PERT(pkl53.component.Textfield B5R17DI_PERT) {
        this.B5R17DI_PERT = B5R17DI_PERT;
    }

    /**
     * @return the B5R17E_PERT
     */
    public pkl53.component.Textfield getB5R17E_PERT() {
        return B5R17E_PERT;
    }

    /**
     * @param B5R17E_PERT the B5R17E_PERT to set
     */
    public void setB5R17E_PERT(pkl53.component.Textfield B5R17E_PERT) {
        this.B5R17E_PERT = B5R17E_PERT;
    }

    /**
     * @return the B5R17F_NON
     */
    public pkl53.component.Textfield getB5R17F_NON() {
        return B5R17F_NON;
    }

    /**
     * @param B5R17F_NON the B5R17F_NON to set
     */
    public void setB5R17F_NON(pkl53.component.Textfield B5R17F_NON) {
        this.B5R17F_NON = B5R17F_NON;
    }

    /**
     * @return the B5R17F_PERT
     */
    public pkl53.component.Textfield getB5R17F_PERT() {
        return B5R17F_PERT;
    }

    /**
     * @param B5R17F_PERT the B5R17F_PERT to set
     */
    public void setB5R17F_PERT(pkl53.component.Textfield B5R17F_PERT) {
        this.B5R17F_PERT = B5R17F_PERT;
    }

    /**
     * @return the B5R17G_NON
     */
    public pkl53.component.Textfield getB5R17G_NON() {
        return B5R17G_NON;
    }

    /**
     * @param B5R17G_NON the B5R17G_NON to set
     */
    public void setB5R17G_NON(pkl53.component.Textfield B5R17G_NON) {
        this.B5R17G_NON = B5R17G_NON;
    }

    /**
     * @return the B5R17G_PERT
     */
    public pkl53.component.Textfield getB5R17G_PERT() {
        return B5R17G_PERT;
    }

    /**
     * @param B5R17G_PERT the B5R17G_PERT to set
     */
    public void setB5R17G_PERT(pkl53.component.Textfield B5R17G_PERT) {
        this.B5R17G_PERT = B5R17G_PERT;
    }

    /**
     * @return the B5R17H_NON
     */
    public pkl53.component.Textfield getB5R17H_NON() {
        return B5R17H_NON;
    }

    /**
     * @param B5R17H_NON the B5R17H_NON to set
     */
    public void setB5R17H_NON(pkl53.component.Textfield B5R17H_NON) {
        this.B5R17H_NON = B5R17H_NON;
    }

    /**
     * @return the B5R17H_PERT
     */
    public pkl53.component.Textfield getB5R17H_PERT() {
        return B5R17H_PERT;
    }

    /**
     * @param B5R17H_PERT the B5R17H_PERT to set
     */
    public void setB5R17H_PERT(pkl53.component.Textfield B5R17H_PERT) {
        this.B5R17H_PERT = B5R17H_PERT;
    }

    /**
     * @return the B5R17I_NON
     */
    public pkl53.component.Textfield getB5R17I_NON() {
        return B5R17I_NON;
    }

    /**
     * @param B5R17I_NON the B5R17I_NON to set
     */
    public void setB5R17I_NON(pkl53.component.Textfield B5R17I_NON) {
        this.B5R17I_NON = B5R17I_NON;
    }

    /**
     * @return the B5R17I_PERT
     */
    public pkl53.component.Textfield getB5R17I_PERT() {
        return B5R17I_PERT;
    }

    /**
     * @param B5R17I_PERT the B5R17I_PERT to set
     */
    public void setB5R17I_PERT(pkl53.component.Textfield B5R17I_PERT) {
        this.B5R17I_PERT = B5R17I_PERT;
    }

    /**
     * @return the B5R17J_NON
     */
    public pkl53.component.Textfield getB5R17J_NON() {
        return B5R17J_NON;
    }

    /**
     * @param B5R17J_NON the B5R17J_NON to set
     */
    public void setB5R17J_NON(pkl53.component.Textfield B5R17J_NON) {
        this.B5R17J_NON = B5R17J_NON;
    }

    /**
     * @return the B5R17J_PERT
     */
    public pkl53.component.Textfield getB5R17J_PERT() {
        return B5R17J_PERT;
    }

    /**
     * @param B5R17J_PERT the B5R17J_PERT to set
     */
    public void setB5R17J_PERT(pkl53.component.Textfield B5R17J_PERT) {
        this.B5R17J_PERT = B5R17J_PERT;
    }

    /**
     * @return the B5R17K_NON
     */
    public pkl53.component.Textfield getB5R17K_NON() {
        return B5R17K_NON;
    }

    /**
     * @param B5R17K_NON the B5R17K_NON to set
     */
    public void setB5R17K_NON(pkl53.component.Textfield B5R17K_NON) {
        this.B5R17K_NON = B5R17K_NON;
    }

    /**
     * @return the B5R17K_PERT
     */
    public pkl53.component.Textfield getB5R17K_PERT() {
        return B5R17K_PERT;
    }

    /**
     * @param B5R17K_PERT the B5R17K_PERT to set
     */
    public void setB5R17K_PERT(pkl53.component.Textfield B5R17K_PERT) {
        this.B5R17K_PERT = B5R17K_PERT;
    }

    /**
     * @return the B5R17LABA_NON
     */
    public pkl53.component.Textfield getB5R17LABA_NON() {
        return B5R17LABA_NON;
    }

    /**
     * @param B5R17LABA_NON the B5R17LABA_NON to set
     */
    public void setB5R17LABA_NON(pkl53.component.Textfield B5R17LABA_NON) {
        this.B5R17LABA_NON = B5R17LABA_NON;
    }

    /**
     * @return the B5R17LABA_PERT
     */
    public pkl53.component.Textfield getB5R17LABA_PERT() {
        return B5R17LABA_PERT;
    }

    /**
     * @param B5R17LABA_PERT the B5R17LABA_PERT to set
     */
    public void setB5R17LABA_PERT(pkl53.component.Textfield B5R17LABA_PERT) {
        this.B5R17LABA_PERT = B5R17LABA_PERT;
    }

    /**
     * @return the B5R17L_NON
     */
    public pkl53.component.Textfield getB5R17L_NON() {
        return B5R17L_NON;
    }

    /**
     * @param B5R17L_NON the B5R17L_NON to set
     */
    public void setB5R17L_NON(pkl53.component.Textfield B5R17L_NON) {
        this.B5R17L_NON = B5R17L_NON;
    }

    /**
     * @return the B5R17L_PERT
     */
    public pkl53.component.Textfield getB5R17L_PERT() {
        return B5R17L_PERT;
    }

    /**
     * @param B5R17L_PERT the B5R17L_PERT to set
     */
    public void setB5R17L_PERT(pkl53.component.Textfield B5R17L_PERT) {
        this.B5R17L_PERT = B5R17L_PERT;
    }

    /**
     * @return the B5R17TOT_NON
     */
    public pkl53.component.Textfield getB5R17TOT_NON() {
        return B5R17TOT_NON;
    }

    /**
     * @param B5R17TOT_NON the B5R17TOT_NON to set
     */
    public void setB5R17TOT_NON(pkl53.component.Textfield B5R17TOT_NON) {
        this.B5R17TOT_NON = B5R17TOT_NON;
    }

    /**
     * @return the B5R17TOT_PERT
     */
    public pkl53.component.Textfield getB5R17TOT_PERT() {
        return B5R17TOT_PERT;
    }

    /**
     * @param B5R17TOT_PERT the B5R17TOT_PERT to set
     */
    public void setB5R17TOT_PERT(pkl53.component.Textfield B5R17TOT_PERT) {
        this.B5R17TOT_PERT = B5R17TOT_PERT;
    }

    /**
     * @return the BR17E_NON
     */
    public pkl53.component.Textfield getBR17E_NON() {
        return getB5R17E_NON();
    }

    /**
     * @param BR17E_NON the BR17E_NON to set
     */
    public void setBR17E_NON(pkl53.component.Textfield BR17E_NON) {
        this.setB5R17E_NON(BR17E_NON);
    }

    /**
     * @return the KKSArtNup
     */
    public String getKKSArtNup() {
        return KKSArtNup;
    }

    /**
     * @param KKSArtNup the KKSArtNup to set
     */
    public void setKKSArtNup(String KKSArtNup) {
        this.KKSArtNup = KKSArtNup;
    }

    /**
     * @return the B5R17E_NON
     */
    public pkl53.component.Textfield getB5R17E_NON() {
        return B5R17E_NON;
    }

    /**
     * @param B5R17E_NON the B5R17E_NON to set
     */
    public void setB5R17E_NON(pkl53.component.Textfield B5R17E_NON) {
        this.B5R17E_NON = B5R17E_NON;
    }

    /**
     * @return the listModelB3R15
     */
    public ArrayList<B3r15PekerjaTambahan> getListModelB3R15() {
        return listModelB3R15;
    }

    /**
     * @return the b3RinciusahaTambahan1
     */
    public pkl53.model.tambahan.B3RinciusahaTambahan getB3RinciusahaTambahan1() {
        return b3RinciusahaTambahan1;
    }

    public void deleteLoop(int jumlahRT) {
        int rt = 1;
        Component[] comp = getLoopPanel().getComponents();
        if ((jumlahRT == 1 && comp.length == 1)||jumlahRT>=comp.length) {

            getLoopPanel().removeAll();
            listModelB3R15.clear();
            getLoopPanel().updateUI();

        }

        //cara mengambil banyak record ya da samapai jumpa 1 kepala rumah tangga?
        for (int i = comp.length - 1; i > 0; i--) {
            if (rt > jumlahRT) {

                break;
            }
            getLoopPanel().remove(i);
            listModelB3R15.remove(i);
            getLoopPanel().updateUI();

            rt++;

        }
    }

    private void addLoop(int jumlah) {
        for (int i = 0; i < jumlah; i++) {
            lu = new LoopUsaha();
            getLoopPanel().add(lu);
            listModelB3R15.add(lu.getB3r15PekerjaTambahan1());
            getLoopPanel().updateUI();

        }

    }

    /**
     * @return the loopPanel
     */
    public javax.swing.JPanel getLoopPanel() {
        return loopPanel;
    }

}
