/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkl53.view;

import java.util.ArrayList;
import java.util.List;
import pkl53.component.Textfield;
import pkl53.validasi.UsahaBlok5CValidasi;
import pkl53.validasi.UsahaBlok5DValidasi;


/**
 *
 * @author YOPPY
 */
public class BlokUsaha5D extends javax.swing.JPanel {

    private ArrayList<Textfield> listTextFieldBlokUsaha5d = new ArrayList<Textfield>();
    
    
/**
     * Creates new form blok78
     */
    public BlokUsaha5D() {
        initComponents();
        addListTextfield();
        UsahaBlok5DValidasi val = new UsahaBlok5DValidasi();
        
        val.setPanelBlokUsaha(this);
        val.registerValidasi();
        val.setList5DUsaha();
    }
    
    
    public List<Textfield> getListTextFieldBlokUsaha5d() {
        return listTextFieldBlokUsaha5d;
    }

    public void addListTextfield() {
        //43 textfield
        listTextFieldBlokUsaha5d.add(B5R24);
        listTextFieldBlokUsaha5d.add(B5R25A);
        listTextFieldBlokUsaha5d.add(B5R25B);
        listTextFieldBlokUsaha5d.add(B5R25C);
        listTextFieldBlokUsaha5d.add(B5R25D);
        listTextFieldBlokUsaha5d.add(B5R25E);
        listTextFieldBlokUsaha5d.add(B5R25F);
        listTextFieldBlokUsaha5d.add(B5R25G);
        listTextFieldBlokUsaha5d.add(B5R25H);
        listTextFieldBlokUsaha5d.add(B5R25I);
        listTextFieldBlokUsaha5d.add(B5R25J);
        listTextFieldBlokUsaha5d.add(B5R25K);
        listTextFieldBlokUsaha5d.add(B5R25L);
        listTextFieldBlokUsaha5d.add(B5R25M_LAIN);
        listTextFieldBlokUsaha5d.add(B5R26A);
        listTextFieldBlokUsaha5d.add(B5R26Lainnya);
        listTextFieldBlokUsaha5d.add(B5R27_1);
        listTextFieldBlokUsaha5d.add(B5R27_10_LAIN);
        listTextFieldBlokUsaha5d.add(B5R27_2);
        listTextFieldBlokUsaha5d.add(B5R27_3);
        listTextFieldBlokUsaha5d.add(B5R27_4);
        listTextFieldBlokUsaha5d.add(B5R27_5);
        listTextFieldBlokUsaha5d.add(B5R27_6);
        listTextFieldBlokUsaha5d.add(B5R27_7);
        listTextFieldBlokUsaha5d.add(B5R27_8);
        listTextFieldBlokUsaha5d.add(B5R27_9);
        listTextFieldBlokUsaha5d.add(B5R28);
        listTextFieldBlokUsaha5d.add(B5R29_1);
        listTextFieldBlokUsaha5d.add(B5R29_2);
        listTextFieldBlokUsaha5d.add(B5R29_3);
        listTextFieldBlokUsaha5d.add(B5R30A);
        listTextFieldBlokUsaha5d.add(B5R30B);
        listTextFieldBlokUsaha5d.add(B5R30C);
        listTextFieldBlokUsaha5d.add(B5R30D);
        listTextFieldBlokUsaha5d.add(B5R30E);
        listTextFieldBlokUsaha5d.add(B5R30F);
        listTextFieldBlokUsaha5d.add(B5R30G);
        listTextFieldBlokUsaha5d.add(B5R31);
        listTextFieldBlokUsaha5d.add(B5R32);
        listTextFieldBlokUsaha5d.add(B5R33);
        listTextFieldBlokUsaha5d.add(B5R34);
        listTextFieldBlokUsaha5d.add(B5R35);
        listTextFieldBlokUsaha5d.add(B5R36);

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        b3RinciusahaTambahan1 = new pkl53.model.tambahan.B3RinciusahaTambahan();
        blok78Usaha1 = new pkl53.imageClass.BlokUsaha5D();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        B5R24 = new pkl53.component.Textfield();
        B5R25A = new pkl53.component.Textfield();
        B5R25B = new pkl53.component.Textfield();
        B5R25C = new pkl53.component.Textfield();
        B5R25D = new pkl53.component.Textfield();
        B5R25E = new pkl53.component.Textfield();
        B5R25F = new pkl53.component.Textfield();
        B5R25G = new pkl53.component.Textfield();
        B5R25H = new pkl53.component.Textfield();
        B5R25I = new pkl53.component.Textfield();
        B5R25J = new pkl53.component.Textfield();
        B5R25K = new pkl53.component.Textfield();
        B5R25L = new pkl53.component.Textfield();
        B5R25M_LAIN = new pkl53.component.Textfield();
        B5R26A = new pkl53.component.Textfield();
        B5R26Lainnya = new pkl53.component.Textfield();
        B5R27_1 = new pkl53.component.Textfield();
        B5R27_2 = new pkl53.component.Textfield();
        B5R27_3 = new pkl53.component.Textfield();
        B5R27_4 = new pkl53.component.Textfield();
        B5R27_5 = new pkl53.component.Textfield();
        B5R27_6 = new pkl53.component.Textfield();
        B5R27_7 = new pkl53.component.Textfield();
        B5R27_8 = new pkl53.component.Textfield();
        B5R27_9 = new pkl53.component.Textfield();
        B5R27_10_LAIN = new pkl53.component.Textfield();
        B5R28 = new pkl53.component.Textfield();
        B5R29_1 = new pkl53.component.Textfield();
        B5R29_2 = new pkl53.component.Textfield();
        B5R29_3 = new pkl53.component.Textfield();
        B5R30A = new pkl53.component.Textfield();
        B5R30B = new pkl53.component.Textfield();
        B5R30C = new pkl53.component.Textfield();
        B5R30D = new pkl53.component.Textfield();
        B5R30E = new pkl53.component.Textfield();
        B5R30F = new pkl53.component.Textfield();
        B5R30G = new pkl53.component.Textfield();
        B5R31 = new pkl53.component.Textfield();
        B5R32 = new pkl53.component.Textfield();
        B5R33 = new pkl53.component.Textfield();
        B5R34 = new pkl53.component.Textfield();
        B5R35 = new pkl53.component.Textfield();
        B5R36 = new pkl53.component.Textfield();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R24, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R24"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25A, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25A"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25B, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25B"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25C, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25C"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25D, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25D"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25E, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25E"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25F, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25F"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25G, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25G"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25H, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25H"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25I, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25I"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25J, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25J"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25K, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25K"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25L, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25L"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R25M_LAIN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R25M_LAIN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R26A, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R26A"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R26Lainnya, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R26Lainnya"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R27_1, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R27_1"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R27_10_LAIN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R27_10_LAIN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R27_2, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R27_2"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R27_3, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R27_3"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R27_4, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R27_4"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R27_5, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R27_5"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R27_6, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R27_6"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R27_7, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R27_7"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R27_8, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R27_8"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R27_9, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R27_9"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R28, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R28"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R29_1, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R29_1"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R29_2, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R29_2"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R29_3, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R29_3"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R30A, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R30A"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R30B, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R30B"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R30C, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R30C"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R30D, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R30D"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R30E, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R30E"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R30F, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R30F"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R30G, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R30G"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R31, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R31"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R32, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R32"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R33, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R33"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R34, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R34"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R35, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R35"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R36, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R36"));
        bindingGroup.addBinding(binding);

        setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B5R24.setNextType(true);
        B5R24.setPanel(blok78Usaha1);
        B5R24.setTextfield(B5R25A);
        B5R24.setTextfieldKhusus(true);
        jLayeredPane1.add(B5R24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 30, 30));

        B5R25A.setNextType(true);
        B5R25A.setPanel(blok78Usaha1);
        B5R25A.setTextfield(B5R25B);
        B5R25A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25AActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25A, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 30, 25));

        B5R25B.setNextType(true);
        B5R25B.setPanel(blok78Usaha1);
        B5R25B.setTextfield(B5R25C);
        B5R25B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25BActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25B, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 255, 30, 25));

        B5R25C.setNextType(true);
        B5R25C.setPanel(blok78Usaha1);
        B5R25C.setTextfield(B5R25D);
        B5R25C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25CActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25C, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 285, 30, 25));

        B5R25D.setNextType(true);
        B5R25D.setPanel(blok78Usaha1);
        B5R25D.setTextfield(B5R25E);
        B5R25D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25DActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25D, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 30, 25));

        B5R25E.setNextType(true);
        B5R25E.setPanel(blok78Usaha1);
        B5R25E.setTextfield(B5R25F);
        B5R25E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25EActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25E, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 30, 25));

        B5R25F.setNextType(true);
        B5R25F.setPanel(blok78Usaha1);
        B5R25F.setTextfield(B5R25G);
        B5R25F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25FActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25F, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 365, 30, 25));

        B5R25G.setNextType(true);
        B5R25G.setPanel(blok78Usaha1);
        B5R25G.setTextfield(B5R25H);
        B5R25G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25GActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25G, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 395, 30, 25));

        B5R25H.setNextType(true);
        B5R25H.setPanel(blok78Usaha1);
        B5R25H.setTextfield(B5R25I);
        B5R25H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25HActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25H, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 30, 25));

        B5R25I.setNextType(true);
        B5R25I.setPanel(blok78Usaha1);
        B5R25I.setTextfield(B5R25J);
        B5R25I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25IActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25I, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 30, 25));

        B5R25J.setNextType(true);
        B5R25J.setPanel(blok78Usaha1);
        B5R25J.setTextfield(B5R25K);
        B5R25J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25JActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25J, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 475, 30, 25));

        B5R25K.setNextType(true);
        B5R25K.setPanel(blok78Usaha1);
        B5R25K.setTextfield(B5R25L);
        B5R25K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25KActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25K, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 30, 25));

        B5R25L.setNextType(true);
        B5R25L.setPanel(blok78Usaha1);
        B5R25L.setTextfield(B5R25M_LAIN);
        B5R25L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25LActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25L, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 535, 30, 25));

        B5R25M_LAIN.setCharType('2');
        B5R25M_LAIN.setLength(30);
        B5R25M_LAIN.setNextType(true);
        B5R25M_LAIN.setPanel(blok78Usaha1);
        B5R25M_LAIN.setTextfield(B5R26A);
        B5R25M_LAIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R25M_LAINActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R25M_LAIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 230, 25));

        B5R26A.setNextType(true);
        B5R26A.setPanel(blok78Usaha1);
        B5R26A.setTextfield(B5R26Lainnya);
        B5R26A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R26AActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R26A, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 690, 30, 30));

        B5R26Lainnya.setCharType('2');
        B5R26Lainnya.setLength(30);
        B5R26Lainnya.setNextType(true);
        B5R26Lainnya.setPanel(blok78Usaha1);
        B5R26Lainnya.setTextfield(B5R27_1);
        B5R26Lainnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R26LainnyaActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R26Lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 740, 220, 25));

        B5R27_1.setNextType(true);
        B5R27_1.setPanel(blok78Usaha1);
        B5R27_1.setTextfield(B5R27_2);
        B5R27_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R27_1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R27_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 850, 30, 25));

        B5R27_2.setNextType(true);
        B5R27_2.setPanel(blok78Usaha1);
        B5R27_2.setTextfield(B5R27_3);
        B5R27_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R27_2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R27_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 875, 30, 25));

        B5R27_3.setNextType(true);
        B5R27_3.setPanel(blok78Usaha1);
        B5R27_3.setTextfield(B5R27_4);
        B5R27_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R27_3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R27_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 900, 30, 25));

        B5R27_4.setNextType(true);
        B5R27_4.setPanel(blok78Usaha1);
        B5R27_4.setTextfield(B5R27_5);
        B5R27_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R27_4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R27_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 925, 30, 25));

        B5R27_5.setNextType(true);
        B5R27_5.setPanel(blok78Usaha1);
        B5R27_5.setTextfield(B5R27_6);
        B5R27_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R27_5ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R27_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 955, 30, 25));

        B5R27_6.setNextType(true);
        B5R27_6.setPanel(blok78Usaha1);
        B5R27_6.setTextfield(B5R27_7);
        B5R27_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R27_6ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R27_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 980, 30, 25));

        B5R27_7.setNextType(true);
        B5R27_7.setPanel(blok78Usaha1);
        B5R27_7.setTextfield(B5R27_8);
        B5R27_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R27_7ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R27_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1005, 30, 25));

        B5R27_8.setNextType(true);
        B5R27_8.setPanel(blok78Usaha1);
        B5R27_8.setTextfield(B5R27_9);
        B5R27_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R27_8ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R27_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1035, 30, 25));

        B5R27_9.setNextType(true);
        B5R27_9.setPanel(blok78Usaha1);
        B5R27_9.setTextfield(B5R27_10_LAIN);
        B5R27_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R27_9ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R27_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1060, 30, 25));

        B5R27_10_LAIN.setCharType('2');
        B5R27_10_LAIN.setLength(30);
        B5R27_10_LAIN.setNextType(true);
        B5R27_10_LAIN.setPanel(blok78Usaha1);
        B5R27_10_LAIN.setTextfield(B5R28);
        B5R27_10_LAIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R27_10_LAINActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R27_10_LAIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1090, 160, 25));

        B5R28.setNextType(true);
        B5R28.setPanel(blok78Usaha1);
        B5R28.setTextfield(B5R29_1);
        B5R28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R28ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R28, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1190, 30, 30));

        B5R29_1.setCharType('2');
        B5R29_1.setLength(30);
        B5R29_1.setNextType(true);
        B5R29_1.setPanel(blok78Usaha1);
        B5R29_1.setTextfield(B5R29_2);
        jLayeredPane1.add(B5R29_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1340, 240, 25));

        B5R29_2.setCharType('2');
        B5R29_2.setLength(30);
        B5R29_2.setNextType(true);
        B5R29_2.setPanel(blok78Usaha1);
        B5R29_2.setTextfield(B5R29_3);
        B5R29_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R29_2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R29_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1370, 240, 25));

        B5R29_3.setCharType('2');
        B5R29_3.setLength(30);
        B5R29_3.setNextType(true);
        B5R29_3.setPanel(blok78Usaha1);
        B5R29_3.setTextfield(B5R30A);
        B5R29_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R29_3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R29_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1400, 240, 25));

        B5R30A.setNextType(true);
        B5R30A.setPanel(blok78Usaha1);
        B5R30A.setTextfield(B5R30B);
        B5R30A.setTextfieldKhusus(true);
        jLayeredPane1.add(B5R30A, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, 30, 30));

        B5R30B.setNextType(true);
        B5R30B.setPanel(blok78Usaha1);
        B5R30B.setTextfield(B5R30C);
        jLayeredPane1.add(B5R30B, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 160, 30, 30));

        B5R30C.setNextType(true);
        B5R30C.setPanel(blok78Usaha1);
        B5R30C.setTextfield(B5R30D);
        jLayeredPane1.add(B5R30C, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 30, 30));

        B5R30D.setNextType(true);
        B5R30D.setPanel(blok78Usaha1);
        B5R30D.setTextfield(B5R30E);
        jLayeredPane1.add(B5R30D, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, 30, 30));

        B5R30E.setNextType(true);
        B5R30E.setPanel(blok78Usaha1);
        B5R30E.setTextfield(B5R30F);
        jLayeredPane1.add(B5R30E, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, 30, 30));

        B5R30F.setNextType(true);
        B5R30F.setPanel(blok78Usaha1);
        B5R30F.setTextfield(B5R30G);
        jLayeredPane1.add(B5R30F, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 280, 30, 30));

        B5R30G.setNextType(true);
        B5R30G.setPanel(blok78Usaha1);
        B5R30G.setTextfield(B5R31);
        jLayeredPane1.add(B5R30G, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, 30, 30));

        B5R31.setNextType(true);
        B5R31.setPanel(blok78Usaha1);
        B5R31.setTextfield(B5R32);
        jLayeredPane1.add(B5R31, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 400, 30, 30));

        B5R32.setNextType(true);
        B5R32.setPanel(blok78Usaha1);
        B5R32.setTextfield(B5R33);
        jLayeredPane1.add(B5R32, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 50, 30));

        B5R33.setLength(2);
        B5R33.setNextType(true);
        B5R33.setPanel(blok78Usaha1);
        B5R33.setTextfield(B5R34);
        jLayeredPane1.add(B5R33, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 580, 60, 30));

        B5R34.setNextType(true);
        B5R34.setPanel(blok78Usaha1);
        B5R34.setTextfield(B5R35);
        jLayeredPane1.add(B5R34, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 710, 30, 30));

        B5R35.setNextType(true);
        B5R35.setPanel(blok78Usaha1);
        B5R35.setTextfield(B5R36);
        jLayeredPane1.add(B5R35, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 940, 30, 30));

        B5R36.setPanel(blok78Usaha1);
        jLayeredPane1.add(B5R36, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 1060, 30, 30));

        javax.swing.GroupLayout blok78Usaha1Layout = new javax.swing.GroupLayout(blok78Usaha1);
        blok78Usaha1.setLayout(blok78Usaha1Layout);
        blok78Usaha1Layout.setHorizontalGroup(
            blok78Usaha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        blok78Usaha1Layout.setVerticalGroup(
            blok78Usaha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blok78Usaha1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(blok78Usaha1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void B5R25AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25AActionPerformed

    private void B5R25BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25BActionPerformed

    private void B5R25CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25CActionPerformed

    private void B5R25DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25DActionPerformed

    private void B5R25EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25EActionPerformed

    private void B5R25FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25FActionPerformed

    private void B5R25GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25GActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25GActionPerformed

    private void B5R25HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25HActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25HActionPerformed

    private void B5R25IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25IActionPerformed

    private void B5R25JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25JActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25JActionPerformed

    private void B5R25KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25KActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25KActionPerformed

    private void B5R25LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25LActionPerformed

    private void B5R25M_LAINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R25M_LAINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R25M_LAINActionPerformed

    private void B5R26AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R26AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R26AActionPerformed

    private void B5R26LainnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R26LainnyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R26LainnyaActionPerformed

    private void B5R27_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R27_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R27_1ActionPerformed

    private void B5R27_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R27_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R27_2ActionPerformed

    private void B5R27_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R27_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R27_3ActionPerformed

    private void B5R27_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R27_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R27_4ActionPerformed

    private void B5R27_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R27_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R27_5ActionPerformed

    private void B5R27_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R27_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R27_6ActionPerformed

    private void B5R27_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R27_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R27_7ActionPerformed

    private void B5R27_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R27_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R27_8ActionPerformed

    private void B5R27_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R27_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R27_9ActionPerformed

    private void B5R27_10_LAINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R27_10_LAINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R27_10_LAINActionPerformed

    private void B5R28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R28ActionPerformed

    private void B5R29_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R29_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R29_2ActionPerformed

    private void B5R29_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R29_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R29_3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static pkl53.component.Textfield B5R24;
    private pkl53.component.Textfield B5R25A;
    private pkl53.component.Textfield B5R25B;
    private pkl53.component.Textfield B5R25C;
    private pkl53.component.Textfield B5R25D;
    private pkl53.component.Textfield B5R25E;
    private pkl53.component.Textfield B5R25F;
    private pkl53.component.Textfield B5R25G;
    private pkl53.component.Textfield B5R25H;
    private pkl53.component.Textfield B5R25I;
    private pkl53.component.Textfield B5R25J;
    private pkl53.component.Textfield B5R25K;
    private pkl53.component.Textfield B5R25L;
    private pkl53.component.Textfield B5R25M_LAIN;
    private pkl53.component.Textfield B5R26A;
    private pkl53.component.Textfield B5R26Lainnya;
    private pkl53.component.Textfield B5R27_1;
    private pkl53.component.Textfield B5R27_10_LAIN;
    private pkl53.component.Textfield B5R27_2;
    private pkl53.component.Textfield B5R27_3;
    private pkl53.component.Textfield B5R27_4;
    private pkl53.component.Textfield B5R27_5;
    private pkl53.component.Textfield B5R27_6;
    private pkl53.component.Textfield B5R27_7;
    private pkl53.component.Textfield B5R27_8;
    private pkl53.component.Textfield B5R27_9;
    private pkl53.component.Textfield B5R28;
    private pkl53.component.Textfield B5R29_1;
    private pkl53.component.Textfield B5R29_2;
    private pkl53.component.Textfield B5R29_3;
    private pkl53.component.Textfield B5R30A;
    private pkl53.component.Textfield B5R30B;
    private pkl53.component.Textfield B5R30C;
    private pkl53.component.Textfield B5R30D;
    private pkl53.component.Textfield B5R30E;
    private pkl53.component.Textfield B5R30F;
    private pkl53.component.Textfield B5R30G;
    private pkl53.component.Textfield B5R31;
    private pkl53.component.Textfield B5R32;
    private pkl53.component.Textfield B5R33;
    private pkl53.component.Textfield B5R34;
    private pkl53.component.Textfield B5R35;
    private pkl53.component.Textfield B5R36;
    private pkl53.model.tambahan.B3RinciusahaTambahan b3RinciusahaTambahan1;
    private pkl53.imageClass.BlokUsaha5D blok78Usaha1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    
    /**
     * @return the B3R53
     */
    public pkl53.component.Textfield getB3R53() {
        return getB5R26A();
    }

    /**
     * @param B3R53 the B3R53 to set
     */
    public void setB3R53(pkl53.component.Textfield B3R53) {
        this.setB5R26A(B3R53);
    }

    /**
     * @return the B3R54
     */
    public pkl53.component.Textfield getB3R54() {
        return getB5R26Lainnya();
    }

    /**
     * @param B3R54 the B3R54 to set
     */
    public void setB3R54(pkl53.component.Textfield B3R54) {
        this.setB5R26Lainnya(B3R54);
    }

    /**
     * @return the B5R24
     */
    public static pkl53.component.Textfield getB5R24() {
        return B5R24;
    }

    /**
     * @param B5R24 the B5R24 to set
     */
    public void setB5R24(pkl53.component.Textfield B5R24) {
        this.B5R24 = B5R24;
    }

    /**
     * @return the B5R25A
     */
    public pkl53.component.Textfield getB5R25A() {
        return B5R25A;
    }

    /**
     * @param B5R25A the B5R25A to set
     */
    public void setB5R25A(pkl53.component.Textfield B5R25A) {
        this.B5R25A = B5R25A;
    }

    /**
     * @return the B5R25B
     */
    public pkl53.component.Textfield getB5R25B() {
        return B5R25B;
    }

    /**
     * @param B5R25B the B5R25B to set
     */
    public void setB5R25B(pkl53.component.Textfield B5R25B) {
        this.B5R25B = B5R25B;
    }

    /**
     * @return the B5R25C
     */
    public pkl53.component.Textfield getB5R25C() {
        return B5R25C;
    }

    /**
     * @param B5R25C the B5R25C to set
     */
    public void setB5R25C(pkl53.component.Textfield B5R25C) {
        this.B5R25C = B5R25C;
    }

    /**
     * @return the B5R25D
     */
    public pkl53.component.Textfield getB5R25D() {
        return B5R25D;
    }

    /**
     * @param B5R25D the B5R25D to set
     */
    public void setB5R25D(pkl53.component.Textfield B5R25D) {
        this.B5R25D = B5R25D;
    }

    /**
     * @return the B5R25E
     */
    public pkl53.component.Textfield getB5R25E() {
        return B5R25E;
    }

    /**
     * @param B5R25E the B5R25E to set
     */
    public void setB5R25E(pkl53.component.Textfield B5R25E) {
        this.B5R25E = B5R25E;
    }

    /**
     * @return the B5R25F
     */
    public pkl53.component.Textfield getB5R25F() {
        return B5R25F;
    }

    /**
     * @param B5R25F the B5R25F to set
     */
    public void setB5R25F(pkl53.component.Textfield B5R25F) {
        this.B5R25F = B5R25F;
    }

    /**
     * @return the B5R25G
     */
    public pkl53.component.Textfield getB5R25G() {
        return B5R25G;
    }

    /**
     * @param B5R25G the B5R25G to set
     */
    public void setB5R25G(pkl53.component.Textfield B5R25G) {
        this.B5R25G = B5R25G;
    }

    /**
     * @return the B5R25H
     */
    public pkl53.component.Textfield getB5R25H() {
        return B5R25H;
    }

    /**
     * @param B5R25H the B5R25H to set
     */
    public void setB5R25H(pkl53.component.Textfield B5R25H) {
        this.B5R25H = B5R25H;
    }

    /**
     * @return the B5R25I
     */
    public pkl53.component.Textfield getB5R25I() {
        return B5R25I;
    }

    /**
     * @param B5R25I the B5R25I to set
     */
    public void setB5R25I(pkl53.component.Textfield B5R25I) {
        this.B5R25I = B5R25I;
    }

    /**
     * @return the B5R25J
     */
    public pkl53.component.Textfield getB5R25J() {
        return B5R25J;
    }

    /**
     * @param B5R25J the B5R25J to set
     */
    public void setB5R25J(pkl53.component.Textfield B5R25J) {
        this.B5R25J = B5R25J;
    }

    /**
     * @return the B5R25K
     */
    public pkl53.component.Textfield getB5R25K() {
        return B5R25K;
    }

    /**
     * @param B5R25K the B5R25K to set
     */
    public void setB5R25K(pkl53.component.Textfield B5R25K) {
        this.B5R25K = B5R25K;
    }

    /**
     * @return the B5R25L
     */
    public pkl53.component.Textfield getB5R25L() {
        return B5R25L;
    }

    /**
     * @param B5R25L the B5R25L to set
     */
    public void setB5R25L(pkl53.component.Textfield B5R25L) {
        this.B5R25L = B5R25L;
    }

    /**
     * @return the B5R25M_LAIN
     */
    public pkl53.component.Textfield getB5R25M_LAIN() {
        return B5R25M_LAIN;
    }

    /**
     * @param B5R25M_LAIN the B5R25M_LAIN to set
     */
    public void setB5R25M_LAIN(pkl53.component.Textfield B5R25M_LAIN) {
        this.B5R25M_LAIN = B5R25M_LAIN;
    }

    /**
     * @return the B5R27_1
     */
    public pkl53.component.Textfield getB5R27_1() {
        return B5R27_1;
    }

    /**
     * @param B5R27_1 the B5R27_1 to set
     */
    public void setB5R27_1(pkl53.component.Textfield B5R27_1) {
        this.B5R27_1 = B5R27_1;
    }

    /**
     * @return the B5R27_10_LAIN
     */
    public pkl53.component.Textfield getB5R27_10_LAIN() {
        return B5R27_10_LAIN;
    }

    /**
     * @param B5R27_10_LAIN the B5R27_10_LAIN to set
     */
    public void setB5R27_10_LAIN(pkl53.component.Textfield B5R27_10_LAIN) {
        this.B5R27_10_LAIN = B5R27_10_LAIN;
    }

    /**
     * @return the B5R27_2
     */
    public pkl53.component.Textfield getB5R27_2() {
        return B5R27_2;
    }

    /**
     * @param B5R27_2 the B5R27_2 to set
     */
    public void setB5R27_2(pkl53.component.Textfield B5R27_2) {
        this.B5R27_2 = B5R27_2;
    }

    /**
     * @return the B5R27_3
     */
    public pkl53.component.Textfield getB5R27_3() {
        return B5R27_3;
    }

    /**
     * @param B5R27_3 the B5R27_3 to set
     */
    public void setB5R27_3(pkl53.component.Textfield B5R27_3) {
        this.B5R27_3 = B5R27_3;
    }

    /**
     * @return the B5R27_4
     */
    public pkl53.component.Textfield getB5R27_4() {
        return B5R27_4;
    }

    /**
     * @param B5R27_4 the B5R27_4 to set
     */
    public void setB5R27_4(pkl53.component.Textfield B5R27_4) {
        this.B5R27_4 = B5R27_4;
    }

    /**
     * @return the B5R27_5
     */
    public pkl53.component.Textfield getB5R27_5() {
        return B5R27_5;
    }

    /**
     * @param B5R27_5 the B5R27_5 to set
     */
    public void setB5R27_5(pkl53.component.Textfield B5R27_5) {
        this.B5R27_5 = B5R27_5;
    }

    /**
     * @return the B5R27_6
     */
    public pkl53.component.Textfield getB5R27_6() {
        return B5R27_6;
    }

    /**
     * @param B5R27_6 the B5R27_6 to set
     */
    public void setB5R27_6(pkl53.component.Textfield B5R27_6) {
        this.B5R27_6 = B5R27_6;
    }

    /**
     * @return the B5R27_7
     */
    public pkl53.component.Textfield getB5R27_7() {
        return B5R27_7;
    }

    /**
     * @param B5R27_7 the B5R27_7 to set
     */
    public void setB5R27_7(pkl53.component.Textfield B5R27_7) {
        this.B5R27_7 = B5R27_7;
    }

    /**
     * @return the B5R27_8
     */
    public pkl53.component.Textfield getB5R27_8() {
        return B5R27_8;
    }

    /**
     * @param B5R27_8 the B5R27_8 to set
     */
    public void setB5R27_8(pkl53.component.Textfield B5R27_8) {
        this.B5R27_8 = B5R27_8;
    }

    /**
     * @return the B5R27_9
     */
    public pkl53.component.Textfield getB5R27_9() {
        return B5R27_9;
    }

    /**
     * @param B5R27_9 the B5R27_9 to set
     */
    public void setB5R27_9(pkl53.component.Textfield B5R27_9) {
        this.B5R27_9 = B5R27_9;
    }

    /**
     * @return the B5R28
     */
    public pkl53.component.Textfield getB5R28() {
        return B5R28;
    }

    /**
     * @param B5R28 the B5R28 to set
     */
    public void setB5R28(pkl53.component.Textfield B5R28) {
        this.B5R28 = B5R28;
    }

    /**
     * @return the B5R29_1
     */
    public pkl53.component.Textfield getB5R29_1() {
        return B5R29_1;
    }

    /**
     * @param B5R29_1 the B5R29_1 to set
     */
    public void setB5R29_1(pkl53.component.Textfield B5R29_1) {
        this.B5R29_1 = B5R29_1;
    }

    /**
     * @return the B5R29_2
     */
    public pkl53.component.Textfield getB5R29_2() {
        return B5R29_2;
    }

    /**
     * @param B5R29_2 the B5R29_2 to set
     */
    public void setB5R29_2(pkl53.component.Textfield B5R29_2) {
        this.B5R29_2 = B5R29_2;
    }

    /**
     * @return the B5R29_3
     */
    public pkl53.component.Textfield getB5R29_3() {
        return B5R29_3;
    }

    /**
     * @param B5R29_3 the B5R29_3 to set
     */
    public void setB5R29_3(pkl53.component.Textfield B5R29_3) {
        this.B5R29_3 = B5R29_3;
    }

    /**
     * @return the B5R30A
     */
    public pkl53.component.Textfield getB5R30A() {
        return B5R30A;
    }

    /**
     * @param B5R30A the B5R30A to set
     */
    public void setB5R30A(pkl53.component.Textfield B5R30A) {
        this.B5R30A = B5R30A;
    }

    /**
     * @return the B5R30B
     */
    public pkl53.component.Textfield getB5R30B() {
        return B5R30B;
    }

    /**
     * @param B5R30B the B5R30B to set
     */
    public void setB5R30B(pkl53.component.Textfield B5R30B) {
        this.B5R30B = B5R30B;
    }

    /**
     * @return the B5R30C
     */
    public pkl53.component.Textfield getB5R30C() {
        return B5R30C;
    }

    /**
     * @param B5R30C the B5R30C to set
     */
    public void setB5R30C(pkl53.component.Textfield B5R30C) {
        this.B5R30C = B5R30C;
    }

    /**
     * @return the B5R30D
     */
    public pkl53.component.Textfield getB5R30D() {
        return B5R30D;
    }

    /**
     * @param B5R30D the B5R30D to set
     */
    public void setB5R30D(pkl53.component.Textfield B5R30D) {
        this.B5R30D = B5R30D;
    }

    /**
     * @return the B5R30E
     */
    public pkl53.component.Textfield getB5R30E() {
        return B5R30E;
    }

    /**
     * @param B5R30E the B5R30E to set
     */
    public void setB5R30E(pkl53.component.Textfield B5R30E) {
        this.B5R30E = B5R30E;
    }

    /**
     * @return the B5R30F
     */
    public pkl53.component.Textfield getB5R30F() {
        return B5R30F;
    }

    /**
     * @param B5R30F the B5R30F to set
     */
    public void setB5R30F(pkl53.component.Textfield B5R30F) {
        this.B5R30F = B5R30F;
    }

    /**
     * @return the B5R30G
     */
    public pkl53.component.Textfield getB5R30G() {
        return B5R30G;
    }

    /**
     * @param B5R30G the B5R30G to set
     */
    public void setB5R30G(pkl53.component.Textfield B5R30G) {
        this.B5R30G = B5R30G;
    }

    /**
     * @return the B5R31
     */
    public pkl53.component.Textfield getB5R31() {
        return B5R31;
    }

    /**
     * @param B5R31 the B5R31 to set
     */
    public void setB5R31(pkl53.component.Textfield B5R31) {
        this.B5R31 = B5R31;
    }

    /**
     * @return the B5R32
     */
    public pkl53.component.Textfield getB5R32() {
        return B5R32;
    }

    /**
     * @param B5R32 the B5R32 to set
     */
    public void setB5R32(pkl53.component.Textfield B5R32) {
        this.B5R32 = B5R32;
    }

    /**
     * @return the B5R33
     */
    public pkl53.component.Textfield getB5R33() {
        return B5R33;
    }

    /**
     * @param B5R33 the B5R33 to set
     */
    public void setB5R33(pkl53.component.Textfield B5R33) {
        this.B5R33 = B5R33;
    }

    /**
     * @return the B5R34
     */
    public pkl53.component.Textfield getB5R34() {
        return B5R34;
    }

    /**
     * @param B5R34 the B5R34 to set
     */
    public void setB5R34(pkl53.component.Textfield B5R34) {
        this.B5R34 = B5R34;
    }

    /**
     * @return the B5R35
     */
    public pkl53.component.Textfield getB5R35() {
        return B5R35;
    }

    /**
     * @param B5R35 the B5R35 to set
     */
    public void setB5R35(pkl53.component.Textfield B5R35) {
        this.B5R35 = B5R35;
    }

    /**
     * @return the B5R36
     */
    public pkl53.component.Textfield getB5R36() {
        return B5R36;
    }

    /**
     * @param B5R36 the B5R36 to set
     */
    public void setB5R36(pkl53.component.Textfield B5R36) {
        this.B5R36 = B5R36;
    }

    /**
     * @return the B5R26A
     */
    public pkl53.component.Textfield getB5R26A() {
        return B5R26A;
    }

    /**
     * @param B5R26A the B5R26A to set
     */
    public void setB5R26A(pkl53.component.Textfield B5R26A) {
        this.B5R26A = B5R26A;
    }

    /**
     * @return the B5R26Lainnya
     */
    public pkl53.component.Textfield getB5R26Lainnya() {
        return B5R26Lainnya;
    }

    /**
     * @param B5R26Lainnya the B5R26Lainnya to set
     */
    public void setB5R26Lainnya(pkl53.component.Textfield B5R26Lainnya) {
        this.B5R26Lainnya = B5R26Lainnya;
    }

    /**
     * @return the b3RinciusahaTambahan1
     */
    public pkl53.model.tambahan.B3RinciusahaTambahan getB3RinciusahaTambahan1() {
        return b3RinciusahaTambahan1;
    }

}
