/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl53.view;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import pkl53.component.Textfield;
import pkl53.validasi.Blok56Validasi;
import static pkl53.view.Blok4Listing.getContainerPanel;
import pkl53.view.loop.Loop4Listing;

/**
 *
 * @author User
 */
public class Blok56 extends javax.swing.JPanel {

    private ArrayList<Textfield> listTextFieldBlok56 = new ArrayList<Textfield>();

    /**
     * Creates new form blok123
     */
    public Blok56() {
        initComponents();
        addListTextfield();
        Blok56Validasi val = new Blok56Validasi();
        val.setPanelBlok56(this);
        val.registerValidasi();
        val.setList();

    }

    public List<Textfield> getListTextFieldBlok56() {
        return listTextFieldBlok56;
    }

    public void addListTextfield() {
        listTextFieldBlok56.add(getB5R1Nama());
        listTextFieldBlok56.add(getB5R1Art());
        listTextFieldBlok56.add(getB5R2());
        listTextFieldBlok56.add(getB5R3());
        listTextFieldBlok56.add(getB5R4());
        listTextFieldBlok56.add(getB5R5());
        listTextFieldBlok56.add(getB5R6Prop());
        listTextFieldBlok56.add(getB5R6Kab());
        listTextFieldBlok56.add(getB5R7Prop());
        listTextFieldBlok56.add(getB5R7Kab());
        listTextFieldBlok56.add(getB5R8());
        listTextFieldBlok56.add(getB5R9());
        listTextFieldBlok56.add(getB5R10());
        listTextFieldBlok56.add(getB5R11());
        listTextFieldBlok56.add(getB5R12());
        listTextFieldBlok56.add(getB5R13());
        listTextFieldBlok56.add(getB5R14a());
        listTextFieldBlok56.add(getB5R14b());
        listTextFieldBlok56.add(getB5R15());
        listTextFieldBlok56.add(getB5R16());
        listTextFieldBlok56.add(getB5R17a());
        listTextFieldBlok56.add(getB5R17b());
        listTextFieldBlok56.add(getB6R1());
        listTextFieldBlok56.add(getB6R2());
        listTextFieldBlok56.add(getB6R3());
        listTextFieldBlok56.add(getB6R3tetap());
        listTextFieldBlok56.add(getB6R3tdktetap());
        listTextFieldBlok56.add(getB6R4a());
        listTextFieldBlok56.add(getB6R4b());
        listTextFieldBlok56.add(getB6R5a());
        listTextFieldBlok56.add(getB6R5b());
        listTextFieldBlok56.add(getB6R6utama());
        listTextFieldBlok56.add(getB6R6lainnya());
        listTextFieldBlok56.add(getB6R6lainnya2());
        listTextFieldBlok56.add(getB6R7a());
        listTextFieldBlok56.add(getB6R7b());
        listTextFieldBlok56.add(getB6R8a());
        listTextFieldBlok56.add(getB6R8b1());
        listTextFieldBlok56.add(getB6R8b2());
        listTextFieldBlok56.add(getB6R8b3());
        listTextFieldBlok56.add(getB6R8b4());
        listTextFieldBlok56.add(getB6R8b5());
        listTextFieldBlok56.add(getB6R8b6());
        listTextFieldBlok56.add(getB6R8b8());
        listTextFieldBlok56.add(getB6R8bJuml());
        listTextFieldBlok56.add(getB6R9a());
        listTextFieldBlok56.add(getB6R9b());
        listTextFieldBlok56.add(getB6R10());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        blok56BTamabahan = new pkl53.model.tambahan.Blok56BTamabahan();
        blok561 = new pkl53.imageClass.BlokPekerja56();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        B5R1Nama = new pkl53.component.Textfield();
        B5R2 = new pkl53.component.Textfield();
        B6R3 = new pkl53.component.Textfield();
        B5R4 = new pkl53.component.Textfield();
        B5R5 = new pkl53.component.Textfield();
        B5R6Kab = new pkl53.component.Textfield();
        B5R7Kab = new pkl53.component.Textfield();
        B5R8 = new pkl53.component.Textfield();
        B5R9 = new pkl53.component.Textfield();
        B5R10 = new pkl53.component.Textfield();
        B5R11 = new pkl53.component.Textfield();
        B5R12 = new pkl53.component.Textfield();
        B5R13 = new pkl53.component.Textfield();
        B6R2 = new pkl53.component.Textfield();
        B5R3 = new pkl53.component.Textfield();
        B6R7a = new pkl53.component.Textfield();
        B6R6utama = new pkl53.component.Textfield();
        B6R8a = new pkl53.component.Textfield();
        B6R9b = new pkl53.component.Textfield();
        B5R1Art = new pkl53.component.Textfield();
        B5R6Prop = new pkl53.component.Textfield();
        B5R7Prop = new pkl53.component.Textfield();
        B5R14b = new pkl53.component.Textfield();
        B5R15 = new pkl53.component.Textfield();
        B5R16 = new pkl53.component.Textfield();
        B5R17a = new pkl53.component.Textfield();
        B6R7b = new pkl53.component.Textfield();
        B5R14a = new pkl53.component.Textfield();
        B6R4b = new pkl53.component.Textfield();
        B6R4a = new pkl53.component.Textfield();
        B6R5a = new pkl53.component.Textfield();
        B6R5b = new pkl53.component.Textfield();
        B6R8b2 = new pkl53.component.Textfield();
        B6R8b1 = new pkl53.component.Textfield();
        B6R8b4 = new pkl53.component.Textfield();
        B6R8b3 = new pkl53.component.Textfield();
        B6R8b6 = new pkl53.component.Textfield();
        B6R8bJuml = new pkl53.component.Textfield();
        B6R8b5 = new pkl53.component.Textfield();
        B6R9a = new pkl53.component.Textfield();
        B6R10 = new pkl53.component.Textfield();
        B5R17b = new pkl53.component.Textfield();
        B6R1 = new pkl53.component.Textfield();
        B6R3tdktetap = new pkl53.component.Textfield();
        B6R3tetap = new pkl53.component.Textfield();
        B6R6lainnya = new pkl53.component.Textfield();
        B6R6lainnya2 = new pkl53.component.Textfield();
        B6R8b8 = new pkl53.component.Textfield();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R10, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r10"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R11, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r11"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R12, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r12"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r13"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R14a, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r14a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R14b, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r14b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R15, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r15"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R16, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r16"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17a, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r17a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R17b, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r17b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R1Art, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r1art"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R1Nama, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r1nama"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R2, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r2"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R3, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r3"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R4, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r4"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R5, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r5"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R6Prop, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r6a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R6Kab, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r6b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R7Prop, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r7a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R7Kab, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r7b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R8, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r8"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R9, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b5r9"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R1, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r1"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R10, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r10"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R2, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r2"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R3, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r3"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R3tetap, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r310lain"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R3tdktetap, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r313lain"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R4a, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r4a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R4b, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r4b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R5a, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r5a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R5b, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r5b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R6lainnya, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r6lain"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R6lainnya2, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r6lainnya"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R6utama, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r6utama"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R7a, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r7a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R7b, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r7b"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R8a, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r8a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R8b5, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r8bJum"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R8bJuml, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r8bJuml"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R8b4, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r8bKam"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R8b8, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r8bMin"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R8b3, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r8bRab"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R8b6, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r8bSab"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R8b2, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r8bSel"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R8b1, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r8bSen"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R9a, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r9a"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B6R9b, org.jdesktop.beansbinding.ELProperty.create("${text}"), blok56BTamabahan, org.jdesktop.beansbinding.BeanProperty.create("b6r9b"));
        bindingGroup.addBinding(binding);

        setBackground(new java.awt.Color(255, 255, 255));

        blok561.setBackground(new java.awt.Color(255, 255, 255));
        blok561.setPreferredSize(new java.awt.Dimension(1070, 1765));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1070, 1305));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B5R1Nama.setCharType('2');
        B5R1Nama.setLength(30);
        B5R1Nama.setNextType(true);
        B5R1Nama.setPanel(blok561);
        B5R1Nama.setTextfield(B5R1Art);
        B5R1Nama.setTextfieldKhusus(true);
        jLayeredPane1.add(B5R1Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 108, 200, 25));

        B5R2.setNextType(true);
        B5R2.setPanel(blok561);
        B5R2.setTextfield(B5R3);
        B5R2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                B5R2FocusLost(evt);
            }
        });
        jLayeredPane1.add(B5R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 35, 30));

        B6R3.setLength(2);
        B6R3.setNextType(true);
        B6R3.setPanel(blok561);
        B6R3.setTextfield(B6R3tetap);
        jLayeredPane1.add(B6R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 210, 40, 30));

        B5R4.setLength(2);
        B5R4.setNextType(true);
        B5R4.setPanel(blok561);
        B5R4.setTextfield(B5R5);
        jLayeredPane1.add(B5R4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 293, 35, 30));

        B5R5.setNextType(true);
        B5R5.setPanel(blok561);
        B5R5.setTextfield(B5R6Prop);
        jLayeredPane1.add(B5R5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 35, 30));

        B5R6Kab.setCharType('2');
        B5R6Kab.setLength(3);
        B5R6Kab.setNextType(true);
        B5R6Kab.setPanel(blok561);
        B5R6Kab.setTextfield(B5R7Prop);
        jLayeredPane1.add(B5R6Kab, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 487, 70, 25));

        B5R7Kab.setCharType('2');
        B5R7Kab.setLength(3);
        B5R7Kab.setNextType(true);
        B5R7Kab.setPanel(blok561);
        B5R7Kab.setTextfield(B5R8);
        jLayeredPane1.add(B5R7Kab, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, 70, 25));

        B5R8.setNextType(true);
        B5R8.setPanel(blok561);
        B5R8.setTextfield(B5R9);
        jLayeredPane1.add(B5R8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, 40, 25));

        B5R9.setNextType(true);
        B5R9.setPanel(blok561);
        B5R9.setTextfield(B5R10);
        B5R9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R9ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 735, 35, 30));

        B5R10.setNextType(true);
        B5R10.setPanel(blok561);
        B5R10.setTextfield(B5R11);
        jLayeredPane1.add(B5R10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 820, 35, 30));

        B5R11.setNextType(true);
        B5R11.setPanel(blok561);
        B5R11.setTextfield(B5R12);
        jLayeredPane1.add(B5R11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 885, 35, 30));

        B5R12.setLength(2);
        B5R12.setNextType(true);
        B5R12.setPanel(blok561);
        B5R12.setTextfield(B5R13);
        jLayeredPane1.add(B5R12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1060, 40, 30));

        B5R13.setNextType(true);
        B5R13.setPanel(blok561);
        B5R13.setTextfield(B5R14a);
        jLayeredPane1.add(B5R13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1130, 37, 30));

        B6R2.setLength(2);
        B6R2.setNextType(true);
        B6R2.setPanel(blok561);
        B6R2.setTextfield(B6R3);
        B6R2.setTextfieldKhusus(true);
        B6R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6R2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B6R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 40, 30));

        B5R3.setNextType(true);
        B5R3.setPanel(blok561);
        B5R3.setTextfield(B5R4);
        jLayeredPane1.add(B5R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 245, 35, 30));

        B6R7a.setLength(2);
        B6R7a.setNextType(true);
        B6R7a.setPanel(blok561);
        B6R7a.setTextfield(B6R7b);
        jLayeredPane1.add(B6R7a, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 1115, 40, 30));

        B6R6utama.setLength(2);
        B6R6utama.setNextType(true);
        B6R6utama.setPanel(blok561);
        B6R6utama.setTextfield(B6R6lainnya);
        jLayeredPane1.add(B6R6utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 940, 35, 30));

        B6R8a.setLength(2);
        B6R8a.setNextType(true);
        B6R8a.setPanel(blok561);
        B6R8a.setTextfield(B6R8b1);
        jLayeredPane1.add(B6R8a, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 1215, 35, 30));

        B6R9b.setNextType(true);
        B6R9b.setPanel(blok561);
        B6R9b.setTextfield(B6R10);
        jLayeredPane1.add(B6R9b, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 1545, 35, 30));

        B5R1Art.setNextType(true);
        B5R1Art.setPanel(blok561);
        B5R1Art.setTextfield(B5R2);
        B5R1Art.setTextfieldKhusus(true);
        jLayeredPane1.add(B5R1Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 105, 35, 30));

        B5R6Prop.setCharType('2');
        B5R6Prop.setLength(3);
        B5R6Prop.setNextType(true);
        B5R6Prop.setPanel(blok561);
        B5R6Prop.setTextfield(B5R6Kab);
        jLayeredPane1.add(B5R6Prop, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 70, 25));

        B5R7Prop.setCharType('2');
        B5R7Prop.setLength(3);
        B5R7Prop.setNextType(true);
        B5R7Prop.setPanel(blok561);
        B5R7Prop.setTextfield(B5R7Kab);
        jLayeredPane1.add(B5R7Prop, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 70, 25));

        B5R14b.setLength(2);
        B5R14b.setNextType(true);
        B5R14b.setPanel(blok561);
        B5R14b.setTextfield(B5R15);
        jLayeredPane1.add(B5R14b, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1300, 40, 30));

        B5R15.setNextType(true);
        B5R15.setPanel(blok561);
        B5R15.setTextfield(B5R16);
        jLayeredPane1.add(B5R15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1355, 35, 30));

        B5R16.setNextType(true);
        B5R16.setPanel(blok561);
        B5R16.setTextfield(B5R17a);
        jLayeredPane1.add(B5R16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1425, 35, 30));

        B5R17a.setNextType(true);
        B5R17a.setPanel(blok561);
        B5R17a.setTextfield(B5R17b);
        jLayeredPane1.add(B5R17a, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1490, 35, 30));

        B6R7b.setLength(2);
        B6R7b.setNextType(true);
        B6R7b.setPanel(blok561);
        B6R7b.setTextfield(B6R8a);
        jLayeredPane1.add(B6R7b, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 1115, 40, 30));

        B5R14a.setLength(2);
        B5R14a.setNextType(true);
        B5R14a.setPanel(blok561);
        B5R14a.setTextfield(B5R14b);
        jLayeredPane1.add(B5R14a, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1270, 40, 30));

        B6R4b.setLength(3);
        B6R4b.setNextType(true);
        B6R4b.setPanel(blok561);
        B6R4b.setTextfield(B6R5a);
        jLayeredPane1.add(B6R4b, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 725, 50, 27));

        B6R4a.setLength(2);
        B6R4a.setNextType(true);
        B6R4a.setPanel(blok561);
        B6R4a.setTextfield(B6R4b);
        jLayeredPane1.add(B6R4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 725, 50, 27));

        B6R5a.setLength(2);
        B6R5a.setNextType(true);
        B6R5a.setPanel(blok561);
        B6R5a.setTextfield(B6R5b);
        jLayeredPane1.add(B6R5a, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 820, 50, 27));

        B6R5b.setLength(2);
        B6R5b.setNextType(true);
        B6R5b.setPanel(blok561);
        B6R5b.setTextfield(B6R6utama);
        jLayeredPane1.add(B6R5b, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 825, 50, 27));

        B6R8b2.setLength(2);
        B6R8b2.setNextType(true);
        B6R8b2.setPanel(blok561);
        B6R8b2.setTextfield(B6R8b3);
        jLayeredPane1.add(B6R8b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1340, 50, 30));

        B6R8b1.setLength(2);
        B6R8b1.setNextType(true);
        B6R8b1.setPanel(blok561);
        B6R8b1.setTextfield(B6R8b2);
        jLayeredPane1.add(B6R8b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 1340, 50, 30));

        B6R8b4.setLength(2);
        B6R8b4.setNextType(true);
        B6R8b4.setPanel(blok561);
        B6R8b4.setTextfield(B6R8b5);
        jLayeredPane1.add(B6R8b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 1340, 50, 30));

        B6R8b3.setLength(2);
        B6R8b3.setNextType(true);
        B6R8b3.setPanel(blok561);
        B6R8b3.setTextNew("<Not Set>");
        B6R8b3.setTextfield(B6R8b4);
        jLayeredPane1.add(B6R8b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 1340, 50, 30));

        B6R8b6.setLength(2);
        B6R8b6.setNextType(true);
        B6R8b6.setPanel(blok561);
        B6R8b6.setTextfield(B6R8b8);
        jLayeredPane1.add(B6R8b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 1340, 50, 30));

        B6R8bJuml.setLength(2);
        B6R8bJuml.setNextType(true);
        B6R8bJuml.setPanel(blok561);
        B6R8bJuml.setTextfield(B6R9a);
        jLayeredPane1.add(B6R8bJuml, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 1340, 50, 30));

        B6R8b5.setLength(2);
        B6R8b5.setNextType(true);
        B6R8b5.setPanel(blok561);
        B6R8b5.setTextfield(B6R8b6);
        jLayeredPane1.add(B6R8b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 1340, 50, 30));

        B6R9a.setNextType(true);
        B6R9a.setPanel(blok561);
        B6R9a.setTextfield(B6R9b);
        jLayeredPane1.add(B6R9a, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 1455, 35, 30));

        B6R10.setPanel(blok561);
        jLayeredPane1.add(B6R10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 1655, 35, 30));

        B5R17b.setNextType(true);
        B5R17b.setPanel(blok561);
        B5R17b.setTextfield(B6R1);
        jLayeredPane1.add(B5R17b, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1555, 35, 30));

        B6R1.setLength(2);
        B6R1.setNextType(true);
        B6R1.setPanel(blok561);
        B6R1.setTextfield(B6R2);
        B6R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6R1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B6R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1655, 35, 30));

        B6R3tdktetap.setCharType('2');
        B6R3tdktetap.setLength(30);
        B6R3tdktetap.setNextType(true);
        B6R3tdktetap.setPanel(this);
        B6R3tdktetap.setTextfield(B6R4a);
        jLayeredPane1.add(B6R3tdktetap, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 640, 250, 25));

        B6R3tetap.setCharType('2');
        B6R3tetap.setLength(30);
        B6R3tetap.setNextType(true);
        B6R3tetap.setPanel(this);
        B6R3tetap.setTextfield(B6R3tdktetap);
        jLayeredPane1.add(B6R3tetap, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 250, 25));

        B6R6lainnya.setLength(2);
        B6R6lainnya.setNextType(true);
        B6R6lainnya.setPanel(this);
        B6R6lainnya.setTextfield(B6R6lainnya2);
        jLayeredPane1.add(B6R6lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 1010, 35, 30));

        B6R6lainnya2.setCharType('2');
        B6R6lainnya2.setLength(30);
        B6R6lainnya2.setNextType(true);
        B6R6lainnya2.setPanel(this);
        B6R6lainnya2.setTextfield(B6R7a);
        jLayeredPane1.add(B6R6lainnya2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 1030, 200, 25));

        B6R8b8.setLength(2);
        B6R8b8.setNextType(true);
        B6R8b8.setPanel(this);
        B6R8b8.setTextfield(B6R8bJuml);
        jLayeredPane1.add(B6R8b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 1340, 50, 30));

        javax.swing.GroupLayout blok561Layout = new javax.swing.GroupLayout(blok561);
        blok561.setLayout(blok561Layout);
        blok561Layout.setHorizontalGroup(
            blok561Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        blok561Layout.setVerticalGroup(
            blok561Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blok561Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1765, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blok561, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blok561, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void B5R9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R9ActionPerformed

    private void B6R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6R2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B6R2ActionPerformed

    private void B6R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B6R1ActionPerformed

    private void B5R2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_B5R2FocusLost
        // TODO add your handling code here:
       


    }//GEN-LAST:event_B5R2FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl53.component.Textfield B5R10;
    private pkl53.component.Textfield B5R11;
    private pkl53.component.Textfield B5R12;
    private pkl53.component.Textfield B5R13;
    private pkl53.component.Textfield B5R14a;
    private pkl53.component.Textfield B5R14b;
    private pkl53.component.Textfield B5R15;
    private pkl53.component.Textfield B5R16;
    private pkl53.component.Textfield B5R17a;
    private pkl53.component.Textfield B5R17b;
    private pkl53.component.Textfield B5R1Art;
    private static pkl53.component.Textfield B5R1Nama;
    private pkl53.component.Textfield B5R2;
    private pkl53.component.Textfield B5R3;
    private pkl53.component.Textfield B5R4;
    private pkl53.component.Textfield B5R5;
    private pkl53.component.Textfield B5R6Kab;
    private pkl53.component.Textfield B5R6Prop;
    private pkl53.component.Textfield B5R7Kab;
    private pkl53.component.Textfield B5R7Prop;
    private pkl53.component.Textfield B5R8;
    private pkl53.component.Textfield B5R9;
    private pkl53.component.Textfield B6R1;
    private pkl53.component.Textfield B6R10;
    private pkl53.component.Textfield B6R2;
    private pkl53.component.Textfield B6R3;
    private pkl53.component.Textfield B6R3tdktetap;
    private pkl53.component.Textfield B6R3tetap;
    private pkl53.component.Textfield B6R4a;
    private pkl53.component.Textfield B6R4b;
    private pkl53.component.Textfield B6R5a;
    private pkl53.component.Textfield B6R5b;
    private pkl53.component.Textfield B6R6lainnya;
    private pkl53.component.Textfield B6R6lainnya2;
    private pkl53.component.Textfield B6R6utama;
    private pkl53.component.Textfield B6R7a;
    private pkl53.component.Textfield B6R7b;
    private pkl53.component.Textfield B6R8a;
    private pkl53.component.Textfield B6R8b1;
    private pkl53.component.Textfield B6R8b2;
    private pkl53.component.Textfield B6R8b3;
    private pkl53.component.Textfield B6R8b4;
    private pkl53.component.Textfield B6R8b5;
    private pkl53.component.Textfield B6R8b6;
    private pkl53.component.Textfield B6R8b8;
    private pkl53.component.Textfield B6R8bJuml;
    private pkl53.component.Textfield B6R9a;
    private pkl53.component.Textfield B6R9b;
    private pkl53.imageClass.BlokPekerja56 blok561;
    private pkl53.model.tambahan.Blok56BTamabahan blok56BTamabahan;
    private javax.swing.JLayeredPane jLayeredPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the B5R10
     */
    public pkl53.component.Textfield getB5R10() {
        return B5R10;
    }

    /**
     * @param B5R10 the B5R10 to set
     */
    public void setB5R10(pkl53.component.Textfield B5R10) {
        this.B5R10 = B5R10;
    }

    /**
     * @return the B5R11
     */
    public pkl53.component.Textfield getB5R11() {
        return B5R11;
    }

    /**
     * @param B5R11 the B5R11 to set
     */
    public void setB5R11(pkl53.component.Textfield B5R11) {
        this.B5R11 = B5R11;
    }

    /**
     * @return the B5R12
     */
    public pkl53.component.Textfield getB5R12() {
        return B5R12;
    }

    /**
     * @param B5R12 the B5R12 to set
     */
    public void setB5R12(pkl53.component.Textfield B5R12) {
        this.B5R12 = B5R12;
    }

    /**
     * @return the B5R13
     */
    public pkl53.component.Textfield getB5R13() {
        return B5R13;
    }

    /**
     * @param B5R13 the B5R13 to set
     */
    public void setB5R13(pkl53.component.Textfield B5R13) {
        this.B5R13 = B5R13;
    }

    /**
     * @return the B5R14a
     */
    public pkl53.component.Textfield getB5R14a() {
        return B5R14a;
    }

    /**
     * @param B5R14a the B5R14a to set
     */
    public void setB5R14a(pkl53.component.Textfield B5R14a) {
        this.B5R14a = B5R14a;
    }

    /**
     * @return the B5R14b
     */
    public pkl53.component.Textfield getB5R14b() {
        return B5R14b;
    }

    /**
     * @param B5R14b the B5R14b to set
     */
    public void setB5R14b(pkl53.component.Textfield B5R14b) {
        this.B5R14b = B5R14b;
    }

    /**
     * @return the B5R15
     */
    public pkl53.component.Textfield getB5R15() {
        return B5R15;
    }

    /**
     * @param B5R15 the B5R15 to set
     */
    public void setB5R15(pkl53.component.Textfield B5R15) {
        this.B5R15 = B5R15;
    }

    /**
     * @return the B5R16
     */
    public pkl53.component.Textfield getB5R16() {
        return B5R16;
    }

    /**
     * @param B5R16 the B5R16 to set
     */
    public void setB5R16(pkl53.component.Textfield B5R16) {
        this.B5R16 = B5R16;
    }

    /**
     * @return the B5R17a
     */
    public pkl53.component.Textfield getB5R17a() {
        return B5R17a;
    }

    /**
     * @param B5R17a the B5R17a to set
     */
    public void setB5R17a(pkl53.component.Textfield B5R17a) {
        this.B5R17a = B5R17a;
    }

    /**
     * @return the B5R17b
     */
    public pkl53.component.Textfield getB5R17b() {
        return B5R17b;
    }

    /**
     * @param B5R17b the B5R17b to set
     */
    public void setB5R17b(pkl53.component.Textfield B5R17b) {
        this.B5R17b = B5R17b;
    }

    /**
     * @return the B5R1Art
     */
    public pkl53.component.Textfield getB5R1Art() {
        return B5R1Art;
    }

    /**
     * @param B5R1Art the B5R1Art to set
     */
    public void setB5R1Art(pkl53.component.Textfield B5R1Art) {
        this.B5R1Art = B5R1Art;
    }

    /**
     * @return the B5R1Nama
     */
    public static pkl53.component.Textfield getB5R1Nama() {
        return B5R1Nama;
    }

    /**
     * @param B5R1Nama the B5R1Nama to set
     */
    public void setB5R1Nama(pkl53.component.Textfield B5R1Nama) {
        this.B5R1Nama = B5R1Nama;
    }

    /**
     * @return the B5R2
     */
    public pkl53.component.Textfield getB5R2() {
        return B5R2;
    }

    /**
     * @param B5R2 the B5R2 to set
     */
    public void setB5R2(pkl53.component.Textfield B5R2) {
        this.B5R2 = B5R2;
    }

    /**
     * @return the B5R3
     */
    public pkl53.component.Textfield getB5R3() {
        return B5R3;
    }

    /**
     * @param B5R3 the B5R3 to set
     */
    public void setB5R3(pkl53.component.Textfield B5R3) {
        this.B5R3 = B5R3;
    }

    /**
     * @return the B5R4
     */
    public pkl53.component.Textfield getB5R4() {
        return B5R4;
    }

    /**
     * @param B5R4 the B5R4 to set
     */
    public void setB5R4(pkl53.component.Textfield B5R4) {
        this.B5R4 = B5R4;
    }

    /**
     * @return the B5R5
     */
    public pkl53.component.Textfield getB5R5() {
        return B5R5;
    }

    /**
     * @param B5R5 the B5R5 to set
     */
    public void setB5R5(pkl53.component.Textfield B5R5) {
        this.B5R5 = B5R5;
    }

    /**
     * @return the B5R6Kab
     */
    public pkl53.component.Textfield getB5R6Kab() {
        return B5R6Kab;
    }

    /**
     * @param B5R6Kab the B5R6Kab to set
     */
    public void setB5R6Kab(pkl53.component.Textfield B5R6Kab) {
        this.B5R6Kab = B5R6Kab;
    }

    /**
     * @return the B5R6Prop
     */
    public pkl53.component.Textfield getB5R6Prop() {
        return B5R6Prop;
    }

    /**
     * @param B5R6Prop the B5R6Prop to set
     */
    public void setB5R6Prop(pkl53.component.Textfield B5R6Prop) {
        this.B5R6Prop = B5R6Prop;
    }

    /**
     * @return the B5R7Kab
     */
    public pkl53.component.Textfield getB5R7Kab() {
        return B5R7Kab;
    }

    /**
     * @param B5R7Kab the B5R7Kab to set
     */
    public void setB5R7Kab(pkl53.component.Textfield B5R7Kab) {
        this.B5R7Kab = B5R7Kab;
    }

    /**
     * @return the B5R7Prop
     */
    public pkl53.component.Textfield getB5R7Prop() {
        return B5R7Prop;
    }

    /**
     * @param B5R7Prop the B5R7Prop to set
     */
    public void setB5R7Prop(pkl53.component.Textfield B5R7Prop) {
        this.B5R7Prop = B5R7Prop;
    }

    /**
     * @return the B5R8
     */
    public pkl53.component.Textfield getB5R8() {
        return B5R8;
    }

    /**
     * @param B5R8 the B5R8 to set
     */
    public void setB5R8(pkl53.component.Textfield B5R8) {
        this.B5R8 = B5R8;
    }

    /**
     * @return the B5R9
     */
    public pkl53.component.Textfield getB5R9() {
        return B5R9;
    }

    /**
     * @param B5R9 the B5R9 to set
     */
    public void setB5R9(pkl53.component.Textfield B5R9) {
        this.B5R9 = B5R9;
    }

    /**
     * @return the B6R1
     */
    public pkl53.component.Textfield getB6R1() {
        return B6R1;
    }

    /**
     * @param B6R1 the B6R1 to set
     */
    public void setB6R1(pkl53.component.Textfield B6R1) {
        this.B6R1 = B6R1;
    }

    /**
     * @return the B6R10
     */
    public pkl53.component.Textfield getB6R10() {
        return B6R10;
    }

    /**
     * @param B6R10 the B6R10 to set
     */
    public void setB6R10(pkl53.component.Textfield B6R10) {
        this.B6R10 = B6R10;
    }

    /**
     * @return the B6R2
     */
    public pkl53.component.Textfield getB6R2() {
        return B6R2;
    }

    /**
     * @param B6R2 the B6R2 to set
     */
    public void setB6R2(pkl53.component.Textfield B6R2) {
        this.B6R2 = B6R2;
    }

    /**
     * @return the B6R3
     */
    public pkl53.component.Textfield getB6R3() {
        return B6R3;
    }

    /**
     * @param B6R3 the B6R3 to set
     */
    public void setB6R3(pkl53.component.Textfield B6R3) {
        this.B6R3 = B6R3;
    }

    /**
     * @return the B6R3tdktetap
     */
    public pkl53.component.Textfield getB6R3tdktetap() {
        return B6R3tdktetap;
    }

    /**
     * @param B6R3tdktetap the B6R3tdktetap to set
     */
    public void setB6R3tdktetap(pkl53.component.Textfield B6R3tdktetap) {
        this.B6R3tdktetap = B6R3tdktetap;
    }

    /**
     * @return the B6R3tetap
     */
    public pkl53.component.Textfield getB6R3tetap() {
        return B6R3tetap;
    }

    /**
     * @param B6R3tetap the B6R3tetap to set
     */
    public void setB6R3tetap(pkl53.component.Textfield B6R3tetap) {
        this.B6R3tetap = B6R3tetap;
    }

    /**
     * @return the B6R4a
     */
    public pkl53.component.Textfield getB6R4a() {
        return B6R4a;
    }

    /**
     * @param B6R4a the B6R4a to set
     */
    public void setB6R4a(pkl53.component.Textfield B6R4a) {
        this.B6R4a = B6R4a;
    }

    /**
     * @return the B6R4b
     */
    public pkl53.component.Textfield getB6R4b() {
        return B6R4b;
    }

    /**
     * @param B6R4b the B6R4b to set
     */
    public void setB6R4b(pkl53.component.Textfield B6R4b) {
        this.B6R4b = B6R4b;
    }

    /**
     * @return the B6R5a
     */
    public pkl53.component.Textfield getB6R5a() {
        return B6R5a;
    }

    /**
     * @param B6R5a the B6R5a to set
     */
    public void setB6R5a(pkl53.component.Textfield B6R5a) {
        this.B6R5a = B6R5a;
    }

    /**
     * @return the B6R5b
     */
    public pkl53.component.Textfield getB6R5b() {
        return B6R5b;
    }

    /**
     * @param B6R5b the B6R5b to set
     */
    public void setB6R5b(pkl53.component.Textfield B6R5b) {
        this.B6R5b = B6R5b;
    }

    /**
     * @return the B6R6lainnya
     */
    public pkl53.component.Textfield getB6R6lainnya() {
        return B6R6lainnya;
    }

    /**
     * @param B6R6lainnya the B6R6lainnya to set
     */
    public void setB6R6lainnya(pkl53.component.Textfield B6R6lainnya) {
        this.B6R6lainnya = B6R6lainnya;
    }

    /**
     * @return the B6R6lainnya2
     */
    public pkl53.component.Textfield getB6R6lainnya2() {
        return B6R6lainnya2;
    }

    /**
     * @param B6R6lainnya2 the B6R6lainnya2 to set
     */
    public void setB6R6lainnya2(pkl53.component.Textfield B6R6lainnya2) {
        this.B6R6lainnya2 = B6R6lainnya2;
    }

    /**
     * @return the B6R6utama
     */
    public pkl53.component.Textfield getB6R6utama() {
        return B6R6utama;
    }

    /**
     * @param B6R6utama the B6R6utama to set
     */
    public void setB6R6utama(pkl53.component.Textfield B6R6utama) {
        this.B6R6utama = B6R6utama;
    }

    /**
     * @return the B6R7a
     */
    public pkl53.component.Textfield getB6R7a() {
        return B6R7a;
    }

    /**
     * @param B6R7a the B6R7a to set
     */
    public void setB6R7a(pkl53.component.Textfield B6R7a) {
        this.B6R7a = B6R7a;
    }

    /**
     * @return the B6R7b
     */
    public pkl53.component.Textfield getB6R7b() {
        return B6R7b;
    }

    /**
     * @param B6R7b the B6R7b to set
     */
    public void setB6R7b(pkl53.component.Textfield B6R7b) {
        this.B6R7b = B6R7b;
    }

    /**
     * @return the B6R8a
     */
    public pkl53.component.Textfield getB6R8a() {
        return B6R8a;
    }

    /**
     * @param B6R8a the B6R8a to set
     */
    public void setB6R8a(pkl53.component.Textfield B6R8a) {
        this.B6R8a = B6R8a;
    }

    /**
     * @return the B6R8b1
     */
    public pkl53.component.Textfield getB6R8b1() {
        return B6R8b1;
    }

    /**
     * @param B6R8b1 the B6R8b1 to set
     */
    public void setB6R8b1(pkl53.component.Textfield B6R8b1) {
        this.B6R8b1 = B6R8b1;
    }

    /**
     * @return the B6R8b2
     */
    public pkl53.component.Textfield getB6R8b2() {
        return B6R8b2;
    }

    /**
     * @param B6R8b2 the B6R8b2 to set
     */
    public void setB6R8b2(pkl53.component.Textfield B6R8b2) {
        this.B6R8b2 = B6R8b2;
    }

    /**
     * @return the B6R8b3
     */
    public pkl53.component.Textfield getB6R8b3() {
        return B6R8b3;
    }

    /**
     * @param B6R8b3 the B6R8b3 to set
     */
    public void setB6R8b3(pkl53.component.Textfield B6R8b3) {
        this.B6R8b3 = B6R8b3;
    }

    /**
     * @return the B6R8b4
     */
    public pkl53.component.Textfield getB6R8b4() {
        return B6R8b4;
    }

    /**
     * @param B6R8b4 the B6R8b4 to set
     */
    public void setB6R8b4(pkl53.component.Textfield B6R8b4) {
        this.B6R8b4 = B6R8b4;
    }

    /**
     * @return the B6R8b5
     */
    public pkl53.component.Textfield getB6R8b5() {
        return B6R8b5;
    }

    /**
     * @param B6R8b5 the B6R8b5 to set
     */
    public void setB6R8b5(pkl53.component.Textfield B6R8b5) {
        this.B6R8b5 = B6R8b5;
    }

    /**
     * @return the B6R8b6
     */
    public pkl53.component.Textfield getB6R8b6() {
        return B6R8b6;
    }

    /**
     * @param B6R8b6 the B6R8b6 to set
     */
    public void setB6R8b6(pkl53.component.Textfield B6R8b6) {
        this.B6R8b6 = B6R8b6;
    }

    /**
     * @return the B6R8b8
     */
    public pkl53.component.Textfield getB6R8b8() {
        return B6R8b8;
    }

    /**
     * @param B6R8b8 the B6R8b8 to set
     */
    public void setB6R8b8(pkl53.component.Textfield B6R8b8) {
        this.B6R8b8 = B6R8b8;
    }

    /**
     * @return the B6R8bJuml
     */
    public pkl53.component.Textfield getB6R8bJuml() {
        return B6R8bJuml;
    }

    /**
     * @param B6R8bJuml the B6R8bJuml to set
     */
    public void setB6R8bJuml(pkl53.component.Textfield B6R8bJuml) {
        this.B6R8bJuml = B6R8bJuml;
    }

    /**
     * @return the B6R9a
     */
    public pkl53.component.Textfield getB6R9a() {
        return B6R9a;
    }

    /**
     * @param B6R9a the B6R9a to set
     */
    public void setB6R9a(pkl53.component.Textfield B6R9a) {
        this.B6R9a = B6R9a;
    }

    /**
     * @return the B6R9b
     */
    public pkl53.component.Textfield getB6R9b() {
        return B6R9b;
    }

    /**
     * @param B6R9b the B6R9b to set
     */
    public void setB6R9b(pkl53.component.Textfield B6R9b) {
        this.B6R9b = B6R9b;
    }

    /**
     * @return the blok561
     */
    public pkl53.imageClass.BlokPekerja56 getBlok561() {
        return blok561;
    }

    /**
     * @param blok561 the blok561 to set
     */
    public void setBlok561(pkl53.imageClass.BlokPekerja56 blok561) {
        this.blok561 = blok561;
    }

    /**
     * @return the blok56BTamabahan
     */
    public pkl53.model.tambahan.Blok56BTamabahan getBlok56BTamabahan() {
        return blok56BTamabahan;
    }

    /**
     * @param blok56BTamabahan the blok56BTamabahan to set
     */
    public void setBlok56BTamabahan(pkl53.model.tambahan.Blok56BTamabahan blok56BTamabahan) {
        this.blok56BTamabahan = blok56BTamabahan;
    }

}
