/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkl53.view;

import java.util.ArrayList;
import java.util.List;
import pkl53.component.Textfield;
import pkl53.validasi.UsahaBlok5AValidasi;

/**
 *
 * @author YOPPY
 */
public class BlokUsaha5 extends javax.swing.JPanel {

    private BlokUsaha5B blokUsaha5B;
    private ArrayList<Textfield> listTextFieldBlokUsaha5 = new ArrayList<Textfield>();
    /**
     * Creates new form blok123
     */
    public BlokUsaha5() {
        initComponents();
        addListTextfield();
        UsahaBlok5AValidasi val = new UsahaBlok5AValidasi();
        val.setPanelUsahaBlok5A(this);
        val.registerValidasi();
        val.setListB5AUsaha();
        
    }
    
    public List<Textfield> getListTextFieldBlokUsaha5() {
        return listTextFieldBlokUsaha5;
    }
    
     public void addListTextfield() {
         //50 textfield
         listTextFieldBlokUsaha5.add(B5R1NAMA);
         listTextFieldBlokUsaha5.add(B5R1NOART);
         listTextFieldBlokUsaha5.add(B5R2);
         listTextFieldBlokUsaha5.add(B5R3);
         listTextFieldBlokUsaha5.add(B5R4BULAN);
         listTextFieldBlokUsaha5.add(B5R4TAHUN);
         listTextFieldBlokUsaha5.add(B5R5);
         listTextFieldBlokUsaha5.add(B5R5_10_LAIN);
         listTextFieldBlokUsaha5.add(B5R5_13_LAIN);
         listTextFieldBlokUsaha5.add(B5R6);
         listTextFieldBlokUsaha5.add(B5R7);
         listTextFieldBlokUsaha5.add(B5R7DIBAYAR);
         listTextFieldBlokUsaha5.add(B5R8);
         listTextFieldBlokUsaha5.add(B5R9);
         listTextFieldBlokUsaha5.add(B5R10);
         listTextFieldBlokUsaha5.add(B5R11A);
         listTextFieldBlokUsaha5.add(B5R11B);
         listTextFieldBlokUsaha5.add(B5R11C);
         listTextFieldBlokUsaha5.add(B5R11D);
         listTextFieldBlokUsaha5.add(B5R11E_LAIN);
         listTextFieldBlokUsaha5.add(B5R12A);
         listTextFieldBlokUsaha5.add(B5R12B);
         listTextFieldBlokUsaha5.add(B5R12C);
         listTextFieldBlokUsaha5.add(B5R12D);
         listTextFieldBlokUsaha5.add(B5R12JUML);
         listTextFieldBlokUsaha5.add(B5R13HARI_AGT);
         listTextFieldBlokUsaha5.add(B5R13HARI_APR);
         listTextFieldBlokUsaha5.add(B5R13HARI_DES);
         listTextFieldBlokUsaha5.add(B5R13HARI_FEB);
         listTextFieldBlokUsaha5.add(B5R13HARI_JAN);
         listTextFieldBlokUsaha5.add(B5R13HARI_JUL);
         listTextFieldBlokUsaha5.add(B5R13HARI_JUN);
         listTextFieldBlokUsaha5.add(B5R13HARI_MAR);
         listTextFieldBlokUsaha5.add(B5R13HARI_MEI);
         listTextFieldBlokUsaha5.add(B5R13HARI_NOV);
         listTextFieldBlokUsaha5.add(B5R13HARI_OKT);
         listTextFieldBlokUsaha5.add(B5R13HARI_SEP);
         listTextFieldBlokUsaha5.add(B5R13KODE_AGT);
         listTextFieldBlokUsaha5.add(B5R13KODE_APR);
         listTextFieldBlokUsaha5.add(B5R13KODE_DES);
         listTextFieldBlokUsaha5.add(B5R13KODE_FEB);
         listTextFieldBlokUsaha5.add(B5R13KODE_JAN);
         listTextFieldBlokUsaha5.add(B5R13KODE_JUL);
         listTextFieldBlokUsaha5.add(B5R13KODE_JUN);
         listTextFieldBlokUsaha5.add(B5R13KODE_MAR);
         listTextFieldBlokUsaha5.add(B5R13KODE_MEI);
         listTextFieldBlokUsaha5.add(B5R13KODE_NOV);
         listTextFieldBlokUsaha5.add(B5R13KODE_OKT);
         listTextFieldBlokUsaha5.add(B5R13KODE_SEP);
         listTextFieldBlokUsaha5.add(B5R14);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        b3RinciusahaTambahan1 = new pkl53.model.tambahan.B3RinciusahaTambahan();
        blok56Usaha1 = new pkl53.imageClass.BlokUsaha5();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        B5R1NOART = new pkl53.component.Textfield();
        B5R2 = new pkl53.component.Textfield();
        B5R3 = new pkl53.component.Textfield();
        B5R4BULAN = new pkl53.component.Textfield();
        B5R4TAHUN = new pkl53.component.Textfield();
        B5R5 = new pkl53.component.Textfield();
        B5R5_10_LAIN = new pkl53.component.Textfield();
        B5R5_13_LAIN = new pkl53.component.Textfield();
        B5R6 = new pkl53.component.Textfield();
        B5R7 = new pkl53.component.Textfield();
        B5R7DIBAYAR = new pkl53.component.Textfield();
        B5R8 = new pkl53.component.Textfield();
        B5R9 = new pkl53.component.Textfield();
        B5R10 = new pkl53.component.Textfield();
        B5R11A = new pkl53.component.Textfield();
        B5R11B = new pkl53.component.Textfield();
        B5R11C = new pkl53.component.Textfield();
        B5R11D = new pkl53.component.Textfield();
        B5R11E_LAIN = new pkl53.component.Textfield();
        B5R12A = new pkl53.component.Textfield();
        B5R12B = new pkl53.component.Textfield();
        B5R12C = new pkl53.component.Textfield();
        B5R12D = new pkl53.component.Textfield();
        B5R12JUML = new pkl53.component.Textfield();
        B5R13HARI_APR = new pkl53.component.Textfield();
        B5R13HARI_MEI = new pkl53.component.Textfield();
        B5R13HARI_JUN = new pkl53.component.Textfield();
        B5R13HARI_JUL = new pkl53.component.Textfield();
        B5R13HARI_AGT = new pkl53.component.Textfield();
        B5R13HARI_SEP = new pkl53.component.Textfield();
        B5R13HARI_OKT = new pkl53.component.Textfield();
        B5R13HARI_NOV = new pkl53.component.Textfield();
        B5R13HARI_DES = new pkl53.component.Textfield();
        B5R13HARI_JAN = new pkl53.component.Textfield();
        B5R13HARI_FEB = new pkl53.component.Textfield();
        B5R13HARI_MAR = new pkl53.component.Textfield();
        B5R13KODE_APR = new pkl53.component.Textfield();
        B5R13KODE_MEI = new pkl53.component.Textfield();
        B5R13KODE_JUN = new pkl53.component.Textfield();
        B5R13KODE_JUL = new pkl53.component.Textfield();
        B5R13KODE_AGT = new pkl53.component.Textfield();
        B5R13KODE_SEP = new pkl53.component.Textfield();
        B5R13KODE_OKT = new pkl53.component.Textfield();
        B5R13KODE_NOV = new pkl53.component.Textfield();
        B5R13KODE_DES = new pkl53.component.Textfield();
        B5R13KODE_JAN = new pkl53.component.Textfield();
        B5R13KODE_FEB = new pkl53.component.Textfield();
        B5R13KODE_MAR = new pkl53.component.Textfield();
        B5R14 = new pkl53.component.Textfield();
        B5R1NAMA = new pkl53.component.Textfield();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R10, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R10"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R11A, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R11A"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R11B, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R11B"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R11C, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R11C"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R11D, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R11D"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R11E_LAIN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R11E_LAIN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R12A, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R12A"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R12B, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R12B"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R12C, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R12C"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R12D, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R12D"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R12JUML, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R12JUML"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_AGT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_AGT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_APR, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_APR"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_DES, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_DES"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_FEB, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_FEB"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_JAN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_JAN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_JUL, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_JUL"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_JUN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_JUN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_MAR, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_MAR"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_MEI, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_MEI"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_NOV, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_NOV"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_OKT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_OKT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13HARI_SEP, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13HARI_SEP"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_AGT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_AGT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_APR, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_APR"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_DES, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_DES"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_FEB, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_FEB"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_JAN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_JAN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_JUL, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_JUL"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_JUN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_JUN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_MAR, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_MAR"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_MEI, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_MEI"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_NOV, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_NOV"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_OKT, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_OKT"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R13KODE_SEP, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R13KODE_SEP"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R14, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R14"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R1NAMA, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R1NAMA"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R1NOART, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R1NOART"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R2, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R2"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R3, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R3"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R4BULAN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R4BULAN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R4TAHUN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R4TAHUN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R5, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R5"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R5_10_LAIN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R5_10_LAIN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R5_13_LAIN, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R5_13_LAIN"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R6, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R6"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R7, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R7"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R7DIBAYAR, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R7DIBAYAR"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R8, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R8"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, B5R9, org.jdesktop.beansbinding.ELProperty.create("${text}"), b3RinciusahaTambahan1, org.jdesktop.beansbinding.BeanProperty.create("b5R9"));
        bindingGroup.addBinding(binding);

        setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B5R1NOART.setNextType(true);
        B5R1NOART.setPanel(blok56Usaha1);
        B5R1NOART.setTextfield(B5R2);
        B5R1NOART.setTextfieldKhusus(true);
        jLayeredPane1.add(B5R1NOART, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 40, 30));

        B5R2.setLength(2);
        B5R2.setNextType(true);
        B5R2.setPanel(blok56Usaha1);
        B5R2.setTextfield(B5R3);
        jLayeredPane1.add(B5R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 40, 30));

        B5R3.setLength(2);
        B5R3.setNextType(true);
        B5R3.setPanel(blok56Usaha1);
        B5R3.setTextfield(B5R4BULAN);
        jLayeredPane1.add(B5R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 40, 30));

        B5R4BULAN.setLength(2);
        B5R4BULAN.setNextType(true);
        B5R4BULAN.setPanel(blok56Usaha1);
        B5R4BULAN.setTextfield(B5R4TAHUN);
        B5R4BULAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R4BULANActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R4BULAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 50, 30));

        B5R4TAHUN.setLength(4);
        B5R4TAHUN.setNextType(true);
        B5R4TAHUN.setPanel(blok56Usaha1);
        B5R4TAHUN.setTextfield(B5R5);
        jLayeredPane1.add(B5R4TAHUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 90, 30));

        B5R5.setLength(2);
        B5R5.setNextType(true);
        B5R5.setPanel(blok56Usaha1);
        B5R5.setTextfield(B5R5_10_LAIN);
        jLayeredPane1.add(B5R5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 40, 30));

        B5R5_10_LAIN.setCharType('2');
        B5R5_10_LAIN.setLength(30);
        B5R5_10_LAIN.setNextType(true);
        B5R5_10_LAIN.setPanel(blok56Usaha1);
        B5R5_10_LAIN.setTextfield(B5R5_13_LAIN);
        B5R5_10_LAIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R5_10_LAINActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R5_10_LAIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 780, 220, 30));

        B5R5_13_LAIN.setCharType('2');
        B5R5_13_LAIN.setLength(30);
        B5R5_13_LAIN.setNextType(true);
        B5R5_13_LAIN.setPanel(blok56Usaha1);
        B5R5_13_LAIN.setTextfield(B5R6);
        B5R5_13_LAIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R5_13_LAINActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R5_13_LAIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 900, 200, 30));

        B5R6.setNextType(true);
        B5R6.setPanel(blok56Usaha1);
        B5R6.setTextfield(B5R7);
        B5R6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R6ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 990, 30, 30));

        B5R7.setLength(3);
        B5R7.setNextType(true);
        B5R7.setPanel(blok56Usaha1);
        B5R7.setTextfield(B5R7DIBAYAR);
        B5R7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                B5R7FocusLost(evt);
            }
        });
        B5R7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R7ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1170, 50, 30));

        B5R7DIBAYAR.setLength(3);
        B5R7DIBAYAR.setNextType(true);
        B5R7DIBAYAR.setPanel(blok56Usaha1);
        B5R7DIBAYAR.setTextfield(B5R8);
        B5R7DIBAYAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R7DIBAYARActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R7DIBAYAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1210, 50, 30));

        B5R8.setLength(2);
        B5R8.setNextType(true);
        B5R8.setPanel(blok56Usaha1);
        B5R8.setTextfield(B5R9);
        B5R8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R8ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1290, 50, 30));

        B5R9.setLength(2);
        B5R9.setNextType(true);
        B5R9.setPanel(blok56Usaha1);
        B5R9.setTextfield(B5R10);
        B5R9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R9ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1360, 50, 30));

        B5R10.setNextType(true);
        B5R10.setPanel(blok56Usaha1);
        B5R10.setTextfield(B5R11A);
        B5R10.setTextfieldKhusus(true);
        B5R10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R10ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, 30, 30));

        B5R11A.setNextType(true);
        B5R11A.setPanel(blok56Usaha1);
        B5R11A.setTextfield(B5R11B);
        B5R11A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R11AActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R11A, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 440, 30, 30));

        B5R11B.setNextType(true);
        B5R11B.setPanel(blok56Usaha1);
        B5R11B.setTextfield(B5R11C);
        B5R11B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R11BActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R11B, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 470, 30, 30));

        B5R11C.setNextType(true);
        B5R11C.setPanel(blok56Usaha1);
        B5R11C.setTextfield(B5R11D);
        B5R11C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R11CActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R11C, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, 30, 30));

        B5R11D.setNextType(true);
        B5R11D.setPanel(blok56Usaha1);
        B5R11D.setTextfield(B5R11E_LAIN);
        B5R11D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R11DActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R11D, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 530, 30, 30));

        B5R11E_LAIN.setCharType('2');
        B5R11E_LAIN.setLength(30);
        B5R11E_LAIN.setNextType(true);
        B5R11E_LAIN.setPanel(blok56Usaha1);
        B5R11E_LAIN.setTextfield(B5R12A);
        B5R11E_LAIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R11E_LAINActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R11E_LAIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 585, 340, 27));

        B5R12A.setLength(9);
        B5R12A.setNextType(true);
        B5R12A.setPanel(blok56Usaha1);
        B5R12A.setTextfield(B5R12B);
        B5R12A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R12AActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R12A, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 690, 160, 30));

        B5R12B.setLength(9);
        B5R12B.setNextType(true);
        B5R12B.setPanel(blok56Usaha1);
        B5R12B.setTextfield(B5R12C);
        B5R12B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R12BActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R12B, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 720, 160, 30));

        B5R12C.setLength(9);
        B5R12C.setNextType(true);
        B5R12C.setPanel(blok56Usaha1);
        B5R12C.setTextfield(B5R12D);
        B5R12C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R12CActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R12C, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 750, 160, 30));

        B5R12D.setLength(9);
        B5R12D.setNextType(true);
        B5R12D.setPanel(blok56Usaha1);
        B5R12D.setTextfield(B5R12JUML);
        B5R12D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R12DActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R12D, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 780, 160, 30));

        B5R12JUML.setLength(9);
        B5R12JUML.setNextType(true);
        B5R12JUML.setPanel(blok56Usaha1);
        B5R12JUML.setTextfield(B5R13HARI_APR);
        B5R12JUML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R12JUMLActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R12JUML, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 820, 160, 30));

        B5R13HARI_APR.setLength(2);
        B5R13HARI_APR.setNextType(true);
        B5R13HARI_APR.setPanel(blok56Usaha1);
        B5R13HARI_APR.setTextfield(B5R13HARI_MEI);
        B5R13HARI_APR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_APRActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_APR, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 988, 40, 30));

        B5R13HARI_MEI.setLength(2);
        B5R13HARI_MEI.setNextType(true);
        B5R13HARI_MEI.setPanel(blok56Usaha1);
        B5R13HARI_MEI.setTextfield(B5R13HARI_JUN);
        B5R13HARI_MEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_MEIActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_MEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 988, 40, 30));

        B5R13HARI_JUN.setLength(2);
        B5R13HARI_JUN.setNextType(true);
        B5R13HARI_JUN.setPanel(blok56Usaha1);
        B5R13HARI_JUN.setTextfield(B5R13HARI_JUL);
        B5R13HARI_JUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_JUNActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_JUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 988, 40, 30));

        B5R13HARI_JUL.setLength(2);
        B5R13HARI_JUL.setNextType(true);
        B5R13HARI_JUL.setPanel(blok56Usaha1);
        B5R13HARI_JUL.setTextfield(B5R13HARI_AGT);
        B5R13HARI_JUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_JULActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_JUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 988, 40, 30));

        B5R13HARI_AGT.setLength(2);
        B5R13HARI_AGT.setNextType(true);
        B5R13HARI_AGT.setPanel(blok56Usaha1);
        B5R13HARI_AGT.setTextfield(B5R13HARI_SEP);
        B5R13HARI_AGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_AGTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_AGT, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 988, 40, 30));

        B5R13HARI_SEP.setLength(2);
        B5R13HARI_SEP.setNextType(true);
        B5R13HARI_SEP.setPanel(blok56Usaha1);
        B5R13HARI_SEP.setTextfield(B5R13KODE_APR);
        B5R13HARI_SEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_SEPActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_SEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 988, 40, 30));

        B5R13HARI_OKT.setLength(2);
        B5R13HARI_OKT.setNextType(true);
        B5R13HARI_OKT.setPanel(blok56Usaha1);
        B5R13HARI_OKT.setTextfield(B5R13HARI_NOV);
        B5R13HARI_OKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_OKTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_OKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 1127, 40, 30));

        B5R13HARI_NOV.setLength(2);
        B5R13HARI_NOV.setNextType(true);
        B5R13HARI_NOV.setPanel(blok56Usaha1);
        B5R13HARI_NOV.setTextfield(B5R13HARI_DES);
        B5R13HARI_NOV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_NOVActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_NOV, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 1127, 40, 30));

        B5R13HARI_DES.setLength(2);
        B5R13HARI_DES.setNextType(true);
        B5R13HARI_DES.setPanel(blok56Usaha1);
        B5R13HARI_DES.setTextfield(B5R13HARI_JAN);
        B5R13HARI_DES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_DESActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_DES, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 1127, 40, 30));

        B5R13HARI_JAN.setLength(2);
        B5R13HARI_JAN.setNextType(true);
        B5R13HARI_JAN.setPanel(blok56Usaha1);
        B5R13HARI_JAN.setTextfield(B5R13HARI_FEB);
        B5R13HARI_JAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_JANActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_JAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 1127, 40, 30));

        B5R13HARI_FEB.setLength(2);
        B5R13HARI_FEB.setNextType(true);
        B5R13HARI_FEB.setPanel(blok56Usaha1);
        B5R13HARI_FEB.setTextfield(B5R13HARI_MAR);
        B5R13HARI_FEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_FEBActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_FEB, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 1127, 40, 30));

        B5R13HARI_MAR.setLength(2);
        B5R13HARI_MAR.setNextType(true);
        B5R13HARI_MAR.setPanel(blok56Usaha1);
        B5R13HARI_MAR.setTextfield(B5R13KODE_OKT);
        B5R13HARI_MAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13HARI_MARActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13HARI_MAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 1127, 40, 30));

        B5R13KODE_APR.setLength(2);
        B5R13KODE_APR.setNextType(true);
        B5R13KODE_APR.setPanel(blok56Usaha1);
        B5R13KODE_APR.setTextfield(B5R13KODE_MEI);
        B5R13KODE_APR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_APRActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_APR, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 1027, 40, 30));

        B5R13KODE_MEI.setLength(2);
        B5R13KODE_MEI.setNextType(true);
        B5R13KODE_MEI.setPanel(blok56Usaha1);
        B5R13KODE_MEI.setTextfield(B5R13KODE_JUN);
        B5R13KODE_MEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_MEIActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_MEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 1027, 40, 30));

        B5R13KODE_JUN.setLength(2);
        B5R13KODE_JUN.setNextType(true);
        B5R13KODE_JUN.setPanel(blok56Usaha1);
        B5R13KODE_JUN.setTextfield(B5R13KODE_JUL);
        B5R13KODE_JUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_JUNActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_JUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 1027, 40, 30));

        B5R13KODE_JUL.setLength(2);
        B5R13KODE_JUL.setNextType(true);
        B5R13KODE_JUL.setPanel(blok56Usaha1);
        B5R13KODE_JUL.setTextfield(B5R13KODE_AGT);
        B5R13KODE_JUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_JULActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_JUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 1027, 40, 30));

        B5R13KODE_AGT.setLength(2);
        B5R13KODE_AGT.setNextType(true);
        B5R13KODE_AGT.setPanel(blok56Usaha1);
        B5R13KODE_AGT.setTextfield(B5R13KODE_SEP);
        B5R13KODE_AGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_AGTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_AGT, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 1027, 40, 30));

        B5R13KODE_SEP.setLength(2);
        B5R13KODE_SEP.setNextType(true);
        B5R13KODE_SEP.setPanel(blok56Usaha1);
        B5R13KODE_SEP.setTextfield(B5R13HARI_OKT);
        B5R13KODE_SEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_SEPActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_SEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 1027, 40, 30));

        B5R13KODE_OKT.setLength(2);
        B5R13KODE_OKT.setNextType(true);
        B5R13KODE_OKT.setPanel(blok56Usaha1);
        B5R13KODE_OKT.setTextfield(B5R13KODE_NOV);
        B5R13KODE_OKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_OKTActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_OKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 1167, 40, 30));

        B5R13KODE_NOV.setLength(2);
        B5R13KODE_NOV.setNextType(true);
        B5R13KODE_NOV.setPanel(blok56Usaha1);
        B5R13KODE_NOV.setTextfield(B5R13KODE_DES);
        B5R13KODE_NOV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_NOVActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_NOV, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 1167, 40, 30));

        B5R13KODE_DES.setLength(2);
        B5R13KODE_DES.setNextType(true);
        B5R13KODE_DES.setPanel(blok56Usaha1);
        B5R13KODE_DES.setTextfield(B5R13KODE_JAN);
        B5R13KODE_DES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_DESActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_DES, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 1167, 40, 30));

        B5R13KODE_JAN.setLength(2);
        B5R13KODE_JAN.setNextType(true);
        B5R13KODE_JAN.setPanel(blok56Usaha1);
        B5R13KODE_JAN.setTextfield(B5R13KODE_FEB);
        B5R13KODE_JAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_JANActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_JAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 1167, 40, 30));

        B5R13KODE_FEB.setLength(2);
        B5R13KODE_FEB.setNextType(true);
        B5R13KODE_FEB.setPanel(blok56Usaha1);
        B5R13KODE_FEB.setTextfield(B5R13KODE_MAR);
        B5R13KODE_FEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_FEBActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_FEB, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 1167, 40, 30));

        B5R13KODE_MAR.setLength(2);
        B5R13KODE_MAR.setNextType(true);
        B5R13KODE_MAR.setPanel(blok56Usaha1);
        B5R13KODE_MAR.setTextfield(B5R14);
        B5R13KODE_MAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R13KODE_MARActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R13KODE_MAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 1167, 40, 30));

        B5R14.setLength(9);
        B5R14.setPanel(blok56Usaha1);
        B5R14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5R14ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(B5R14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 1380, 270, 30));

        B5R1NAMA.setCharType('2');
        B5R1NAMA.setLength(30);
        B5R1NAMA.setNextType(true);
        B5R1NAMA.setPanel(blok56Usaha1);
        B5R1NAMA.setTextfield(B5R1NOART);
        B5R1NAMA.setTextfieldKhusus(true);
        jLayeredPane1.add(B5R1NAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 210, 30));

        javax.swing.GroupLayout blok56Usaha1Layout = new javax.swing.GroupLayout(blok56Usaha1);
        blok56Usaha1.setLayout(blok56Usaha1Layout);
        blok56Usaha1Layout.setHorizontalGroup(
            blok56Usaha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blok56Usaha1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        blok56Usaha1Layout.setVerticalGroup(
            blok56Usaha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blok56Usaha1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(blok56Usaha1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void B5R4BULANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R4BULANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R4BULANActionPerformed

    private void B5R6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R6ActionPerformed

    private void B5R7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R7ActionPerformed

    private void B5R7DIBAYARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R7DIBAYARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R7DIBAYARActionPerformed

    private void B5R9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R9ActionPerformed

    private void B5R8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R8ActionPerformed

    private void B5R10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R10ActionPerformed

    private void B5R11AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R11AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R11AActionPerformed

    private void B5R11BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R11BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R11BActionPerformed

    private void B5R11CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R11CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R11CActionPerformed

    private void B5R11DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R11DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R11DActionPerformed

    private void B5R11E_LAINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R11E_LAINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R11E_LAINActionPerformed

    private void B5R12AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R12AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R12AActionPerformed

    private void B5R12BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R12BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R12BActionPerformed

    private void B5R12CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R12CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R12CActionPerformed

    private void B5R12DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R12DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R12DActionPerformed

    private void B5R12JUMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R12JUMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R12JUMLActionPerformed

    private void B5R13KODE_OKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_OKTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_OKTActionPerformed

    private void B5R13KODE_NOVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_NOVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_NOVActionPerformed

    private void B5R13KODE_DESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_DESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_DESActionPerformed

    private void B5R13KODE_JANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_JANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_JANActionPerformed

    private void B5R13KODE_FEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_FEBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_FEBActionPerformed

    private void B5R13KODE_MARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_MARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_MARActionPerformed

    private void B5R13HARI_MARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_MARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_MARActionPerformed

    private void B5R13HARI_FEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_FEBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_FEBActionPerformed

    private void B5R13HARI_JANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_JANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_JANActionPerformed

    private void B5R13HARI_DESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_DESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_DESActionPerformed

    private void B5R13HARI_NOVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_NOVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_NOVActionPerformed

    private void B5R13HARI_OKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_OKTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_OKTActionPerformed

    private void B5R13HARI_MEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_MEIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_MEIActionPerformed

    private void B5R13HARI_APRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_APRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_APRActionPerformed

    private void B5R13HARI_JULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_JULActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_JULActionPerformed

    private void B5R13HARI_AGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_AGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_AGTActionPerformed

    private void B5R13HARI_JUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_JUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_JUNActionPerformed

    private void B5R13HARI_SEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13HARI_SEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13HARI_SEPActionPerformed

    private void B5R13KODE_APRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_APRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_APRActionPerformed

    private void B5R13KODE_MEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_MEIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_MEIActionPerformed

    private void B5R13KODE_JUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_JUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_JUNActionPerformed

    private void B5R13KODE_JULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_JULActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_JULActionPerformed

    private void B5R13KODE_AGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_AGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_AGTActionPerformed

    private void B5R13KODE_SEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R13KODE_SEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R13KODE_SEPActionPerformed

    private void B5R14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R14ActionPerformed

    private void B5R5_13_LAINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R5_13_LAINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R5_13_LAINActionPerformed

    private void B5R5_10_LAINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5R5_10_LAINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5R5_10_LAINActionPerformed

    private void B5R7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_B5R7FocusLost
        
    }//GEN-LAST:event_B5R7FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl53.component.Textfield B5R10;
    private pkl53.component.Textfield B5R11A;
    private pkl53.component.Textfield B5R11B;
    private pkl53.component.Textfield B5R11C;
    private pkl53.component.Textfield B5R11D;
    private pkl53.component.Textfield B5R11E_LAIN;
    private pkl53.component.Textfield B5R12A;
    private pkl53.component.Textfield B5R12B;
    private pkl53.component.Textfield B5R12C;
    private pkl53.component.Textfield B5R12D;
    private pkl53.component.Textfield B5R12JUML;
    private pkl53.component.Textfield B5R13HARI_AGT;
    private pkl53.component.Textfield B5R13HARI_APR;
    private pkl53.component.Textfield B5R13HARI_DES;
    private pkl53.component.Textfield B5R13HARI_FEB;
    private pkl53.component.Textfield B5R13HARI_JAN;
    private pkl53.component.Textfield B5R13HARI_JUL;
    private pkl53.component.Textfield B5R13HARI_JUN;
    private pkl53.component.Textfield B5R13HARI_MAR;
    private pkl53.component.Textfield B5R13HARI_MEI;
    private pkl53.component.Textfield B5R13HARI_NOV;
    private pkl53.component.Textfield B5R13HARI_OKT;
    private pkl53.component.Textfield B5R13HARI_SEP;
    private pkl53.component.Textfield B5R13KODE_AGT;
    private pkl53.component.Textfield B5R13KODE_APR;
    private pkl53.component.Textfield B5R13KODE_DES;
    private pkl53.component.Textfield B5R13KODE_FEB;
    private pkl53.component.Textfield B5R13KODE_JAN;
    private pkl53.component.Textfield B5R13KODE_JUL;
    private pkl53.component.Textfield B5R13KODE_JUN;
    private pkl53.component.Textfield B5R13KODE_MAR;
    private pkl53.component.Textfield B5R13KODE_MEI;
    private pkl53.component.Textfield B5R13KODE_NOV;
    private pkl53.component.Textfield B5R13KODE_OKT;
    private pkl53.component.Textfield B5R13KODE_SEP;
    private pkl53.component.Textfield B5R14;
    private static pkl53.component.Textfield B5R1NAMA;
    private pkl53.component.Textfield B5R1NOART;
    private pkl53.component.Textfield B5R2;
    private pkl53.component.Textfield B5R3;
    private pkl53.component.Textfield B5R4BULAN;
    private pkl53.component.Textfield B5R4TAHUN;
    private pkl53.component.Textfield B5R5;
    private pkl53.component.Textfield B5R5_10_LAIN;
    private pkl53.component.Textfield B5R5_13_LAIN;
    private pkl53.component.Textfield B5R6;
    private pkl53.component.Textfield B5R7;
    private pkl53.component.Textfield B5R7DIBAYAR;
    private pkl53.component.Textfield B5R8;
    private pkl53.component.Textfield B5R9;
    private pkl53.model.tambahan.B3RinciusahaTambahan b3RinciusahaTambahan1;
    private pkl53.imageClass.BlokUsaha5 blok56Usaha1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

  
    /**
     * @return the B5R10
     */
    public pkl53.component.Textfield getB5R10() {
        return B5R10;
    }

    /**
     * @param B5R10 the B5R10 to set
     */
    public void setB5R10(pkl53.component.Textfield B5R10) {
        this.B5R10 = B5R10;
    }

    /**
     * @return the B5R11A
     */
    public pkl53.component.Textfield getB5R11A() {
        return B5R11A;
    }

    /**
     * @param B5R11A the B5R11A to set
     */
    public void setB5R11A(pkl53.component.Textfield B5R11A) {
        this.B5R11A = B5R11A;
    }

    /**
     * @return the B5R11B
     */
    public pkl53.component.Textfield getB5R11B() {
        return B5R11B;
    }

    /**
     * @param B5R11B the B5R11B to set
     */
    public void setB5R11B(pkl53.component.Textfield B5R11B) {
        this.B5R11B = B5R11B;
    }

    /**
     * @return the B5R11C
     */
    public pkl53.component.Textfield getB5R11C() {
        return B5R11C;
    }

    /**
     * @param B5R11C the B5R11C to set
     */
    public void setB5R11C(pkl53.component.Textfield B5R11C) {
        this.B5R11C = B5R11C;
    }

    /**
     * @return the B5R11D
     */
    public pkl53.component.Textfield getB5R11D() {
        return B5R11D;
    }

    /**
     * @param B5R11D the B5R11D to set
     */
    public void setB5R11D(pkl53.component.Textfield B5R11D) {
        this.B5R11D = B5R11D;
    }


    /**
     * @return the B5R11E_LAIN
     */
    public pkl53.component.Textfield getB5R11E_LAIN() {
        return B5R11E_LAIN;
    }

    /**
     * @param B5R11E_LAIN the B5R11E_LAIN to set
     */
    public void setB5R11E_LAIN(pkl53.component.Textfield B5R11E_LAIN) {
        this.B5R11E_LAIN = B5R11E_LAIN;
    }

    /**
     * @return the B5R12A
     */
    public pkl53.component.Textfield getB5R12A() {
        return B5R12A;
    }

    /**
     * @param B5R12A the B5R12A to set
     */
    public void setB5R12A(pkl53.component.Textfield B5R12A) {
        this.B5R12A = B5R12A;
    }

    /**
     * @return the B5R12B
     */
    public pkl53.component.Textfield getB5R12B() {
        return B5R12B;
    }

    /**
     * @param B5R12B the B5R12B to set
     */
    public void setB5R12B(pkl53.component.Textfield B5R12B) {
        this.B5R12B = B5R12B;
    }

    /**
     * @return the B5R12C
     */
    public pkl53.component.Textfield getB5R12C() {
        return B5R12C;
    }

    /**
     * @param B5R12C the B5R12C to set
     */
    public void setB5R12C(pkl53.component.Textfield B5R12C) {
        this.B5R12C = B5R12C;
    }

    /**
     * @return the B5R12D
     */
    public pkl53.component.Textfield getB5R12D() {
        return B5R12D;
    }

    /**
     * @param B5R12D the B5R12D to set
     */
    public void setB5R12D(pkl53.component.Textfield B5R12D) {
        this.B5R12D = B5R12D;
    }

    /**
     * @return the B5R12JUML
     */
    public pkl53.component.Textfield getB5R12JUML() {
        return B5R12JUML;
    }

    /**
     * @param B5R12JUML the B5R12JUML to set
     */
    public void setB5R12JUML(pkl53.component.Textfield B5R12JUML) {
        this.B5R12JUML = B5R12JUML;
    }

    /**
     * @return the B5R13HARI_AGT
     */
    public pkl53.component.Textfield getB5R13HARI_AGT() {
        return B5R13HARI_AGT;
    }

    /**
     * @param B5R13HARI_AGT the B5R13HARI_AGT to set
     */
    public void setB5R13HARI_AGT(pkl53.component.Textfield B5R13HARI_AGT) {
        this.B5R13HARI_AGT = B5R13HARI_AGT;
    }

    /**
     * @return the B5R13HARI_APR
     */
    public pkl53.component.Textfield getB5R13HARI_APR() {
        return B5R13HARI_APR;
    }

    /**
     * @param B5R13HARI_APR the B5R13HARI_APR to set
     */
    public void setB5R13HARI_APR(pkl53.component.Textfield B5R13HARI_APR) {
        this.B5R13HARI_APR = B5R13HARI_APR;
    }

    /**
     * @return the B5R13HARI_DES
     */
    public pkl53.component.Textfield getB5R13HARI_DES() {
        return B5R13HARI_DES;
    }

    /**
     * @param B5R13HARI_DES the B5R13HARI_DES to set
     */
    public void setB5R13HARI_DES(pkl53.component.Textfield B5R13HARI_DES) {
        this.B5R13HARI_DES = B5R13HARI_DES;
    }

    /**
     * @return the B5R13HARI_FEB
     */
    public pkl53.component.Textfield getB5R13HARI_FEB() {
        return B5R13HARI_FEB;
    }

    /**
     * @param B5R13HARI_FEB the B5R13HARI_FEB to set
     */
    public void setB5R13HARI_FEB(pkl53.component.Textfield B5R13HARI_FEB) {
        this.B5R13HARI_FEB = B5R13HARI_FEB;
    }

    /**
     * @return the B5R13HARI_JAN
     */
    public pkl53.component.Textfield getB5R13HARI_JAN() {
        return B5R13HARI_JAN;
    }

    /**
     * @param B5R13HARI_JAN the B5R13HARI_JAN to set
     */
    public void setB5R13HARI_JAN(pkl53.component.Textfield B5R13HARI_JAN) {
        this.B5R13HARI_JAN = B5R13HARI_JAN;
    }

    /**
     * @return the B5R13HARI_JUL
     */
    public pkl53.component.Textfield getB5R13HARI_JUL() {
        return B5R13HARI_JUL;
    }

    /**
     * @param B5R13HARI_JUL the B5R13HARI_JUL to set
     */
    public void setB5R13HARI_JUL(pkl53.component.Textfield B5R13HARI_JUL) {
        this.B5R13HARI_JUL = B5R13HARI_JUL;
    }

    /**
     * @return the B5R13HARI_JUN
     */
    public pkl53.component.Textfield getB5R13HARI_JUN() {
        return B5R13HARI_JUN;
    }

    /**
     * @param B5R13HARI_JUN the B5R13HARI_JUN to set
     */
    public void setB5R13HARI_JUN(pkl53.component.Textfield B5R13HARI_JUN) {
        this.B5R13HARI_JUN = B5R13HARI_JUN;
    }

    /**
     * @return the B5R13HARI_MAR
     */
    public pkl53.component.Textfield getB5R13HARI_MAR() {
        return B5R13HARI_MAR;
    }

    /**
     * @param B5R13HARI_MAR the B5R13HARI_MAR to set
     */
    public void setB5R13HARI_MAR(pkl53.component.Textfield B5R13HARI_MAR) {
        this.B5R13HARI_MAR = B5R13HARI_MAR;
    }

    /**
     * @return the B5R13HARI_MEI
     */
    public pkl53.component.Textfield getB5R13HARI_MEI() {
        return B5R13HARI_MEI;
    }

    /**
     * @param B5R13HARI_MEI the B5R13HARI_MEI to set
     */
    public void setB5R13HARI_MEI(pkl53.component.Textfield B5R13HARI_MEI) {
        this.B5R13HARI_MEI = B5R13HARI_MEI;
    }

    /**
     * @return the B5R13HARI_NOV
     */
    public pkl53.component.Textfield getB5R13HARI_NOV() {
        return B5R13HARI_NOV;
    }

    /**
     * @param B5R13HARI_NOV the B5R13HARI_NOV to set
     */
    public void setB5R13HARI_NOV(pkl53.component.Textfield B5R13HARI_NOV) {
        this.B5R13HARI_NOV = B5R13HARI_NOV;
    }

    /**
     * @return the B5R13HARI_OKT
     */
    public pkl53.component.Textfield getB5R13HARI_OKT() {
        return B5R13HARI_OKT;
    }

    /**
     * @param B5R13HARI_OKT the B5R13HARI_OKT to set
     */
    public void setB5R13HARI_OKT(pkl53.component.Textfield B5R13HARI_OKT) {
        this.B5R13HARI_OKT = B5R13HARI_OKT;
    }

    /**
     * @return the B5R13HARI_SEP
     */
    public pkl53.component.Textfield getB5R13HARI_SEP() {
        return B5R13HARI_SEP;
    }

    /**
     * @param B5R13HARI_SEP the B5R13HARI_SEP to set
     */
    public void setB5R13HARI_SEP(pkl53.component.Textfield B5R13HARI_SEP) {
        this.B5R13HARI_SEP = B5R13HARI_SEP;
    }

    /**
     * @return the B5R13KODE_AGT
     */
    public pkl53.component.Textfield getB5R13KODE_AGT() {
        return B5R13KODE_AGT;
    }

    /**
     * @param B5R13KODE_AGT the B5R13KODE_AGT to set
     */
    public void setB5R13KODE_AGT(pkl53.component.Textfield B5R13KODE_AGT) {
        this.B5R13KODE_AGT = B5R13KODE_AGT;
    }

    /**
     * @return the B5R13KODE_APR
     */
    public pkl53.component.Textfield getB5R13KODE_APR() {
        return B5R13KODE_APR;
    }

    /**
     * @param B5R13KODE_APR the B5R13KODE_APR to set
     */
    public void setB5R13KODE_APR(pkl53.component.Textfield B5R13KODE_APR) {
        this.B5R13KODE_APR = B5R13KODE_APR;
    }

    /**
     * @return the B5R13KODE_DES
     */
    public pkl53.component.Textfield getB5R13KODE_DES() {
        return B5R13KODE_DES;
    }

    /**
     * @param B5R13KODE_DES the B5R13KODE_DES to set
     */
    public void setB5R13KODE_DES(pkl53.component.Textfield B5R13KODE_DES) {
        this.B5R13KODE_DES = B5R13KODE_DES;
    }

    /**
     * @return the B5R13KODE_FEB
     */
    public pkl53.component.Textfield getB5R13KODE_FEB() {
        return B5R13KODE_FEB;
    }

    /**
     * @param B5R13KODE_FEB the B5R13KODE_FEB to set
     */
    public void setB5R13KODE_FEB(pkl53.component.Textfield B5R13KODE_FEB) {
        this.B5R13KODE_FEB = B5R13KODE_FEB;
    }

    /**
     * @return the B5R13KODE_JAN
     */
    public pkl53.component.Textfield getB5R13KODE_JAN() {
        return B5R13KODE_JAN;
    }

    /**
     * @param B5R13KODE_JAN the B5R13KODE_JAN to set
     */
    public void setB5R13KODE_JAN(pkl53.component.Textfield B5R13KODE_JAN) {
        this.B5R13KODE_JAN = B5R13KODE_JAN;
    }

    /**
     * @return the B5R13KODE_JUL
     */
    public pkl53.component.Textfield getB5R13KODE_JUL() {
        return B5R13KODE_JUL;
    }

    /**
     * @param B5R13KODE_JUL the B5R13KODE_JUL to set
     */
    public void setB5R13KODE_JUL(pkl53.component.Textfield B5R13KODE_JUL) {
        this.B5R13KODE_JUL = B5R13KODE_JUL;
    }

    /**
     * @return the B5R13KODE_JUN
     */
    public pkl53.component.Textfield getB5R13KODE_JUN() {
        return B5R13KODE_JUN;
    }

    /**
     * @param B5R13KODE_JUN the B5R13KODE_JUN to set
     */
    public void setB5R13KODE_JUN(pkl53.component.Textfield B5R13KODE_JUN) {
        this.B5R13KODE_JUN = B5R13KODE_JUN;
    }

    /**
     * @return the B5R13KODE_MAR
     */
    public pkl53.component.Textfield getB5R13KODE_MAR() {
        return B5R13KODE_MAR;
    }

    /**
     * @param B5R13KODE_MAR the B5R13KODE_MAR to set
     */
    public void setB5R13KODE_MAR(pkl53.component.Textfield B5R13KODE_MAR) {
        this.B5R13KODE_MAR = B5R13KODE_MAR;
    }

    /**
     * @return the B5R13KODE_MEI
     */
    public pkl53.component.Textfield getB5R13KODE_MEI() {
        return B5R13KODE_MEI;
    }

    /**
     * @param B5R13KODE_MEI the B5R13KODE_MEI to set
     */
    public void setB5R13KODE_MEI(pkl53.component.Textfield B5R13KODE_MEI) {
        this.B5R13KODE_MEI = B5R13KODE_MEI;
    }

    /**
     * @return the B5R13KODE_NOV
     */
    public pkl53.component.Textfield getB5R13KODE_NOV() {
        return B5R13KODE_NOV;
    }

    /**
     * @param B5R13KODE_NOV the B5R13KODE_NOV to set
     */
    public void setB5R13KODE_NOV(pkl53.component.Textfield B5R13KODE_NOV) {
        this.B5R13KODE_NOV = B5R13KODE_NOV;
    }

    /**
     * @return the B5R13KODE_OKT
     */
    public pkl53.component.Textfield getB5R13KODE_OKT() {
        return B5R13KODE_OKT;
    }

    /**
     * @param B5R13KODE_OKT the B5R13KODE_OKT to set
     */
    public void setB5R13KODE_OKT(pkl53.component.Textfield B5R13KODE_OKT) {
        this.B5R13KODE_OKT = B5R13KODE_OKT;
    }

    /**
     * @return the B5R13KODE_SEP
     */
    public pkl53.component.Textfield getB5R13KODE_SEP() {
        return B5R13KODE_SEP;
    }

    /**
     * @param B5R13KODE_SEP the B5R13KODE_SEP to set
     */
    public void setB5R13KODE_SEP(pkl53.component.Textfield B5R13KODE_SEP) {
        this.B5R13KODE_SEP = B5R13KODE_SEP;
    }

    /**
     * @return the B5R14
     */
    public pkl53.component.Textfield getB5R14() {
        return B5R14;
    }

    /**
     * @param B5R14 the B5R14 to set
     */
    public void setB5R14(pkl53.component.Textfield B5R14) {
        this.B5R14 = B5R14;
    }

    /**
     * @return the B5R1NOART
     */
    public pkl53.component.Textfield getB5R1NOART() {
        return B5R1NOART;
    }

    /**
     * @param B5R1NOART the B5R1NOART to set
     */
    public void setB5R1NOART(pkl53.component.Textfield B5R1NOART) {
        this.B5R1NOART = B5R1NOART;
    }

    /**
     * @return the B5R2
     */
    public pkl53.component.Textfield getB5R2() {
        return B5R2;
    }

    /**
     * @param B5R2 the B5R2 to set
     */
    public void setB5R2(pkl53.component.Textfield B5R2) {
        this.B5R2 = B5R2;
    }

    /**
     * @return the B5R3
     */
    public pkl53.component.Textfield getB5R3() {
        return B5R3;
    }

    /**
     * @param B5R3 the B5R3 to set
     */
    public void setB5R3(pkl53.component.Textfield B5R3) {
        this.B5R3 = B5R3;
    }

    /**
     * @return the B5R4BULAN
     */
    public pkl53.component.Textfield getB5R4BULAN() {
        return B5R4BULAN;
    }

    /**
     * @param B5R4BULAN the B5R4BULAN to set
     */
    public void setB5R4BULAN(pkl53.component.Textfield B5R4BULAN) {
        this.B5R4BULAN = B5R4BULAN;
    }

    /**
     * @return the B5R4TAHUN
     */
    public pkl53.component.Textfield getB5R4TAHUN() {
        return B5R4TAHUN;
    }

    /**
     * @param B5R4TAHUN the B5R4TAHUN to set
     */
    public void setB5R4TAHUN(pkl53.component.Textfield B5R4TAHUN) {
        this.B5R4TAHUN = B5R4TAHUN;
    }

    /**
     * @return the B5R5
     */
    public pkl53.component.Textfield getB5R5() {
        return B5R5;
    }

    /**
     * @param B5R5 the B5R5 to set
     */
    public void setB5R5(pkl53.component.Textfield B5R5) {
        this.B5R5 = B5R5;
    }

    /**
     * @return the B5R5_10_LAIN
     */
    public pkl53.component.Textfield getB5R5_10_LAIN() {
        return B5R5_10_LAIN;
    }

    /**
     * @param B5R5_10_LAIN the B5R5_10_LAIN to set
     */
    public void setB5R5_10_LAIN(pkl53.component.Textfield B5R5_10_LAIN) {
        this.B5R5_10_LAIN = B5R5_10_LAIN;
    }

    /**
     * @return the B5R5_13_LAIN
     */
    public pkl53.component.Textfield getB5R5_13_LAIN() {
        return B5R5_13_LAIN;
    }

    /**
     * @param B5R5_13_LAIN the B5R5_13_LAIN to set
     */
    public void setB5R5_13_LAIN(pkl53.component.Textfield B5R5_13_LAIN) {
        this.B5R5_13_LAIN = B5R5_13_LAIN;
    }

    /**
     * @return the B5R6
     */
    public pkl53.component.Textfield getB5R6() {
        return B5R6;
    }

    /**
     * @param B5R6 the B5R6 to set
     */
    public void setB5R6(pkl53.component.Textfield B5R6) {
        this.B5R6 = B5R6;
    }

    /**
     * @return the B5R7
     */
    public pkl53.component.Textfield getB5R7() {
        return B5R7;
    }

    /**
     * @param B5R7 the B5R7 to set
     */
    public void setB5R7(pkl53.component.Textfield B5R7) {
        this.B5R7 = B5R7;
    }

    /**
     * @return the B5R7DIBAYAR
     */
    public pkl53.component.Textfield getB5R7DIBAYAR() {
        return B5R7DIBAYAR;
    }

    /**
     * @param B5R7DIBAYAR the B5R7DIBAYAR to set
     */
    public void setB5R7DIBAYAR(pkl53.component.Textfield B5R7DIBAYAR) {
        this.B5R7DIBAYAR = B5R7DIBAYAR;
    }

    /**
     * @return the B5R8
     */
    public pkl53.component.Textfield getB5R8() {
        return B5R8;
    }

    /**
     * @param B5R8 the B5R8 to set
     */
    public void setB5R8(pkl53.component.Textfield B5R8) {
        this.B5R8 = B5R8;
    }

    /**
     * @return the B5R9
     */
    public pkl53.component.Textfield getB5R9() {
        return B5R9;
    }

    /**
     * @param B5R9 the B5R9 to set
     */
    public void setB5R9(pkl53.component.Textfield B5R9) {
        this.B5R9 = B5R9;
    }

    /**
     * @return the B5R1NAMA
     */
    public static  pkl53.component.Textfield getB5R1NAMA() {
        return B5R1NAMA;
    }

    /**
     * @param B5R1NAMA the B5R1NAMA to set
     */
    public void setB5R1NAMA(pkl53.component.Textfield B5R1NAMA) {
        this.B5R1NAMA = B5R1NAMA;
    }

    void setBlokUsaha5b(BlokUsaha5B blokUsaha5B1) {
        this.blokUsaha5B = blokUsaha5B1;
    }

    /**
     * @return the b3RinciusahaTambahan1
     */
    public pkl53.model.tambahan.B3RinciusahaTambahan getB3RinciusahaTambahan1() {
        return b3RinciusahaTambahan1;
    }

  
}
