/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkl53.view;

import pkl53.view.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import pkl53.controller.BackupKuesionerUsaha;
import pkl53.controller.KuesionerControllerUsaha;
import pkl53.controller.SubmitAllControllerUsaha;
import pkl53.model.tambahan.B3RinciusahaTambahan;
import pkl53.model.tambahan.B3r15PekerjaTambahan;
import pkl53.view.loop.Loop4Usaha;

/**
 *
 * @author akhul
 */
public class DataEntriUsahaPanel extends javax.swing.JPanel {

    private JPanel panel;
    private KuesionerControllerUsaha kuesionerControllerUsaha;
    private int jumlahPekerja = 0;
    private int loop = 0;
    private ArrayList<ArrayList<B3r15PekerjaTambahan>> listAllB3R15 = new ArrayList<ArrayList<B3r15PekerjaTambahan>>();
    private BackupKuesionerUsaha backupKuesionerUsaha;
    private ArrayList<B3RinciusahaTambahan> b3RinciusahaTambahanListA = new ArrayList<B3RinciusahaTambahan>();
    private ArrayList<B3RinciusahaTambahan> b3RinciusahaTambahanListB = new ArrayList<B3RinciusahaTambahan>();
    private ArrayList<B3RinciusahaTambahan> b3RinciusahaTambahanListC = new ArrayList<B3RinciusahaTambahan>();
    private ArrayList<B3RinciusahaTambahan> b3RinciusahaTambahanListD = new ArrayList<B3RinciusahaTambahan>();
    private int i = 0;
    private static BlokUsaha123 bUsaha123;
    private static BlokUsaha4 bUsaha4;
    private static CardLayout card;

    /**
     * Creates new form DataEntriUsahaPanel
     */
    public DataEntriUsahaPanel() {
        initComponents();
        final TimerTask t = new TimerTask() {

            @Override
            public void run() {

                i++;
                jLabelTime.setText(String.valueOf(i));
            }
        };
        new java.util.Timer().scheduleAtFixedRate(
                t,
                0, // run first occurrence immediatetly
                1000
        );

    }

    static void instanceNewBlok() {
        bUsaha123 = new BlokUsaha123();
        bUsaha4 = new BlokUsaha4();
        bUsaha123.setName("blok123");
        bUsaha4.setName("blok4");
        card = (CardLayout) containerPanel.getLayout();
        containerPanel.setLayout(card);
        containerPanel.add(bUsaha123);
        containerPanel.add(bUsaha4);
        bUsaha123.getB1R1().requestFocusInWindow();
    }

    public void setmainFrame(JPanel panel) {
        this.panel = panel;
    }

    private int getJumlahPekerjaBlok4() {
        int j = 0;
        if (BlokUsaha4.getLoopPanel().getComponents().length > 0) {
            Component[] comp = BlokUsaha4.getLoopPanel().getComponents();
            for (int i = 0; i < comp.length; i++) {
                Loop4Usaha loops = (Loop4Usaha) comp[i];
                if (loops.getB4R16().getText().equals("1")) {
                    j++;
                    System.out.println("Usaha Jumlah pekerja: " + j);
                }
            }
        }
        return j;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundLain1 = new pkl53.imageClass.BackgroundLain();
        jScrollPane1 = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();

        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1070, 1070));

        containerPanel.setBackground(new java.awt.Color(204, 255, 204));
        containerPanel.setOpaque(false);
        containerPanel.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(containerPanel);

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/next.png"))); // NOI18N
        nextButton.setContentAreaFilled(false);
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextButtonMouseExited(evt);
            }
        });
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/prev.png"))); // NOI18N
        previousButton.setContentAreaFilled(false);
        previousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                previousButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                previousButtonMouseExited(evt);
            }
        });
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/home.png"))); // NOI18N
        homeButton.setContentAreaFilled(false);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/reset2.png"))); // NOI18N
        Reset.setContentAreaFilled(false);
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResetMouseExited(evt);
            }
        });
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/submit.png"))); // NOI18N
        Submit.setContentAreaFilled(false);
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitMouseExited(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Entri");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Waktu :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("(s)");

        jLabelTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTime.setForeground(new java.awt.Color(51, 153, 0));
        jLabelTime.setText("00");

        javax.swing.GroupLayout backgroundLain1Layout = new javax.swing.GroupLayout(backgroundLain1);
        backgroundLain1.setLayout(backgroundLain1Layout);
        backgroundLain1Layout.setHorizontalGroup(
            backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLain1Layout.createSequentialGroup()
                .addGroup(backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(backgroundLain1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLain1Layout.createSequentialGroup()
                        .addGroup(backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLain1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel1))
                            .addGroup(backgroundLain1Layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(jLabelTime)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        backgroundLain1Layout.setVerticalGroup(
            backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLain1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLain1Layout.createSequentialGroup()
                        .addGroup(backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Submit)
                            .addComponent(Reset)
                            .addGroup(backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nextButton)
                                .addComponent(previousButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLain1Layout.createSequentialGroup()
                        .addGroup(backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabelTime))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLain1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        System.out.println(getCurrentCard().getName());
        System.out.println(bUsaha123.getName());
        card = (CardLayout) containerPanel.getLayout();

        if (getCurrentCard().getName() != null) {
            if (getCurrentCard().getName().equals("blok4")) {
                setJumlahPekerja(getJumlahPekerjaBlok4());

                if (jumlahPekerja != 0) {
                    Component[] comp = containerPanel.getComponents();
                    if (comp.length == 2) {
                        while (getLoop() < getJumlahPekerja()) {
                            BlokUsaha5 b5new = new BlokUsaha5();
                            BlokUsaha5B b5Bnew = new BlokUsaha5B();
                            BlokUsaha5C b5Cnew = new BlokUsaha5C();
                            BlokUsaha5D b5Dnew = new BlokUsaha5D();
                            b5new.setName("blok5");
                            b5Bnew.setName("blok5b");
                            b5Cnew.setName("blok5c");
                            b5Dnew.setName(String.valueOf(getLoop() + 1));
                            containerPanel.add(b5new);
                            containerPanel.add(b5Bnew);
                            containerPanel.add(b5Cnew);
                            containerPanel.add(b5Dnew);

                            b3RinciusahaTambahanListA.add(b5new.getB3RinciusahaTambahan1());
                            b3RinciusahaTambahanListB.add(b5Bnew.getB3RinciusahaTambahan1());
                            listAllB3R15.add(b5Bnew.getListModelB3R15());
                            b3RinciusahaTambahanListC.add(b5Cnew.getB3RinciusahaTambahan1());
                            b3RinciusahaTambahanListD.add(b5Dnew.getB3RinciusahaTambahan1());

                            setLoop(getLoop() + 1);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(panel, "Cek Rincian 16");
                    return;
                }
            }

            if (getCurrentCard().getName().equals("blok123")) {
                if (BlokUsaha4.getLoopPanel().getComponents().length < 1) {
                    System.out.println("mau masuk SETLOOP");
                    bUsaha4.setLoop();
                    i = 0;
                    card.next(getContainerPanel());
                    
                    jScrollPane1.getViewport().setViewPosition(new java.awt.Point(0, 0));
                    return;
                }
            }
            if (getCurrentCard().getName().matches("[0-9]")) {
                if (!(getCurrentCard().getName().equals(String.valueOf(getJumlahPekerja())))) {
                    jScrollPane1.getViewport().setViewPosition(new java.awt.Point(0, 0));
                    JOptionPane.showMessageDialog(this, "Lanjut input entri ART ke-" + String.valueOf(Integer.parseInt(getCurrentCard().getName()) + 1));

                    card.next(getContainerPanel());
                    BlokUsaha5.getB5R1NAMA().requestFocusInWindow();
                    jScrollPane1.getViewport().setViewPosition(new java.awt.Point(0, 0));
                    return;

                }

            }

            if (getCurrentCard().getName().equals(String.valueOf(jumlahPekerja))) {
                JOptionPane.showMessageDialog(this, "Sudah selesai. Silakan submit");
                return;
            }

            card.next(getContainerPanel());
            BlokUsaha5.getB5R1NAMA().requestFocusInWindow();
            
            BlokUsaha5C.getB5R18A().requestFocusInWindow();
            BlokUsaha5D.getB5R24().requestFocusInWindow();
            
            jScrollPane1.getViewport().setViewPosition(new java.awt.Point(0, 0));

        } else {
            card.next(getContainerPanel());
            jScrollPane1.getViewport().setViewPosition(new java.awt.Point(0, 0));
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        if (!getCurrentCard().getName().equals("blok123")) {
            setCard((CardLayout) getContainerPanel().getLayout());
            getCard().previous(getContainerPanel());
            jScrollPane1.getViewport().setViewPosition(new java.awt.Point(0, 0));
        }

    }//GEN-LAST:event_previousButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Reset?", "Confirm", 0);
        if (x == 0) {
            int c = containerPanel.getComponentCount();
            System.out.println("Home--> Container : " + c);
            containerPanel.removeAll();
            System.out.println("reset a"+BlokUsaha4.getB2TambahanList().size());
            BlokUsaha4.getB2TambahanList().clear();
            System.out.println("reset b"+BlokUsaha4.getB2TambahanList().size());
            b3RinciusahaTambahanListA.clear();
            b3RinciusahaTambahanListB.clear();
            b3RinciusahaTambahanListC.clear();
            b3RinciusahaTambahanListD.clear();
            listAllB3R15.clear();
            setLoop(0);
            DataEntriUsahaPanel.instanceNewBlok();
            i = 0;
            setCard((CardLayout) getContainerPanel().getLayout());
            getCard().show(getContainerPanel(), "blok1");

            setCard((CardLayout) panel.getLayout());
            getCard().show(panel, "pupanel");
        }
    }//GEN-LAST:event_homeButtonActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Reset?", "Confirm", 0);
        if (x == 0) {
            int c = containerPanel.getComponentCount();
            System.out.println("Home--> Container : " + c);
            containerPanel.removeAll();
            System.out.println("reset a"+BlokUsaha4.getB2TambahanList().size());
            BlokUsaha4.getB2TambahanList().clear();
            System.out.println("reset b"+BlokUsaha4.getB2TambahanList().size());
            b3RinciusahaTambahanListA.clear();
            b3RinciusahaTambahanListB.clear();
            b3RinciusahaTambahanListC.clear();
            b3RinciusahaTambahanListD.clear();
            listAllB3R15.clear();
            setLoop(0);
            DataEntriUsahaPanel.instanceNewBlok();
            i = 0;
            setCard((CardLayout) getContainerPanel().getLayout());
            getCard().show(getContainerPanel(), "blok1");
            jScrollPane1.getViewport().setViewPosition(new java.awt.Point(0, 0));
        }
    }//GEN-LAST:event_ResetActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Submit?", "Confirm", 0);
        if (x == 0) {
            SubmitAllControllerUsaha submit = new SubmitAllControllerUsaha();
            submit.setPanelBlok123(bUsaha123);
            submit.setPanelBlok4(bUsaha4);
            submit.setB3RinciusahaTambahanListA(getB3RinciusahaTambahanListA());
            submit.setB3RinciusahaTambahanListB(getB3RinciusahaTambahanListB());
            submit.setListAllB3R15(listAllB3R15);
            submit.setB3RinciusahaTambahanListC(getB3RinciusahaTambahanListC());
            submit.setB3RinciusahaTambahanListD(getB3RinciusahaTambahanListD());
            submit.insertAllBlok(i);
            i = 0;
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void nextButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseEntered
        // TODO add your handling code here:
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/nexthover.png")));

    }//GEN-LAST:event_nextButtonMouseEntered

    private void nextButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseExited
        // TODO add your handling code here:
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/next.png")));

    }//GEN-LAST:event_nextButtonMouseExited

    private void previousButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseEntered
        // TODO add your handling code here:
        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/prevhover.png")));

    }//GEN-LAST:event_previousButtonMouseEntered

    private void previousButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseExited
        // TODO add your handling code here:
        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/prev.png")));

    }//GEN-LAST:event_previousButtonMouseExited

    private void SubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseEntered
        // TODO add your handling code here:
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/submithover.png")));

    }//GEN-LAST:event_SubmitMouseEntered

    private void SubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseExited
        // TODO add your handling code here:
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/submit.png")));

    }//GEN-LAST:event_SubmitMouseExited

    private void ResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseEntered
        // TODO add your handling code here:
        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/reset2hover.png")));

    }//GEN-LAST:event_ResetMouseEntered

    private void ResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseExited
        // TODO add your handling code here:
        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/reset2.png")));

    }//GEN-LAST:event_ResetMouseExited

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        // TODO add your handling code here:
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/homehover.png")));

    }//GEN-LAST:event_homeButtonMouseEntered

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        // TODO add your handling code here:
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/home.png")));

    }//GEN-LAST:event_homeButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton Submit;
    private pkl53.imageClass.BackgroundLain backgroundLain1;
    private static javax.swing.JPanel containerPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the card
     */
    public CardLayout getCard() {
        return card;
    }

    /**
     * @param aCard the card to set
     */
    public void setCard(CardLayout aCard) {
        card = aCard;
    }

    /**
     * @return the containerPanel
     */
    public static javax.swing.JPanel getContainerPanel() {
        return containerPanel;
    }

    /**
     * @return the panel
     */
    public JPanel getPanel() {
        return panel;
    }

    private JPanel getCurrentCard() {
        JPanel card = null;
        for (Component comp : containerPanel.getComponents()) {
            if (comp.isVisible() == true) {
                card = (JPanel) comp;
            }
        }
        return card;
    }

    /**
     * @return the jumlahPekerja
     */
    public int getJumlahPekerja() {
        return jumlahPekerja;
    }

    /**
     * @param jumlahPekerja the jumlahPekerja to set
     */
    public void setJumlahPekerja(int jumlahPekerja) {
        this.jumlahPekerja = jumlahPekerja;
    }

    /**
     * @return the b3RinciusahaTambahanListA
     */
    public ArrayList<B3RinciusahaTambahan> getB3RinciusahaTambahanListA() {
        return b3RinciusahaTambahanListA;
    }

    /**
     * @return the b3RinciusahaTambahanListB
     */
    public ArrayList<B3RinciusahaTambahan> getB3RinciusahaTambahanListB() {
        return b3RinciusahaTambahanListB;
    }

    /**
     * @return the b3RinciusahaTambahanListC
     */
    public ArrayList<B3RinciusahaTambahan> getB3RinciusahaTambahanListC() {
        return b3RinciusahaTambahanListC;
    }

    /**
     * @return the b3RinciusahaTambahanListD
     */
    public ArrayList<B3RinciusahaTambahan> getB3RinciusahaTambahanListD() {
        return b3RinciusahaTambahanListD;
    }

    /**
     * @return the loop
     */
    public int getLoop() {
        return loop;
    }

    /**
     * @param loop the loop to set
     */
    public void setLoop(int loop) {
        this.loop = loop;
    }

}
