/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkl53.view;

import java.awt.CardLayout;
import javax.swing.JFileChooser;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import pkl53.controller.BackupKuesioner;
import pkl53.controller.BackupKuesionerUsaha;

/**
 *
 * @author User
 */
public class HomePUPanel extends javax.swing.JPanel {

    /**
     * @param aPathTextField the pathTextField to set
     */
    public static void setPathTextField(javax.swing.JTextField aPathTextField) {
        pathTextField = aPathTextField;
    }

    private MainFrame mainFrame1;
    
   
    private LoginPanel2 panel2;
    
    private JPanel panel;
    private CardLayout card;
    
    private LoginPanel2 loginPanel2;
    
    
    /**
     * Creates new form homePanel
     */
    public HomePUPanel() {
        initComponents();
        
        
        //panel2.setUsername(null);
    }
    
      public void setmainFrame(MainFrame frameUtama, JPanel panel, CardLayout card){
        setMainFrame1(frameUtama);
        this.setPanel(panel);
        this.setCard(card);
        }
      
//      public void setMenuBar(JMenuBar menu){
//          menubar = menu;
//        }
      


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        backgroundLain1 = new pkl53.imageClass.BackgroundLain();
        pathTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        importButtonNewPanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        updateDialog = new javax.swing.JDialog();
        updatePanel1 = new pkl53.view.UpdatePanel();
        homePencacahan1 = new pkl53.imageClass.HomePencacahan();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        hometButton = new javax.swing.JButton();
        usahaEntriButton = new javax.swing.JButton();
        PekerjaEntriButton = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(505, 200));
        jDialog1.setModal(true);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        importButtonNewPanel.setBackground(new java.awt.Color(51, 153, 255));
        importButtonNewPanel.setText("Import");
        importButtonNewPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonNewPanelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Import Data");

        javax.swing.GroupLayout backgroundLain1Layout = new javax.swing.GroupLayout(backgroundLain1);
        backgroundLain1.setLayout(backgroundLain1Layout);
        backgroundLain1Layout.setHorizontalGroup(
            backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLain1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLain1Layout.createSequentialGroup()
                        .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLain1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(importButtonNewPanel)
                        .addGap(140, 140, 140)))
                .addGap(61, 61, 61))
            .addGroup(backgroundLain1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLain1Layout.setVerticalGroup(
            backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLain1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(backgroundLain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(importButtonNewPanel)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLain1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLain1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        updateDialog.setModal(true);
        updateDialog.getContentPane().add(updatePanel1, java.awt.BorderLayout.CENTER);

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hometButton.setBackground(new java.awt.Color(102, 51, 0));
        hometButton.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        hometButton.setForeground(new java.awt.Color(255, 255, 255));
        hometButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/homebutton.png"))); // NOI18N
        hometButton.setContentAreaFilled(false);
        hometButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hometButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hometButtonMouseExited(evt);
            }
        });
        hometButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hometButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(hometButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 180, 47));

        usahaEntriButton.setBackground(new java.awt.Color(255, 255, 204));
        usahaEntriButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/usaha.png"))); // NOI18N
        usahaEntriButton.setBorder(null);
        usahaEntriButton.setBorderPainted(false);
        usahaEntriButton.setContentAreaFilled(false);
        usahaEntriButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        usahaEntriButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usahaEntriButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usahaEntriButtonMouseExited(evt);
            }
        });
        usahaEntriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usahaEntriButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(usahaEntriButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 348, 186, 50));

        PekerjaEntriButton.setBackground(new java.awt.Color(102, 51, 0));
        PekerjaEntriButton.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        PekerjaEntriButton.setForeground(new java.awt.Color(255, 255, 255));
        PekerjaEntriButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/pekerjaan.png"))); // NOI18N
        PekerjaEntriButton.setContentAreaFilled(false);
        PekerjaEntriButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PekerjaEntriButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PekerjaEntriButtonMouseExited(evt);
            }
        });
        PekerjaEntriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PekerjaEntriButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(PekerjaEntriButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 187, 48));

        javax.swing.GroupLayout homePencacahan1Layout = new javax.swing.GroupLayout(homePencacahan1);
        homePencacahan1.setLayout(homePencacahan1Layout);
        homePencacahan1Layout.setHorizontalGroup(
            homePencacahan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
            .addGroup(homePencacahan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homePencacahan1Layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        homePencacahan1Layout.setVerticalGroup(
            homePencacahan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(homePencacahan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        add(homePencacahan1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void importButtonNewPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonNewPanelActionPerformed
        // TODO add your handling code here:
        
        jDialog1.setVisible(false);
        String fileSeparator = System.getProperty("file.separator");
        String folderDir = System.getProperty("user.home") + fileSeparator + "Data-entry-pkl53"+fileSeparator+"Pekerjaan";
        
        if(getPathTextField().getText().equals(folderDir)){
        BackupKuesioner.read();
        getPathTextField().setText("");
        card = (CardLayout) panel.getLayout();
        card.show(panel, "dataEntri");
//        DataEntriPekerjaanPanel.getBlok1232().getB1R1().requestFocusInWindow();}
//        else{
//        BackupKuesionerUsaha.read();
        getPathTextField().setText("");
        card = (CardLayout) panel.getLayout();
        card.show(panel, "dataEntri");
//        DataEntriUsahaPanel.getBlok123Usaha1().getB1R1().requestFocusInWindow();
        }
        
            
    }//GEN-LAST:event_importButtonNewPanelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       int val = getjFileChooser1().showOpenDialog(this);
       if(val ==  JFileChooser.APPROVE_OPTION){
            getPathTextField().setText(getjFileChooser1().getSelectedFile().getAbsolutePath());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hometButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hometButtonActionPerformed
        // TODO add your handling code here:
        card.show(panel, "homePanel");
//            getjDialog1().setLocationRelativeTo(this);
//            getjDialog1().setVisible(true);
    
        
    }//GEN-LAST:event_hometButtonActionPerformed

    private void usahaEntriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usahaEntriButtonActionPerformed
        // TODO add your handling code here:
        DataEntriUsahaPanel.getContainerPanel().removeAll();
        DataEntriUsahaPanel.instanceNewBlok();
        
        
        setCard((CardLayout) getPanel().getLayout());
        getCard().show(getPanel(), "dataEntriUsaha");
          BlokUsaha123.getB1R1().requestFocusInWindow();
        
    }//GEN-LAST:event_usahaEntriButtonActionPerformed

    private void PekerjaEntriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PekerjaEntriButtonActionPerformed
        // TODO add your handling code here:
         setCard((CardLayout) getPanel().getLayout());
         DataEntriPekerjaanPanel.getContainerPanel().removeAll();
         DataEntriPekerjaanPanel.intanceNewBlok();
        getCard().show(getPanel(), "dataEntri");
        Blok123.getB1R1().requestFocusInWindow();
    }//GEN-LAST:event_PekerjaEntriButtonActionPerformed

    private void usahaEntriButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usahaEntriButtonMouseEntered
        // TODO add your handling code here:
        usahaEntriButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/usahahover.png")));
    }//GEN-LAST:event_usahaEntriButtonMouseEntered

    private void usahaEntriButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usahaEntriButtonMouseExited
        // TODO add your handling code here:
        usahaEntriButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/usaha.png")));
    }//GEN-LAST:event_usahaEntriButtonMouseExited

    private void PekerjaEntriButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PekerjaEntriButtonMouseEntered
        // TODO add your handling code here:
        PekerjaEntriButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/pekerjaanhover.png")));
    }//GEN-LAST:event_PekerjaEntriButtonMouseEntered

    private void PekerjaEntriButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PekerjaEntriButtonMouseExited
        // TODO add your handling code here:
        PekerjaEntriButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/pekerjaan.png")));
    }//GEN-LAST:event_PekerjaEntriButtonMouseExited

    private void hometButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hometButtonMouseEntered
        // TODO add your handling code here:
        hometButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/homebuttonhover.png")));
    }//GEN-LAST:event_hometButtonMouseEntered

    private void hometButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hometButtonMouseExited
        // TODO add your handling code here:
        hometButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl53/image/tombol/homebutton.png")));
    }//GEN-LAST:event_hometButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PekerjaEntriButton;
    private pkl53.imageClass.BackgroundLain backgroundLain1;
    private pkl53.imageClass.HomePencacahan homePencacahan1;
    private javax.swing.JButton hometButton;
    private javax.swing.JButton importButtonNewPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private static javax.swing.JTextField pathTextField;
    private javax.swing.JDialog updateDialog;
    private pkl53.view.UpdatePanel updatePanel1;
    private javax.swing.JButton usahaEntriButton;
    // End of variables declaration//GEN-END:variables

public static javax.swing.JTextField getPathTextField() {
        return pathTextField;
    }

    /**
     * @return the mainFrame1
     */
    public MainFrame getMainFrame1() {
        return mainFrame1;
    }

    /**
     * @param mainFrame1 the mainFrame1 to set
     */
    public void setMainFrame1(MainFrame mainFrame1) {
        this.mainFrame1 = mainFrame1;
    }

    /**
     * @return the panel2
     */
    public LoginPanel2 getPanel2() {
        return panel2;
    }

    /**
     * @param panel2 the panel2 to set
     */
    public void setPanel2(LoginPanel2 panel2) {
        this.panel2 = panel2;
    }

    /**
     * @return the panel
     */
    public JPanel getPanel() {
        return panel;
    }

    /**
     * @param panel the panel to set
     */
    public void setPanel(JPanel panel) {
        this.panel = panel;
    }

    /**
     * @return the card
     */
    public CardLayout getCard() {
        return card;
    }

    /**
     * @param card the card to set
     */
    public void setCard(CardLayout card) {
        this.card = card;
    }

    /**
     * @return the loginPanel2
     */
    public LoginPanel2 getLoginPanel2() {
        return loginPanel2;
    }

    /**
     * @param loginPanel2 the loginPanel2 to set
     */
    public void setLoginPanel2(LoginPanel2 loginPanel2) {
        this.loginPanel2 = loginPanel2;
    }

    /**
     * @return the backgroundLain1
     */
    public pkl53.imageClass.BackgroundLain getBackgroundLain1() {
        return backgroundLain1;
    }

    /**
     * @param backgroundLain1 the backgroundLain1 to set
     */
    public void setBackgroundLain1(pkl53.imageClass.BackgroundLain backgroundLain1) {
        this.backgroundLain1 = backgroundLain1;
    }

    /**
  

    /**
     * @return the importButton
     */
    public javax.swing.JButton getImportButton() {
        return hometButton;
    }

    /**
     * @param importButton the importButton to set
     */
    public void setImportButton(javax.swing.JButton importButton) {
        this.hometButton = importButton;
    }

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return jButton1;
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1) {
        this.jButton1 = jButton1;
    }

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return importButtonNewPanel;
    }

    /**
     * @param jButton2 the jButton2 to set
     */
    public void setjButton2(javax.swing.JButton jButton2) {
        this.importButtonNewPanel = jButton2;
    }

    /**
     * @return the jDialog1
     */
    public javax.swing.JDialog getjDialog1() {
        return jDialog1;
    }

    /**
     * @param jDialog1 the jDialog1 to set
     */
    public void setjDialog1(javax.swing.JDialog jDialog1) {
        this.jDialog1 = jDialog1;
    }

    /**
     * @return the jFileChooser1
     */
    public javax.swing.JFileChooser getjFileChooser1() {
        return jFileChooser1;
    }

    /**
     * @param jFileChooser1 the jFileChooser1 to set
     */
    public void setjFileChooser1(javax.swing.JFileChooser jFileChooser1) {
        this.jFileChooser1 = jFileChooser1;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLayeredPane1
     */
    public javax.swing.JLayeredPane getjLayeredPane1() {
        return jLayeredPane1;
    }

    /**
     * @param jLayeredPane1 the jLayeredPane1 to set
     */
    public void setjLayeredPane1(javax.swing.JLayeredPane jLayeredPane1) {
        this.jLayeredPane1 = jLayeredPane1;
    }

   
    /**
     * @return the updateDialog
     */
    public javax.swing.JDialog getUpdateDialog() {
        return updateDialog;
    }

    /**
     * @param updateDialog the updateDialog to set
     */
    public void setUpdateDialog(javax.swing.JDialog updateDialog) {
        this.updateDialog = updateDialog;
    }

    /**
     * @return the updatePanel1
     */
    public pkl53.view.UpdatePanel getUpdatePanel1() {
        return updatePanel1;
    }

    /**
     * @param updatePanel1 the updatePanel1 to set
     */
    public void setUpdatePanel1(pkl53.view.UpdatePanel updatePanel1) {
        this.updatePanel1 = updatePanel1;
    }

    /**
     * @return the usahaEntriBuuton
     */
    public javax.swing.JButton getUsahaEntriBuuton() {
        return usahaEntriButton;
    }

    /**
     * @param usahaEntriBuuton the usahaEntriBuuton to set
     */
    public void setUsahaEntriBuuton(javax.swing.JButton usahaEntriBuuton) {
        this.usahaEntriButton = usahaEntriBuuton;
    }

}
