/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkl53.view;

import java.awt.AWTEvent;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Window;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import pkl53.controller.CardLayoutController;
import pkl53.controller.LoginController;


/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame {

    
    private LoginController loginController;
   private CardLayout cardController;
    
    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
        initComponents();
        
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
   
        cardController = (CardLayout) this.getMainPanel().getLayout();
        homePanel1.setmainFrame(this, mainPanel, cardController);
        homePUPanel1.setmainFrame(this, mainPanel, cardController);
        dataEntriPekerjaanPanel1.setmainFrame(mainPanel);
        dataEntriUsahaPanel1.setmainFrame(mainPanel);
        updatePanel1.setMainFrame(mainPanel,this);
        loginPanel1.setmainFrame(this);
        entriListing1.setmainFrame(mainPanel);
        
        
        
    }
 
    
    private JPanel getCurrentCard() {
        JPanel card = null;
        for (Component comp : mainPanel.getComponents()) {
            if (comp.isVisible() == true) {
                card = (JPanel) comp;
            }
        }
        return card;
    }
    
    
    public static JPanel getMainPanel() {
        return mainPanel;
    }
   

    public LoginPanel getLoginPanel() {
        return this.loginPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        loginPanel1 = new pkl53.view.LoginPanel();
        updatePanel1 = new pkl53.view.UpdatePanel();
        dataEntriPekerjaanPanel1 = new pkl53.view.DataEntriPekerjaanPanel();
        dataEntriUsahaPanel1 = new pkl53.view.DataEntriUsahaPanel();
        entriListing1 = new pkl53.view.EntriListing();
        homePanel1 = new pkl53.view.HomePanel();
        homePUPanel1 = new pkl53.view.HomePUPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(loginPanel1, "loginPanel");
        mainPanel.add(updatePanel1, "updatePanel");
        mainPanel.add(dataEntriPekerjaanPanel1, "dataEntri");
        mainPanel.add(dataEntriUsahaPanel1, "dataEntriUsaha");
        mainPanel.add(entriListing1, "listing");
        mainPanel.add(homePanel1, "homePanel");
        mainPanel.add(homePUPanel1, "pupanel");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl53.view.DataEntriPekerjaanPanel dataEntriPekerjaanPanel1;
    private pkl53.view.DataEntriUsahaPanel dataEntriUsahaPanel1;
    private pkl53.view.EntriListing entriListing1;
    private pkl53.view.HomePUPanel homePUPanel1;
    private pkl53.view.HomePanel homePanel1;
    private pkl53.view.LoginPanel loginPanel1;
    private static javax.swing.JPanel mainPanel;
    private pkl53.view.UpdatePanel updatePanel1;
    // End of variables declaration//GEN-END:variables


}
